### ISSUE TITLE
Unable to scroll to last item on TableView

### ISSUE THREAD

**Issue by faris-mobile89** [SCENEE/FloatingPanel#1]
I have downloaded the sample then I changed numberOfRowsInSection to 20. there is an issue on the last cell of table view (Hidden).

**Comment by SCENEE** [comment]
Thank you for #1 report of this library!  I acknowledge this issue and  I'm working to fix it now.

**Comment by SCENEE** [comment]
@faris-mobile89 
I fixed this issue on v1.0.0. Could you please try it?

**Comment by jaimeealmanza** [comment]
Hi! I've also been following this (pretty awesome btw) and I can confirm that we are able to scroll to the last item now. I have a question though, how could we avoid having extra blank space at the bottom when using a tabBar in iPhones X and up? It works fine in square screen devices.

**Comment by SCENEE** [comment]
Hello, @jaimeealmanza!
Thank you for your report. I didn't know the layout issue. I try to investigate that.
If possible, I would like you to attach a screen shot when the issue happens. it will be much helpful for me.

**Comment by SCENEE** [comment]
@jaimeealmanza  Could you try to use 'fix-surface-view-height' branch? 
```
pod 'FloatingPanel', :git => 'https://github.com/scenee/FloatingPanel.git', :branch => 'fix-surface-view-height'
```

**Comment by jaimeealmanza** [comment]
@SCENEE  I'm afraid that branch makes it clip the last cell under the tab bar. Attached screenshots for the current release and for 'fix-surface-view-height' branch.

<img width="733" alt="current release" src="https://user-images.githubusercontent.com/33677333/47454699-135ca780-d78d-11e8-99ee-1ec74ca3a373.png">
<img width="737" alt="fix-surface-view-height branch" src="https://user-images.githubusercontent.com/33677333/47454700-135ca780-d78d-11e8-9d4b-83d3c8042b34.png">

**Comment by SCENEE** [comment]
@jaimeealmanza Thank you for your screen shots! I will fix it.

**Comment by SCENEE** [comment]
Thanks, @faris-mobile89 and @jaimeealmanza.

**Comment by Urkman** [comment]
I'm currently having a similar problem.
I open a panel in 'half' size without tracking the tableview, so it stays at half, when scrolling.
Then it is not possible to scroll to the last tableview items.

When I open the panel in 'full' everything is fine...

**Comment by Urkman** [comment]
What event should I use to handle the "Height change"?
