### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by andreaslindahl** [SCENEE/FloatingPanel#110]
I discovered that my viewcontroller, which has a FloatingPanelController added to it, never gets released. The offending line seems to be this one in my viewDidLoad:

`self.fpc.addPanel(toParent: self)`

If I comment out that line, my VC gets released when it should, so I'm guessing that this creates a retain cycle of some kind. Any ideas on how to break this cycle?

I store my FloatingPanelController as a property in my VC and the FloatingPanelController's contentController is stored in a weak property in my VC.

**Comment by andreaslindahl** [comment]
I think I figured out the issue. I'm returning my VC in the FloatingPanelControllerDelegate method floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection). My VC is then retained by the FloatingPanel's layoutAdapter property, which probably creates the retain cycle.

So, the solution seems to be to NOT use the parent VC as FloatingPanelLayout... I did this, since I needed some properties and logic located in my VC in my FloatingPanelLayout instance, but that wasn't a good idea...

**Comment by SCENEE** [comment]
Thank you for your helpful report! I appreciate it 👍 

 I will try to fix the retain cycle issue.

**Comment by SCENEE** [comment]
I might misunderstood your comments. On the master branch(head: `cb54a2a`), I think this issue could be solved by that FloatingPanelLayout instance has a weak reference to a parent vc.

**Comment by andreaslindahl** [comment]
If I remember correctly, the reason I got the retain cycle was that the FloatingPanelLayout and the parent VC were one and the same, i.e. I didn't create a separate class that extended FloatingPanelLayout, but instead had my parent VC extend that protocol.

**Comment by SCENEE** [comment]
Oh, now I understand. Unfortunately, it's a defect in the library design ..😞 
But the library will be able to notice the retain cycle on the case when a user add a panel to a parent view controller applying FloatingPanelLayout.

I'm going to add a code to print the warning when the case is detected.

**Comment by andreaslindahl** [comment]
Great! It's no big deal, once I figured out why it happened :)
