### ISSUE TITLE
UITableView cut off by mask when using UITableViewController as contentViewController

### ISSUE THREAD

**Issue by datwelk** [SCENEE/FloatingPanel#112]
When using a `UITableViewController` as the `contentViewController` inside a `FloatingPanel`, the method `updateContentViewMask()` in `FloatingPanelSurfaceView.swift` causes the `UITableViewController`'s content to be cut off (the bottom 1,5 row is cut off by the mask). Due to the `@availability` directive used in `updateContentViewMask()`, the issue only arises on iOS 11 and up. Additionally, for me the issue appeared on device (iPhone 8, iOS 12.1.2), not on the simulator (iPhone X, iOS 12.1). The issue can be solved by removing the mask code in `updateContentViewMask()`.

**Comment by SCENEE** [comment]
Thanks for your report! It should be fixed and might be the same as #77.
