### ISSUE TITLE
UICollectionView nested in UIScrollView

### ISSUE THREAD

**Issue by jaytrisw** [SCENEE/FloatingPanel#12]
I have a collection view (horizontal scrolling) nested inside of a scroll view in the floating panel and scrolling does not work.

Any suggestion on a fix?

**Comment by SCENEE** [comment]
Thanks for your report. It's possible this is a problem in a gesture handling of this library. Now I'm investigating.

**Comment by SCENEE** [comment]
Could you try to use `fix-gesture-handling` branch?

**Comment by jaytrisw** [comment]
Perfect!  Thank you very much!
