### ISSUE TITLE
Floating panel jumps while dragged up

### ISSUE THREAD

**Issue by modestman** [SCENEE/FloatingPanel#126]
### Short description
Floating panel jumps while dragged up

### Expected behavior
Panel should moves smoothly

### Actual behavior
![floatingpanel example](https://user-images.githubusercontent.com/1762267/52233581-83bcae00-28d0-11e9-8e31-b4246554711b.gif)

### Steps to reproduce
- Disable `tip` and `hidden` position
- Set large `bottomInteractionBuffer`
- Floating panel `contentViewController` should contains Scroll View 
- Touch the panel inside inner scroll. Drag the panel down, under bottom interaction buffer. 
- Try drag the panel up 
- You can see that view jumps around current and middle position

**Code example that reproduces the issue**
[Link to the example project](https://github.com/modestman/TestFloatingPanel/blob/master/TestFloatingPanel/ViewController.swift)

### Environment

**Library version**
1.3.3

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.1

**Xcode version**
10.1

**Comment by SCENEE** [comment]
Thank you for your clear bug report! I will investigate this bug.

**Comment by SCENEE** [comment]
I've released v1.3.4! Thank you for your contribution.
