### ISSUE TITLE
FloatingPanelIntrinsicLayout and table view

### ISSUE THREAD

**Issue by andreaslindahl** [scenee/FloatingPanel#127]
Is it possible to use FloatingPanelIntrinsicLayout with a UITableView? I would like the height of the panel to adjust to the height of the content in the tableview in the .half position, but don't understand how to setup the bottom constraint for the tableview to achieve this.

**Comment by SCENEE** [comment]
Is it mean that you would like to always fit a height of UITableView to the visible height of a panel in the .full and .half positions?

**Comment by andreaslindahl** [comment]
Exactly, the tableview I want to display has a static number of rows, and the height of the table view is just a couple of hundred pixels, with some minor variants. I could hardcode the height of the .half position, which is what I'm doing now, but it would be nice if the height of the .half position would adapt to the actual height of the content in the table view.

**Comment by nvelichkin** [comment]
@SCENEE any progress on this?

**Comment by SCENEE** [comment]
This feature will be supported in v2.0.

**Comment by abayken** [comment]
@scenee Hello! Any news about this feature? Is it available in new versions of the library? If yes, is there any documentation how to achieve that? Thanks.

**Comment by scenee** [comment]
UITableView has no intrinsic size so FloatingPanelIntrinsicLayout can be used for it. But now you are able to use `FloatingPanelAdaptiveLayoutAnchor` for this use case, which is introduced on 2.1.0.  'Show Adaptive Panel' in the Samples app is an example for the new layout anchor. Thanks.
