### ISSUE TITLE
Tracking Scroll without swapping delegate

### ISSUE THREAD

**Issue by muukii** [SCENEE/FloatingPanel#128]
### Short description

When using ASCollectionNode of Texture (http://texturegroup.org/),
With `FloatingPanelController.track(_ :)`, Texture raise an exception.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ASCollectionView uses asyncDelegate, not UICollectionView's delegate property.'
```

### Expected behavior

The current approach what swapping delegate is so good.
But, It may have some problem with to swap delegate.
So, We need to find another approach to track scroll in scrollview.

Or, as a workaround, To tell scroll event manually will be not bad.
If the customers have this problem, We tell them this workaround.

### Steps to reproduce

set scrollView of ASCollectionNode.view to track().
then an exception will be caused by Texture.

**Code example that reproduces the issue**

### Environment

**Library version**

1.3.3

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

iOS 12.1

**Xcode version**

10.1

**Comment by SCENEE** [comment]
Thanks for your report, @muukii! I will consider the solution for each option.

**Comment by muukii** [comment]
@SCENEE 

I've found out an idea.
Find UIScrollView from UIEvent with custom sub-class of UIPanGesture.
What do you think?

https://twitter.com/i/timeline

**Comment by SCENEE** [comment]
I'm so sorry to be too late for my reply. I've been so busy recently.

At first, You idea is great 😎 Don't come up with it. Now the library adds a target to UIScrollView.panGestureRecognizer to control a scroll view. But even now it's not enough. I'm happy for you to try to improve the scroll tracking with the hack 😄 

Then I'm going to talk about this issue. In conclusion, the hack doesn't seem to be working for the use case for which the library uses the swapping delegate. The use case is that a user scroll seamlessly after a user moves a panel from .tip/.half to .full. Therefore, the library have to control or prevent scroll deceleration after finger up.

It would be great for the library to allow a user to use Texture in a panel and it should be. So now I'm trying to replace swapping delegate by adding a display link to prevent scroll deceleration after finger up 👍 

If you have any ideas, I'm happy for you to let me know!

**Comment by muukii** [comment]
@SCENEE 

Thank you
I know what you think, and I may know what you want.
We have to control the deceleration of UIScrollView when moving the FloatingPanel.

I've also tried to find a way of solution for that.
and then, I've found a way of this.

https://github.com/muukii/Rideau/blob/develop/Rideau/RideauInternalView.swift#L465

**Comment by SCENEE** [comment]
Thank you for your mention! (I'm sorry to be late a bit) That's working 🎉 
I tried to use `UIScrollView.setContentOffset(_:animated:)` before, but it was working because I didn't use it with `DispatchQueue.main.async`!  

I created a draft PR #151 with `remove-swapping-scroll-delegate` branch. If you have time, I'm pleased that you check it.

**Comment by SCENEE** [comment]
@muukii 
I merged `remove-swapping-scroll-delegate` branch to master. Thanks to you, I could remove swapping scroll delegate and make the control of a scroll deceleration well🎉 I appreciate it👍
