### ISSUE TITLE
'dismissSwizzling' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by agisilaos** [SCENEE/FloatingPanel#130]
### Short description

Hello,

I'm trying to run my app after installing & configuring FloatingPanel but I get this weird error.

<img width="786" alt="screenshot 2019-02-05 17 36 44" src="https://user-images.githubusercontent.com/10944108/52284232-aa302700-296c-11e9-88c4-9c44606f0703.png">

I really don't know what's happening since I followed the instructions to install it. Any ideas?

### Environment

**Library version:** 1.3.3

**Installation method**

- [X] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)** Minimun iOS: 10

**Xcode version** Version 10.1 (10B61)

**Comment by SCENEE** [comment]
What version of Swift did you use? I guess that is 3.2 and this can be resolved with Swift 4.0 and later.

**Comment by agisilaos** [comment]
That was it, I was able to resolve the issue. Thanks for the quick reply.
