### ISSUE TITLE
FloatingPanel can be dragged outside safe area

### ISSUE THREAD

**Issue by Pitchanai** [SCENEE/FloatingPanel#133]
### Short description
FloatingPanel can be dragged outside safe area, including top and bottom.

### Expected behavior
FloatingPanel stay inside safe area

### Actual behavior
FloatingPanel can sometimes be dragged outside the safe area. If the panel was once able to dragged outside the safe area, it will be able forever until recreate view.

![image](https://user-images.githubusercontent.com/13790777/52696543-d0c01480-2fa1-11e9-9cbd-844c8c690217.png)

![image](https://user-images.githubusercontent.com/13790777/52696582-e7ff0200-2fa1-11e9-99c8-8958bc70e6d2.png)

### Steps to reproduce
Add FloatingPanel inside view which have navigation bar

**Code example that reproduces the issue**

### Environment

**Library version**
1.3.3

**Installation method**

- [x ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
iOS 12.1

**Xcode version**
10.1

**Comment by SCENEE** [comment]
Thanks for your report! This should be fixed in #135. It will be released in v1.3.5 👍
