### ISSUE TITLE
Broken height for half and tip modes on iPhone X

### ISSUE THREAD

**Issue by vovkaprigarin** [SCENEE/FloatingPanel#137]
### Short description
Only for X-type devices
Bottom constraint will decrease if move panel without position changing. Example: for bounce

### Expected behavior
Bottom constraint doesn't decrease and consider height for special gesture

### Actual behavior
Bottom constraint decrease size and doesn't consider height for special gesture

### Steps to reproduce
0. (in my case) use only half and tip modes, with custom height
1. Launch on iPhone X
2. Programmatically open half size (or by yourself)
3. Swipe up, for bouncing
4. Panel will move to bottom on special gesture height value!!
5. Swipe down to small(tip mode) size
6. Swipe down one more time
7. Panel will move to bottom on special gesture height value!!

**Code example that reproduces the issue**

### Environment
Simulator iPhone XS Max

**Library version**
1.3.4

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.1

**Xcode version**
10.1

**Comment by SCENEE** [comment]
Thanks for your report! I will check this issue in this week.

**Comment by vovkaprigarin** [comment]
@SCENEE Hi. Have you any results?

**Comment by SCENEE** [comment]
I'm sorry to be late. What does "special gesture height" mean? I'm pleased with a screen record when the issue happens!

**Comment by vovkaprigarin** [comment]
@SCENEE it's mean special area on the bottom of X, 34px (If I remember it right)

**Comment by vovkaprigarin** [comment]
@SCENEE I will record screen for you ;)

**Comment by vovkaprigarin** [comment]
@SCENEE branch 'fix-safeareainsets' fixed this issue!
