### ISSUE TITLE
can width of overlay view can be reduced?

### ISSUE THREAD

**Issue by kunusiths** [SCENEE/FloatingPanel#138]
### Short description
i mean width of scroll view if reduced,map view can be seen partially while scrolling.
in your default case, scroll view is completely blocking map view.How to reduce width of the Sliding pan table view please explain

![screen shot 2019-02-23 at 8 17 19 pm](https://user-images.githubusercontent.com/46209817/53287889-31243280-37a8-11e9-9727-a470f71c6845.png)

**Comment by kunusiths** [comment]
got it how to do.

**Comment by ajRiverav** [comment]
@sandeepk000 can you please share the solution for other to see?

**Comment by ajRiverav** [comment]
for other users to benefit, this is how I did it. 

1) Subclass FloatingPanelLayout (e.g. class MyLayout: FloatingPanelLayout)
2) Create method: 

`     public func prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint] {
        // Constraints are created programmatically. Ref.
        // https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ProgrammaticallyCreatingConstraints.html
            return [
                surfaceView.leadingAnchor.constraint(equalTo: view.layoutMarginsGuide.leadingAnchor),
                surfaceView.trailingAnchor.constraint(equalTo: view.layoutMarginsGuide.trailingAnchor) ]
    }`

In the example above, I have programmatically created two constraints. See reference for any question. 
3) In your view controller, implement FloatingPanelControllerDelegate's method floatingPanel. E.g. 

`func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
        return GreetingFloatingPanelLayout()
    }`
