### ISSUE TITLE
detail table view gap with previous table scroll view

### ISSUE THREAD

**Issue by sandeepk000** [scenee/FloatingPanel#139]
after presenting detail table view 
this is my first scroll view(main view)
![screen shot 2019-02-24 at 1 33 27 am](https://user-images.githubusercontent.com/46209817/53291137-7199a580-37d4-11e9-8f33-bec080dc0afe.png)

and after pressing on its cell,detail table vc is added by one more floating panel
![screen shot 2019-02-24 at 1 34 13 am](https://user-images.githubusercontent.com/46209817/53291153-8ece7400-37d4-11e9-9ba2-a0d19e084941.png)

there is some gap between detail table view and first table view please help

**Comment by SCENEE** [comment]
I make sure to understand your usage of FP to fix it. 
* Is there two panels as modality, or as child VCs? 
* Is a panel of the detail table vc presented or added a pane of the main view?

**Comment by kunusiths** [comment]
Two panels are added as child.

Second panel is added as panel view on second instance of floating panel controller

**Comment by scenee** [comment]
I hope it's fixed on 2.x.
