### ISSUE TITLE
Can not install 1.3.5, cocoa pod sees only 1.0.0

### ISSUE THREAD

**Issue by djdance** [SCENEE/FloatingPanel#140]
**Installation method**
- [ ] CocoaPods

I did 
`> pod search FloatingPanel --simple`

output is:

> 
> -> FloatingPanel (1.0.0)
>    FloatingPanel is a simple and easy-to-use UI component of a floating panel interface
>    pod 'FloatingPanel', '~> 1.0.0'
>    - Homepage: https://github.com/SCENEE/FloatingPanel
>    - Source:   https://github.com/SCENEE/FloatingPanel.git
>    - Versions: 1.0.0, 0.9 [master repo]
> (END)
> 

Obviously pod install installs 1.0.0 too. How to fix? Thanks

**Comment by djdance** [comment]
this works:

`pod 'FloatingPanel', :git => 'https://github.com/SCENEE/FloatingPanel.git'`

**Comment by vovkaprigarin** [comment]
`pod 'FloatingPanel'`

**Comment by djdance** [comment]
> `pod 'FloatingPanel'`

and this will install 1.0.0 and this is the reason why I searched for all versions. It sees only 1.0.0 by default. Maybe I should change defaults somehow?

**Comment by vovkaprigarin** [comment]
try `pod update`

**Comment by billidani7** [comment]
It seems that you have out-of-date source repos

try `pod install --repo-update`

**Comment by djdance** [comment]
_pod update_ - it works, thank you all.
