### ISSUE TITLE
TableView inside drawer is not smooth.

### ISSUE THREAD

**Issue by jayarajb1116** [SCENEE/FloatingPanel#148]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Steps to reproduce

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

**Xcode version**

**Comment by SCENEE** [comment]
I've already improve the behavior in v1.4.0. If you already use the version, I'm pleased for you to fill out more detail for your request. Thx!
