### ISSUE TITLE
Swift version downgraded from 4.2 to 4.0  in FloatingPanel 1.4.0 and causing compile issues

### ISSUE THREAD

**Issue by ugenlik** [SCENEE/FloatingPanel#149]
Why the Swift version downgraded to 4.0 , it causing crashes and forces user to downgrade the version.

https://github.com/SCENEE/FloatingPanel/commit/dc7f6d58f983a6214262b90edc5732240893f6c9

Was the version previously wrong?   I was able to use the version `FloatingPanel (1.3.1)` with Swift 4.2 fine....

**Comment by SCENEE** [comment]
Could you please see PR #121?

**Comment by SCENEE** [comment]
Yes, it is. The reason is here, https://github.com/SCENEE/FloatingPanel/pull/111#issuecomment-456619728. However this library should support Swift 5 soon.
