### ISSUE TITLE
Why .hidden is forbidden in init of supportedPositions ?

### ISSUE THREAD

**Issue by djdance** [SCENEE/FloatingPanel#150]
### Short description
I see .hidden is removed from supportedPositions during initialization. Why? Could you leave it as is?

### Expected behavior
I want to set it so, then call panel in hidden state and stop playing with weird _case .tip: return nil_:

```
        var initialPosition: FloatingPanelPosition {
            return .hidden
        }

```
### Actual behavior
But now .hidden is is removed from supportedPositions, and it obviously leads to crash

> assert(supportedPositions.contains(layout.initialPosition),
>                "Does not include an initial potision(\(layout.initialPosition)) in supportedPositions(\(supportedPositions))")

**Library version**
1.4.0

**Installation method**

- [ ] CocoaPods

**iOS version(s)**
10

**Xcode version**
10.1

**Comment by SCENEE** [comment]
Your proposal makes sense to me!  The reason why is just because I don't expect the use case when `.hidden` is used as an initial position.

I created PR #156. It will allows you to use `.hidden` initial position

**Comment by atereshkov** [comment]
This is a very useful feature! Look forward to seeing it in the new version! Thanks for the work!

**Comment by uniqby** [comment]
+1 Waiting to this feature
