### ISSUE TITLE
Jump while dragged up or down

### ISSUE THREAD

**Issue by vovkaprigarin** [SCENEE/FloatingPanel#154]
### Short description
Up from .tip to .half and from .half to .tip position is incorrect while dragging.
This behavior was appeared on library version 1.4.0, previous version work perfectly.

### Expected behavior
library version 1.3.5 and correct behavior:
![ezgif-1-76694c1667d7](https://user-images.githubusercontent.com/10516315/53934264-b676e380-40d4-11e9-8388-e19d7605ceef.gif)

### Actual behavior
library version 1.4.0 and incorrect behavior:
![ezgif-1-22e3941c8930](https://user-images.githubusercontent.com/10516315/53934274-bbd42e00-40d4-11e9-905d-634d2e520614.gif)

### Environment
Simulator iPhone 5s iOS 12.1

**Library version**
1.4.0

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.1

**Xcode version**
10.1

**Comment by SCENEE** [comment]
I will investigate the issue. Thanks for your report!

**Comment by SCENEE** [comment]
I tested this issue with the [Samples app](https://github.com/SCENEE/FloatingPanel/tree/master/Examples/Samples) on v1.4.0, but unfortunately it isn't able to reproduce this issue. Could you please attach a sample code to reproduce this?

**Comment by SCENEE** [comment]
I could watch the issue once! But I’ve not be able to find a concrete repo way...

**Comment by vovkaprigarin** [comment]
@SCENEE Ok, I will create sample and post in this issue, but later, ok?

**Comment by SCENEE** [comment]
Of course, @vovkaprigarin!  I appreciate your contribution 👍

**Comment by SCENEE** [comment]
@vovkaprigarin
I could fix this issue on `fix-safeareainsets` branch!
I found a safe area inset issue related to top/bottom dragging of a panel with a large title navigation bar. The branch resolves the issue. I'm not sure it's same, but it's possible this issue is also related to a safe area inset.  So could you try the branch?

**Comment by pakko972** [comment]
Hi all, I had the exact same issue and branch `fix-safeareainsets` fixed it.

**Comment by SCENEE** [comment]
Thanks, all! I created PR #168. It will be released in v1.4.1 soon.

**Comment by vovkaprigarin** [comment]
@SCENEE fix-safeareainsets fixed this issue partially :) Now panel not jumping, but still moving to top. I will check for moving issue 167 and branch fix-top-dragging-boundary! Thx!

**Comment by vovkaprigarin** [comment]
Yep, fix-top-dragging-boundary fixes it completely!

**Comment by vovkaprigarin** [comment]
@SCENEE how check both fixes fix-top-dragging-boundary and fix-safeareainsets ?

**Comment by SCENEE** [comment]
I'm going to rebase `fix-top-dragging-boundary` soon by the master branch already merged `fix-safeareainsets`. I'll let you know it in this issue when I did.  I'm pleased that you will check the new `fix-top-dragging-boundary` branch(both of fix-top-dragging-boundary and fix-safeareainsets)!

**Comment by SCENEE** [comment]
@vovkaprigarin 
I prepared the new `fix-top-dragging-boundary` branch. I polish the previous one. I'm pleased that you check it.

**Comment by Lukaz32** [comment]
Should the problem be solved in the `fix-top-dragging-boundary` branch? 
I still get the weird behaviour on it.<br> I've set my `full` position at `-44`, and also `fpc.additionalSafeAreaInsets = UIEdgeInsets(top: -44, left: 0, bottom: 0, right: 0)` <br> but after scrolling around it never returns to the correct position.

![giphy](https://user-images.githubusercontent.com/544727/55002111-53db7e00-4fd6-11e9-87e7-d583a2795573.gif)

**Comment by SCENEE** [comment]
@Lukaz32 
No, the branch intends to solve #167. But the problem should be fixed. This library hasn't taken care of a use case using it with `fpc.additionalSafeAreaInsets`. So could you please make a new issue and attach your modified Maps app?

**Comment by Lukaz32** [comment]
Oh, my bad, I thought it was related to this issue. Sure thing, I'll file a new issue on this matter. Thanks

**Comment by vovkaprigarin** [comment]
@SCENEE All is well. Works perfectly, Thank you!

**Comment by SCENEE** [comment]
@Lukaz32 
Thanks! I will be sure to fix it.

@vovkaprigarin 
Thank you, too! I could fix the fundamental issues by your contribution. I really appreciate it.
