### ISSUE TITLE
Is it possible to set footer to drawer? As default it should be visible.

### ISSUE THREAD

**Issue by jayarajb1116** [SCENEE/FloatingPanel#160]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Steps to reproduce

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

**Xcode version**

**Comment by SCENEE** [comment]
It's not supported in a container view controller, but `FloatingPanelController` is just a view controller containing the surface and backdrop views. https://github.com/SCENEE/FloatingPanel#view-hierarchy
Therefore you can add a footer view above the surface view 👍 
(Using Xcode view debugger when a floating panel is added will help you ☺️)

**Comment by SCENEE** [comment]
A footer of a content view controller can be visible using an elastic layout implementing in #145. So I reopen this issue.

**Comment by SCENEE** [comment]
The lib has already supported the fixed footer in `.fitToBounds` mode . Thanks.
