### ISSUE TITLE
[Feature] iOS 9 Support

### ISSUE THREAD

**Issue by AlexLamond** [SCENEE/FloatingPanel#163]
Would it be possible to make FloatingPanel compatible with iOS 9 - I know this is unlikely but when trying to reach as big a user base as possible it would be nice for app deployment

**Comment by SCENEE** [comment]
This library is tightly coupled with `UIViewPropertyAnimator`(available on iOS10+). So It's hard to support iOS 9 because this library has to have particular APIs only for iOS9 and I have no time to do it.
