### ISSUE TITLE
UITableView's didSelectRowAt not called after swiping

### ISSUE THREAD

**Issue by peterstojanowski** [SCENEE/FloatingPanel#164]
### Short description
There is a really annoying bug when the contentViewController of the FloatingPanelController has a UITableView. When you swipe up or down quickly so that the floating panel bounces a bit at the end of animation, the first tap on UITableView cell is ignored - the delegate method `tableView:didSelectRowAt:` is not called. It's being called the second time you tap on a cell or when you swipe slowly and then tap. There must be an issue with intercepting some gestures when UIScrollView decelerates but I didn't have much time to investigate properly.

### Expected behavior
The `tableView:didSelectRowAt:` is called every time.

### Actual behavior
The `tableView:didSelectRowAt:` is not called the first time after scrolling quickly.

### Steps to reproduce
Can be easily reproduced using the Maps example by adding some logs to `tableView:didSelectRowAt:` to see they are not printed out after scrolling fast and tapping on a cell.

**Code example that reproduces the issue**

### Environment

**Library version**
1.4.0
**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12
**Xcode version**
10.1

**Comment by RpX974** [comment]
Hi, I have the same issue.
Did you find a solution ?

**Comment by SCENEE** [comment]
I acknowledged this issue. I will try to fix it.

**Comment by SCENEE** [comment]
How about `fix-tap-abort` branch(7a51219)?

**Comment by peterstojanowski** [comment]
Yes, this fixes the issue. Thanks.

**Comment by RpX974** [comment]
Still same for me :/

**Comment by peterstojanowski** [comment]
I double checked that on the Maps example and looks like it's only partially fixed. It works now when you swipe up from tip to half and half to full but it's still broken when you swipe from full to half.
@RpX974 can you confirm that?

**Comment by RpX974** [comment]
I'm using from tip to full, so I can confirm for that. I will try the other ways.

**Comment by RpX974** [comment]
Yes, from tip to half, it works

**Comment by RpX974** [comment]
Nevermind, it doesn't work too, I scrolled before when I tried from tip to half.

**Comment by RpX974** [comment]
Ok, I found something. When I try to change the height constraint of a view in "floatingPanelDidChangePosition" for the tip position, I got the issue. But if I don't change the height, I don't have the issue.

**Comment by SCENEE** [comment]
This issue might be related to this bug ,https://bugs.swift.org/browse/SR-10257.
See also here, https://stackoverflow.com/questions/55592341/xcode-10-2-protocol-inheritance-issue.

**Comment by peterstojanowski** [comment]
@SCENEE I doubt that. This issue can be reproduced using Xcode 10.1. The bugs you're talking about are related to Xcode 10.2.

**Comment by SCENEE** [comment]
Thanks for your quick feedback, @peterstojanowski 😀
I struggled with this issue  for a while and at last I found a solution to make it better!
I know it doesn't defeat this issue completely, but eases the problem.
I pushed 9076ba8 commit. I'm pleased to check it out 👍

**Comment by SCENEE** [comment]
Hmm... the commit might not fixed it...

**Comment by SCENEE** [comment]
Hmm.... It's also working well partially....

**Comment by congmn** [comment]
I found out that Apple Maps has the same bug.

**Comment by SCENEE** [comment]
Thanks for your sharing, @congmn! 
Then I think it's hard to fix this issue completely without modifying a tap gesture handling of UITableView.  So I'm going to merge #185 to master.

**Comment by ThangTruong921** [comment]
I have a suggestion to solve this problem. 
You can put the button into the cells of the table. 
I succeeded with this solution.

**Comment by SCENEE** [comment]
I merged a solution into master to ease this issue 👍 Thanks all 🎉 
I closed this issue for now, but I would like to fix it as expected so welcome any ideas and mentions for this :relieved:.

**Comment by HappyIosDeveloper** [comment]
I Still have this issue!
