### ISSUE TITLE
[Question] Is it possible to display the panel on top of everything?

### ISSUE THREAD

**Issue by SpiderUnicorn** [SCENEE/FloatingPanel#166]
I would like to have the panel over the tab bar and navigation bar. Is there a way to configure the floating panel in this way?

**Comment by SCENEE** [comment]
Yes! 😄  It's just to present a panel modally https://github.com/SCENEE/FloatingPanel#present-a-floating-panel-as-a-modality. If you set the backdrop alpha to 0.0 in the layout object, user interactions of a backed content is enabled.
