### ISSUE TITLE
half mode panel is dragged to the top of the screen !

### ISSUE THREAD

**Issue by musa-almatri** [SCENEE/FloatingPanel#167]
### Short description
after upgrading to v1.4.0
a panel support [.half, .tip] modes. when the panel in half mode, user shouldn't be able to drag it toward the full mode. or the bouncing should stop when reaching to the half mode.

### Expected behavior
half mode panel should stop bouncing when it reached the half mode offset

### Actual behavior
half mode panel is dragged to the top of the screen

### Steps to reproduce
create a panel that support [.half, .tip] modes.
try to drag it to the top of the screen

### Environment
v1.4.0

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.1

**Xcode version**
10

**Comment by vovkaprigarin** [comment]
duplicate

**Comment by vovkaprigarin** [comment]
https://github.com/SCENEE/FloatingPanel/issues/154

**Comment by SCENEE** [comment]
Thanks, @vovkaprigarin! I confirmed this issue, but it looks different from #154.
I found a problem on the top boundary in dragging.

@musa-almatri, I pushed `fix-top-dragging-boundary` branch. It should fix this issue 👍

**Comment by vovkaprigarin** [comment]
It's works for me, thx!

**Comment by musa-almatri** [comment]
great, this fixed the issue, thanks @SCENEE.
