### ISSUE TITLE
Is it possible to modify the height of the panel at run time?

### ISSUE THREAD

**Issue by willianB** [scenee/FloatingPanel#171]
### Short description
I'm trying to change the height of the main panel at runtime, but I have not found the way

### Expected behavior
Allow to change the height of the panel at run time

### Actual behavior
currently apparently does not Allow to change the height of the panel at runtime

### Environment

**Library version**
v1.4.0

**Installation method**

- [ ] CocoaPods
- [X] Carthage
- [ ] Git submodules

**iOS version(s)**
10

**Xcode version**
10

**Comment by SCENEE** [comment]
Good suggestion! I will consider the use case 👍

**Comment by junyun0516** [comment]
I also put a tableView in the panel and can not cover the scroll area when the height is .half.

**Comment by R-Ashh** [comment]
is this feature added to the library yet? I'm having the same issue. thanks for the great library.

**Comment by scenee** [comment]
It's dup of https://github.com/scenee/FloatingPanel/issues/127. Thank you.
