### ISSUE TITLE
Missing pan gestures (edit: in UIPageViewController)

### ISSUE THREAD

**Issue by GerdC** [SCENEE/FloatingPanel#172]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Short description
no pan gestures call methods floatingPanelDidMove and floatingPanelWillBeginDragging when not in state .full

### Expected behavior
when panning, calls to the delegate methods floatingPanelDidMove, floatingPanelWillBeginDragging and floatingPanelDidEndDragging are expected, the floatig panel should move visually.

### Actual behavior
The expected behaviour happens only in state .full.

in state .half and .pin, only floatingPanelDidEndDragging is called, the FloatingPanelController does not move.

### Steps to reproduce
I have a tabBarViewController containing a UIViewController.
This UIViewController calls fpc.addPanel(toParent: self, animated: true)
The contentViewController is a tableViewController.

The visual size does not matter: Using
    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 16.0
        case .half: return 702.0
        default: return nil
        }
    }
.half is almost as long as .full, is doesn't make a difference.

The mntioned delegate methods floatingPanelDidMove, floatingPanelWillBeginDragging and floatingPanelDidEndDragging have no implementation apart from printing debug lines to the console.

**Code example that reproduces the issue**

### Environment

**Library version**
FloatingPanel (1.4.0)
**Installation method**

- [X] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.1

**Xcode version**
10.1

**Comment by GerdC** [comment]
Found the solution: 

The viewController that shows the FloatingPanelController must not be a page of a pageViewController.

You might add this as a precondition.

**Comment by SCENEE** [comment]
@GerdC 
I confirmed this issue can be resolved by `FloatingPanelControllerDelegate.floatingPanel(_:shouldRecognizeSimultaneouslyWith:)`

Here is a sample code 👍 

```swift
let page1 = FloatingPanelController(delegate: self)
page1.view.backgroundColor = .blue
page1.show()
...

func floatingPanel(_ vc: FloatingPanelController, shouldRecognizeSimultaneouslyWith gestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
}
```
