### ISSUE TITLE
Swift 3+ FloatingPanelController Subclassing

### ISSUE THREAD

**Issue by xysverma** [SCENEE/FloatingPanel#173]
I am trying to modify UI of FloatingPanelController to match my app requirement but since FloatingPanelController is not declared as open, i can't subclass it while using pod.

Is it possible to make it open and allow subclassing ?

**Comment by SCENEE** [comment]
Yes. it's possible! I created `allow-subclassing` branch. How about it?

**Comment by SCENEE** [comment]
Now FloatingPanelController allows subclassing it 🐱

**Comment by xysverma** [comment]
Awesome. Thanks :)
