### ISSUE TITLE
Prevent panel from going below a certain Y value

### ISSUE THREAD

**Issue by liriz002** [SCENEE/FloatingPanel#174]
### Short description
Hey there. Firstly, thank you all for such an incredible library. This is truly a lifesaver!
I just installed it and I've been playing with it and I basically enabled two anchor positions only: .full and .tip.

However, if I scroll down hard enough, it'll put the panel SO low that I cannot bring it back up due to the iPhone X's home button. 

### Expected behavior
It would only go as low as the .tip position. However, it passes it.

### Actual behavior
It goes down to where the top of the panel is just a bit higher than the home button, making it hard (if not impossible) to scroll back up.

How can I go about putting a stop so that it doesn't go below a certain Y value, possibly with a little spring animation?

### Steps to reproduce
I think this is default behavior, so just scroll down very hard and you'll see it happening.

**Code example that reproduces the issue**
This is my custom floating panel layout:

`class MovieDetailsFloatingPanelLayout: FloatingPanelLayout {
    public var initialPosition: FloatingPanelPosition {
        return .tip
    }
    
    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 100.0 // A top inset from safe area
        //case .half: return n // A bottom inset from the safe area
        case .tip: return 80.0 // A bottom inset from the safe area
        default: return nil // Or `case .hidden: return nil`
        }
    }
}
`

### Environment

**Library version**
1.4.0

**Installation method**

- [X] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
10.3

**Xcode version**
10

Thank you!

**Comment by liriz002** [comment]
So, by adding the middle anchor once again, this does not happen anymore. Looks like that by taking out the middle position, it adds another position (the one I mention above) as a possible state.

Is there any way to have only 2 positions (e.g. full and tip), and then prevent it from going down more than the tip position?

**Comment by SCENEE** [comment]
This seems to be a bug of this library. I will try to fix it. Thanks!

**Comment by liriz002** [comment]
Thank you!

**Comment by SCENEE** [comment]
Could you please try to set `bottomInteractionBuffer` to zero?

```swift
class MovieDetailsFloatingPanelLayout: FloatingPanelLayout {
    ...
    var bottomInteractionBuffer: CGFloat = 0.0 
}
```

**Comment by liriz002** [comment]
Hey there!

I tried adding this while again commenting out .half position. Unfortunately, swiping down while in the .full position brings it to that same very low position (below the .tip).

Please let me know if you'd like me to try anything else.

**Comment by florianldt** [comment]
try to add the `var supportedPositions: Set<FloatingPanelPosition>` property in your custom`FloatingPanelLayout`.

From https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelLayout.swift#L48 , it is said that:

> By default, it returns all position except for `hidden` position.

That means you want only 2 positions but 3 are supported from your layout.

For your particular case, I guess that
```swift
var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .tip]
    }

    public var initialPosition: FloatingPanelPosition {
        return .tip
    }

    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 100.0 // A top inset from safe area
        case .tip: return 80.0 // A bottom inset from the safe area
        default: return nil // Or `case .hidden: return nil`
        }
    }
```

should make it.

Let me know about it.

**Comment by SCENEE** [comment]
v2 has supported this use case to reimplement the animation. I wrote an example [here](https://github.com/SCENEE/FloatingPanel/blob/master/Documentation/FloatingPanel%202.0%20Migration%20Guide.md#deprecated-apis-1). Thanks for all.
