### ISSUE TITLE
Dismiss drawer entirely when I swipe down

### ISSUE THREAD

**Issue by agisilaos** [SCENEE/FloatingPanel#175]
Hello @SCENEE. I'm trying to dismiss the drawer entirely when I swipe down but I'm not exactly sure how to do that. I already read the docs and I couldn't find the answer I'm looking for. I would love your help on this one since I'm trying to work on that for a couple of days now. I'm using FloatingPanel as a modal and here's my code. 

```swift
func presentDrawer() {
        let storyboard = UIStoryboard(name: "myStoryboard", bundle: nil)
        let addLogsController = storyboard.instantiateViewController(withIdentifier: "MyViewController")
        
        // TO-DO: Change the name of the variable to something less broad. 
        let fpc = FloatingPanelController()
        let contentVC = addLogsController
        fpc.set(contentViewController: contentVC)
        
        fpc.isRemovalInteractionEnabled = true // Optional: Let it removable by a swipe-down
        
        self.present(fpc, animated: true, completion: nil)
    }
```
With the code above when I swipe down to dismiss it, the result is:

<img width="419" alt="Screenshot 2019-03-28 19 41 33" src="https://user-images.githubusercontent.com/10944108/55180353-1c193580-5192-11e9-9c92-18a7b7e6a3df.png">

Unfortunately, I can't dismiss it entirely. How I can achieve that? Thanks in advance

--

**Note:** I already checked similar issues but didn't find the answer I was looking for.

**Comment by atereshkov** [comment]
`fpc.isRemovalInteractionEnabled = true `

works for me

**Comment by agisilaos** [comment]
@atereshkov Unfortunately it doesn’t work for me for some weird reason. 🤔 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by agisilaos** [comment]
@SCENEE Any ideas what may be happening here? I still didn't manage to fix the issue. Any advice/tips is appreciated.

**Comment by SCENEE** [comment]
Could you please let me know your layout and behavior definitions?

**Comment by agisilaos** [comment]
@SCENEE Here's my layout for the drawer:

```swift
class MyFloatingPanelLayout: FloatingPanelLayout {
    public var initialPosition: FloatingPanelPosition {
        return .half
    }
    
    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 16.0  // A top inset from safe area
        case .half: return 205.0 // So we can have the desirable height for the drawer
        case .tip: return nil // Because it's nil that's why we can swipe down and dismiss the drawer
        default: return nil // Or `case .hidden: return nil`
            
        }
    }
}
```

**Comment by agisilaos** [comment]
My initial implementation was even without layout and behavior definitions. I wanted it to work as a modal. The code I wrote was as it is above and I'm not sure how to move forward.

```swift
func presentDrawer() {
        let storyboard = UIStoryboard(name: "myStoryboard", bundle: nil)
        let addLogsController = storyboard.instantiateViewController(withIdentifier: "MyViewController")
        
        // TO-DO: Change the name of the variable to something less broad. 
        let fpc = FloatingPanelController()
        let contentVC = addLogsController
        fpc.set(contentViewController: contentVC)
        
        fpc.isRemovalInteractionEnabled = true // Optional: Let it removable by a swipe-down
        
        self.present(fpc, animated: true, completion: nil)
    }
```

**Comment by gabrieloliva** [comment]
It doesn't work here as well.

When I drag the FloatingPanelController to the bottom of the screen, it just go to `.hidden` mode, but still there.

**Comment by gabrieloliva** [comment]
@agisilaos after a long debug, I found a way to get this behaviour right by implementing the `var initialPosition: FloatingPanelPosition { get }` from `FloatingPanelLayout` protocol.

**Comment by SCENEE** [comment]
I'm sorry I haven't yet reproduced this so that I can't detect the cause...

**Comment by bardonadam** [comment]
I wanted to have only .`full` or .`hidden` positions, but the swipe to dismiss wasn't working for me either.

```
public var initialPosition: FloatingPanelPosition {
        return .full
    }
    
public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
    switch position {
    case .full: return 70.0 // A top inset from safe area
    default: return nil // Or `case .hidden: return nil`
    }
}
```

After I've added `supportedPositions`, it worked:
```
public var supportedPositions: Set<FloatingPanelPosition> {
    return [.full, .hidden]
}
```

**Comment by SCENEE** [comment]
Thank, @bardonadam! I will investigate this issue again.

**Comment by SCENEE** [comment]
Finally I have understand the issue. The removal interaction is enabled on the bottom most position now. On @agisilaos's case, the bottom most position is `.tip` position. So the panel couldn't be removed from the position any more because  `.tip` inset is zero and the panel fits to a safe area bottom.
I need to consider the spec about the removal interaction and a panel behavior between `.full` + `.hidden` positions.

**Comment by XavierLost** [comment]
Manually call the method to remove it
 func floatingPanelDidEndDecelerating(_ vc: FloatingPanelController) {
        if vc.position == .hidden || vc.position == .tip {
            vc.dismiss(animated: false, completion: nil)
        }
    }

**Comment by akashnimare** [comment]
@SCENEE Is it possible to have only `full` position and dismiss the panel by swiping it down? Currently, it doesn't dismiss but stuck at the bottom position.

**Comment by bardonadam** [comment]
@akashnimare check my [comment](https://github.com/SCENEE/FloatingPanel/issues/175#issuecomment-498248778)

**Comment by akashnimare** [comment]
Oh man, it worked. Thanks 🚀
