### ISSUE TITLE
UI freezes when one of the subviews sets its frame manually

### ISSUE THREAD

**Issue by nderkach** [SCENEE/FloatingPanel#179]
### Short description

If one of the subviews with a floating panel sets its frame manually in `layoutSubviews` and also update safe area insets, it leads to an infinite calling loop caused by `safeAreaInsetsObservation`, i.e. the KVO triggers `layoutSubviews` which in its turn sets the frame and triggers `safeAreaInsetsObservation` KVO update. This, in turn, leads to a UI freeze.

### Steps to reproduce

An example would be using a custom navigation bar height for a navigation controller which is configured as `contentViewController` of `FloatingPanelController` presented modally with animation. Within `layoutSubviews` I'm calling `self.frame = ...` and this causes an infinite loop with `safeAreaInsetsObservation`. This only happens when I'm presenting `FloatingPanelController` with animation.

### Environment

**Library version**

1.4.0

**Installation method**

Cocoapods

**iOS version(s)**

12.2

**Xcode version**

10.2

**Comment by SCENEE** [comment]
Does it also happen on v1.4.1? It can be fixed on https://github.com/SCENEE/FloatingPanel/commit/68f48f714d09173dab1fa56404ac221f6bf45684 👍

**Comment by SCENEE** [comment]
I close this issue. If this still occurs on the latest version, please reopen and let me know!

**Comment by warpling** [comment]
I've observed something similar when update constraints in the panel's content ViewController's `viewDidLayoutSubviews()`. When I pause the running application I don't observe a deadlock but the UI is indeed frozen and I can't dismiss the panel without killing the app.

**Comment by warpling** [comment]
There is definitely some deeper problem here (likely with these weird workarounds I've implemented so that my UIViewController never exceed the height of the screen and break FloatingPanel) but wrapping the constraint update in a dispatch async solved the issue for now:
```
override func viewDidLayoutSubviews() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
             // Constraint setting code
        }
}
```

**Comment by warpling** [comment]
The issue turned out to be related to constraints and a specific hierarchy where I had a `UIViewController > View > UIStackView > UITableView`. The `UITableView` was trying to size itself partially based off of the stack view which was apparently causing something strange to happen. I ended up removing the `UIStackView` and placing the views more directly in the `UIViewController`'s view and the issue went away. Maybe this can help someone in the future that stumbles into this issue.

**Comment by SCENEE** [comment]
@warpling Thank you for sharing your experience! It will surely helps developers using FloatingPanel 👍
