### ISSUE TITLE
Assertion failed: Does not include an initial potision(hidden) in supportedPositions ([FloatingPanel.FloatingPanelPosition.full])

### ISSUE THREAD

**Issue by atereshkov** [SCENEE/FloatingPanel#184]
### Short description
The app is going to crash when using .hidden as an initial position.

### Expected behavior
We can use .hidden without a crash since the 1.4.1 update

### Actual behavior
Can't use .hidden as an initial position

### Steps to reproduce

**Code example that reproduces the issue**

```
    var initialPosition: FloatingPanelPosition {
        return .hidden
    }
    
    var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .hidden]
    }
    
    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 40.0
        default: return nil
        }
    }
```

### Environment

**Library version**
1.4.1

**Installation method**

- [x] CocoaPods

**iOS version(s)**
12
**Xcode version**
10.1

**Comment by SCENEE** [comment]
Hmm... I can use it 🤔 Could you please try to  clean build folder, <kbd>⌥ Option</kbd>+<kbd>⇧ Shift</kbd>+<kbd>⌘ Command</kbd>+<kbd>K</kbd>?

**Comment by atereshkov** [comment]
I already did, also tried to remove DerivedData. Nothing happened.
But will try to reinstall the pod one more time and will check it out. Looks really strange as I also see that Xcode is showing some errors (Swift 4 stuff) using 1.4.1 version with Swift 4.2... That is strange :)

**Comment by atereshkov** [comment]
Was caused by some local Xcode issues, reinstall helped so closing the issue.
