### ISSUE TITLE
No support for UITableViewController?

### ISSUE THREAD

**Issue by Antoine4011** [SCENEE/FloatingPanel#19]
Hey, I'm just starting to use your lib and wondering why you don't allow the contentViewController to be an `UITableViewController`. The reason `UITableViewController should not be the parent because the view hierarchy will be break in reusing cells.` seems a little bit odd to me. It's too bad to lose all features from UITableViewController... 

Or maybe I'm doing something wrong and it's possible? Thanks.

**Comment by SCENEE** [comment]
Do you try to add FloatingPanel into a parent view controller inherited from UITableViewController?
It can not be added into UITableViewController(the parent), but FloatingPanel allows any UITableViewController as the content view controller.

**Comment by Antoine4011** [comment]
Yes, that's why I'm trying to do. I'm curious why you choose to not allow this?

**Comment by SCENEE** [comment]
UITableViewController can't keep FloatingPanel's view in the top of the subviews because UITableViewController's view is a table view.

See this screen shot.

![screen shot 2018-10-29 at 22 31 21](https://user-images.githubusercontent.com/899487/47652846-66d65780-dbca-11e8-8b7b-bccc2edc1b39.png)

**Comment by Antoine4011** [comment]
All right, thanks for your answer. It does make sense now.
