### ISSUE TITLE
Add delegate floatingPanelWillChangePosition

### ISSUE THREAD

**Issue by Dominik777** [SCENEE/FloatingPanel#192]
Hey,

is it possible to add a delegate that gets trigged when the panel is about to snap to its target position, not after its done? My current workaround is to create a custom FloatingPanelBehavior that fires a delegate/closure when `func interactionAnimator(_ fpc: FloatingPanelController, to targetPosition: FloatingPanelPosition, with velocity: CGVector) -> UIViewPropertyAnimator {...` is called. 

Use cases would be e.g to fade certain things out in certain target positions and we cannot always rely on floatingPanelDidMove for this incase user does a fast flick/swipe. And `func floatingPanelDidChangePosition(_ vc: FloatingPanelController) {..` might be too late for this.

**Comment by SCENEE** [comment]
How about `floatingPanelDidEndDragging(_:withVelocity: targetPosition:)` or `floatingPanelWillBeginDecelerating(_:)`?

https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L521
https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L620

**Comment by Dominik777** [comment]
Hey, thanks for your reply. Let me check those out again for my use case. I remember having trouble using those. Thank you

**Comment by SCENEE** [comment]
I close this issue. Please feel free to reopen this If necessary.
