### ISSUE TITLE
AREA OF GESTURES. URGENT PROBLEM,

### ISSUE THREAD

**Issue by yuriandryu** [SCENEE/FloatingPanel#193]
[Hello.](`url`) Now the panel responds to gestures, anywhere you can touch, pull and the panel will move. I want to touch (reacted contact specific, or a specific view). For example, I want to pull the panel only for the "grabber handle" or for the area (CGRect (x: 0, y: 0, width: surfaceView.width, height: 20)). How to do it? I would be grateful for your early reply.

I want to do this because the panel is twitching when I pull UISlider.

**Comment by yuriandryu** [comment]
I decided it this way, but I really like the solution, I would like to specify the required view and not the coordinates

`func floatingPanelShouldBeginDragging(_ vc: FloatingPanelController) -> Bool {
        
        let location = vc.panGestureRecognizer.location(in: vc.surfaceView)
        let translation = vc.panGestureRecognizer.translation(in: vc.surfaceView)
        let previousLocation = CGPoint(x: location.x - translation.x, y: location.y - translation.y)
        
        return previousLocation.y < 50
    }`

**Comment by zntfdr** [comment]
Hi @yuriandryu, you can get the "Grabber Handle" view by accessing it via your `FloatingPanelController` instance.

Here's how

```swift
let fpc = FloatingPanelController()
fpc.surfaceView.grabberHandle // <-- this is the UIView you're looking for.
```

**Comment by SCENEE** [comment]
I'm sorry to be late for my reply. I considered adding the draggle area API and then I recognized the API needs to care a back-and-forth pan gesture and the pull-down action with the scroll tracking, so it can be not simple or expected for someone. 
Therefore I think a solution using `floatingPanelShouldBeginDragging` is not simpler than your solution, but is flexible for any other use cases 😌
