### ISSUE TITLE
Any chance to support presenting from left/right?

### ISSUE THREAD

**Issue by atereshkov** [SCENEE/FloatingPanel#197]
Hi there!

Thanks for the good work and stylish library!

I just wondering are you planning to include support for left to right and right to left transitions in addition to the standard one (from bottom to top)?

**Comment by SCENEE** [comment]
I'm planning to add an API to specify a moving edge(now it's `top` only) to support #108 (from top to bottom)by specifying `bottom` moving edge. It's possible for the API to provide your proposed use case when it's specified to `left` moving edge 😄 (It might need additional changes for the API implementation though.)

**Comment by az-oolloow** [comment]
This one is pretty important for iPad-centric apps, atm the control is amazing, but just a bit too big for iPad :)

**Comment by andreaslindahl** [comment]
@az-oolloow You can always change the width, if you don't want it to take up the entire width of the screen on iPad.

**Comment by SCENEE** [comment]
v2 has supported left/right positioned panel 👍
