### ISSUE TITLE
Calling FloatingPanel.move(to:animated:completion:) locks scroll view

### ISSUE THREAD

**Issue by mattt** [SCENEE/FloatingPanel#198]
### Short description

Programmatically setting the position of a floating panel using the `move(to:animated:completion:)` method causes any tracked scroll view to lock scroll position, disable bounces, and hide scroll indicators.

You might, for example, call this method from a tap gesture recognizer added to the scroll view or one of its subviews. The result is behavior that's noticeably inconsistent than if positions were changed by scrolling.

### Expected behavior

Programmatically moving a floating panel behaves the same as if positions were changed by scrolling.

### Actual behavior

The underlying scroll view is locked, with bounces and scroll indicators disabled. 

### Steps to reproduce

```
// Assuming current position is .half (note: must not be layout top-most state)
floatingPanelController.move(to: .full, animated: true)
```

### Diagnosis

Looking at the source code, I believe that the problem occurs [here](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L102-L104):

```swift
private func move(from: FloatingPanelPosition, to: FloatingPanelPosition, animated: Bool, completion: (() -> Void)? = nil) {
        if state != layoutAdapter.topMostState {
            lockScrollView()
        }
```

The call to [`lockScrollView()`](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L869-L875) appears to be missing a corresponding call to `unlockScrollView()`.

Adding the following line to the implementation should fix the error (though one concern with this approach is that won't be set until after `completion` is called):

```swift
private func move(from: FloatingPanelPosition, to: FloatingPanelPosition, animated: Bool, completion: (() -> Void)? = nil) {
        if state != layoutAdapter.topMostState {
            lockScrollView()
            defer { unlockScrollView() }
        }
```

As a framework consumer, this can be worked around by restoring scroll view behavior in a specified `completion` parameter:

```swift
floatingPanelController.move(to: .full, animated: true)
   floatingPanelController.scrollView.bounces = true
}
```

### Environment

**Library version**

1.5.0

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

12.0

**Xcode version**

10.2.1 (10E1001)

**Comment by SCENEE** [comment]
Thank you, @mattt. I'm very pleased because I respect you for your great works. I detected the issue as you mentioned and then fixed it at 194a197e8339684f3f9a7300a8442727f6cf5b0e in #201:relieved:

**Comment by SCENEE** [comment]
I reopen this issue because #201 doesn't fix it.

**Comment by mattt** [comment]
Thanks for the fix, @SCENEE. Much appreciated!
