### ISSUE TITLE
Problem with ambiguous height on rotation

### ISSUE THREAD

**Issue by andreaslindahl** [SCENEE/FloatingPanel#199]
I'm having some weird layout issues on iPad when the device rotates. I'm displaying a viewcontroller in a floating panel. The viewcontroller doesn't use a tableview or scrollview, but displays a number of "regular" views, with static heights.

On iPad, when the device rotates, the height if the surface view for some reason becomes 0 and I can no longer interact with the views and controls in my floating panel viewcontroller.

This also messes up the layout in my floating panel.

When I debug the view hierarchy, the height of the FloatingPanelSurfaceView is indicated as being "ambiguous".

For some reason, this error only seem to occur if I launch the app when the simulator is in portrait mode and then rotates to landscape. If I launch the app while in landscape, the layout problem doesn't seem to appear.

**Comment by SCENEE** [comment]
I also figure out the same issue in the Samples app on iPhone. I'm planning to change the height management on v1.6.0. So I will try to fix this issue at the time.

**Comment by SCENEE** [comment]
I confirmed the ambiguous height error I found the Samples app already disappeared on v1.6.0 and v1.6.2. If you still have the same issue, please reopen this and let me know the version. Thanks 👍
