### ISSUE TITLE
Segues from floating panel

### ISSUE THREAD

**Issue by jaytrisw** [SCENEE/FloatingPanel#20]
I hesitate to add this here, as I'm sure I am just doing something wrong.

I am having some trouble with segues.  I would like to perform some segues from the floating panel.  Currently when I do this, it brings the new view controller in and it replaces the floating panel.  I'd like the segues to perform just as they would from a normal view controller.

I hope I described this adequately and I really appreciate any help on this.

**Comment by SCENEE** [comment]
Thank you for your report! You're right and this library has a problem on this case.
I'm trying to fix it now. Please wait for a little while longer.

**Comment by SCENEE** [comment]
@jaytrisw,

Could you try 'fix-show-segue-problem' branch referred by PR #21 ?

`FloatingPanelController.show(_:sender)` causes this issue. After I changed the implementation at 
0f60068 commit to keep the backward compatibility for v1.1.0, I think it's better to replace this method with `FloatingPanelController.set(contentViewController:)`. The migration is easy through 2-time fixes of build errors.

What do you think of the change?

Thank you for your cooperation.

**Comment by jaytrisw** [comment]
I am getting a crash when I try to load the floating panel.

I'm sure that I've just done something wrong.  Is the only code change that I need to make:

`fpc.set(contentViewController: searchVC)`

**Comment by jaytrisw** [comment]
Also, I tried adding another view controller to the map sample project and performing a segue using `performSegue(withIdentifier: "pushVC", sender: nil)` it still adds the new view controller in the floating panel.

**Comment by SCENEE** [comment]
Well, it should works only after you change your code like [here](https://github.com/SCENEE/FloatingPanel/pull/21/commits/b510baca21bf7a2be28433b32d318f0828bc6f46#diff-608d5618e897333e9606cb5a146951fdR30)

**Comment by jaytrisw** [comment]
I am sorry, I am very new to iOS development.   I'm just not understanding the sample project.

**Comment by jaytrisw** [comment]
I've implemented the new commit and it no longer crashes when loading the initial view controller.  However the segue performs just as it did while using v1.1 of the floating panel.

I am very sorry to keep bothering you, I just don't know what I am doing wrong.  Would it be possible to send you my project?  If not, I completely understand.  And I really do appreciate all the time you've already committed to this.

**Comment by SCENEE** [comment]
Good news! Of course, could you share a dropbox link of your project?

**Comment by jaytrisw** [comment]
Sent, thank you!
