### ISSUE TITLE
How to change Height of floating panel controller as per the content change of that content view controller?

### ISSUE THREAD

**Issue by jeky1990** [scenee/FloatingPanel#202]
How to change Height of floating panel controller as per the content change of that content view controller.
I am using it with fpc.updatelayout() but it is working only when my fpc position is .full.
if I change the position of that from .full to .half that and after when content change at that time fpc going to hidden.
![Screenshot 2019-05-08 at 5 03 53 PM](https://user-images.githubusercontent.com/42162475/57372462-5b846a00-71b3-11e9-926e-442afb760247.png)

     
![Screenshot 2019-05-08 at 5 02 06 PM](https://user-images.githubusercontent.com/42162475/57372354-09dbdf80-71b3-11e9-8ceb-603ba6883ec8.png)
}

**Comment by SCENEE** [comment]
The library doesn't take care of your use case so far, but I will try to consider it later when I update the height management.

**Comment by purepure** [comment]
I am on this issue too. Hope it will available soon. Thank

**Comment by SCENEE** [comment]
This issue might be fixed on #239.

**Comment by SCENEE** [comment]
Could you try v1.6.4 and later?

**Comment by scenee** [comment]
This lib has `FloatingPanelIntrinsicLayoutAnchor` and `FloatingPanelAdaptiveLayoutAnchor` since 2.x. Please use ether of them according to your use case.
