### ISSUE TITLE
Content offset

### ISSUE THREAD

**Issue by bardonadam** [SCENEE/FloatingPanel#217]
Is there a way to set custom content offset? I need a top margin for my navigation controller, so it doesn't look that crowded:

![image](https://user-images.githubusercontent.com/6375640/58805356-31886100-8614-11e9-89b5-7ffd6e4655f8.png)

**Comment by SCENEE** [comment]
Good timing! `FloatingPanelSurfaceView.contentInset` has been added in v1.6.0! https://github.com/SCENEE/FloatingPanel/releases/tag/v1.6.0
