### ISSUE TITLE
Tableview's didSelectRowAt method not getting called in v1.6.0

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [scenee/FloatingPanel#222]
### Short description
I have a `UITableViewController` embedded in the floating panel. When I single tap on any cell, the `didSelectRowAt` method gets fired. But since the latest version, this behavior has become erratic. I have to double tap on cells for the `didSelectRowAt` method to fire.

### Expected behavior
`didSelectRowAt` method to fire on single tap. This worked fine in v1.4.0.

### Steps to reproduce
- Have the floating panel initial position has half.
- Swipe up to full position and tap on a cell. `didSelectRowAt` does not fire.
- Tap on that cell again. Now the `didSelectRowAt` fires.

Another behavior I noticed.

- Have the floating panel initial position has half.
- Swipe up on the floating panel but before it reaches full position, let go so it slides back down.
- Now swipe it up fully again.
- Tap on a cell and the `didSelectRowAt` fires.

### Environment

**Library version**
1.6.0

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12.2

**Xcode version**
10.2.1

**Comment by SCENEE** [comment]
Could you please check the repro when you comment out the [line](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L45) and then rebuild the library after cleaning derived data?

**Comment by Isuru-Nanayakkara** [comment]
Is it okay to edit the source files even if I add the library to my project via CocoaPods?

**Comment by SCENEE** [comment]
Yes, it is!

**Comment by Isuru-Nanayakkara** [comment]
Tried it. Cleaned the DerviedData folder manually too. But the issue persists.

**Comment by SCENEE** [comment]
Thanks, it looks same as https://github.com/SCENEE/FloatingPanel/issues/164.
As [the comment](https://github.com/SCENEE/FloatingPanel/issues/164#issuecomment-484772607) mentioned, it seems to be an issue of UITableView. I tried to fix it in a couple of days but it's hard to fix it completely..

**Comment by Isuru-Nanayakkara** [comment]
Oh, that sucks. I guess I'll revert back to v1.4.0 for now. Everything works fine in that version.

**Comment by SCENEE** [comment]
Oh, I missed it. There is not same issue as #164 because it's reported on v1.4.0. I need to investigate this more.

**Comment by HappyIosDeveloper** [comment]
I still have this issue.
