### ISSUE TITLE
Notify delegate when Panel is being dismiss via a tap on backdrop view

### ISSUE THREAD

**Issue by xinatanil** [SCENEE/FloatingPanel#227]
We already have two convenient delegate methods which notify us when panel is being dismissed via interactive removal.
```
    func floatingPanelDidEndDraggingToRemove(_ vc: FloatingPanelController, withVelocity velocity: CGPoint)
    func floatingPanelDidEndRemove(_ vc: FloatingPanelController)
```

But it's also very much needed to notify delegates when panels are being removed via a tap on the backdrop view (especially when panels are presented modally).
Something like
```
 func floatingPanelWillBeDismissedByBackdropViewTap(_ vc: FloatingPanelController)
 func floatingPanelWasDismissedByBackdropViewTap(_ vc: FloatingPanelController)
```

Thanks!

**Comment by SCENEE** [comment]
In #205, the tap gesture to dismiss a panel is planning to be open.

**Comment by SCENEE** [comment]
You will be able to use `FloatingPanelBackdropView.dismissalTapGestureRecognizer` on v1.7.0 and later. And then you can detect the tap event using `fpc.backdropView.dismissalTapGestureRecognizer.addTarget(_:action:)`.
