### ISSUE TITLE
Support for Swift 5.1 via Carthage needed

### ISSUE THREAD

**Issue by fahlout** [SCENEE/FloatingPanel#233]

**Comment by SCENEE** [comment]
How about SwiftPM with Xcode 11?

**Comment by fahlout** [comment]
Unfortunately, I have to support internal libraries with dependencies that do not support SwiftPM yet and may not support it if the owner decides to only support Carthage or CocoaPods. I’d certainly love to eventually be able to just use SwiftPM for all my dependencies, but realistically that isn’t possible just yet.

In addition to that I do believe that open source libraries should, at least for now, still give the choice between SwiftPM, Carthage, and CocoaPods.

**Comment by SCENEE** [comment]
Alright. I understand your background.
At first, the library can be compiled by Xcode 11 beta(Swift 5.1 compiler) and supports SwiftPM, Carthage and CocoaPods.
But the xcodeproj specifies the default version as Swift 4.x(depends on Xcode version). So if you would like to specify Swift 5.1 when you build it by Carthage, you can do below.
```
$ echo "SWIFT_VERSION = 5.1" > temp.xccconfig
$ XCODE_XCCONFIG_FILE=./temp.xcconfig carthage build FloatinPanel
``

**Comment by fahlout** [comment]
Thank you so much for your help. I will try that out on Monday.
