### ISSUE TITLE
uisearchbar in navigationbar cant touch

### ISSUE THREAD

**Issue by LeaguePlayer** [SCENEE/FloatingPanel#237]
### Short description
i added UISearchBar in contentViewController.view like subview (for testing)
but it doesnt work, i cant tap on searchBar http://joxi.ru/52ay59zfEq0yb2
it should be fixed at top float controller

i think its conflict between pan gestures and searchbar

how can i solve it ?

**Library version**
1.6.0

**Installation method**

- [+ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**Comment by SCENEE** [comment]
[Examples/Maps](https://github.com/SCENEE/FloatingPanel/tree/master/Examples/Maps) don't have this issue. What is the difference between the example and your app?

**Comment by LeaguePlayer** [comment]
difference in navigation controller i use it for show other controllers inside float panel. Top space disable as full

**Comment by SCENEE** [comment]
I tried the below `NavigationController` as a content view controller, but the search bar is working well 🤔
```swift
class NavigationController: UINavigationController {}

class NavigationContentViewController: UIViewController, UISearchBarDelegate {
    var searchBar: UISearchBar!
    override func viewDidLoad() {
        super.viewDidLoad()
        setupSearchBar()
    }
    func setupSearchBar() {
        if let navigationBarFrame = navigationController?.navigationBar.bounds {
            let searchBar: UISearchBar = UISearchBar(frame: navigationBarFrame)
            searchBar.delegate = self
            searchBar.placeholder = "Search"
            searchBar.tintColor = UIColor.gray
            searchBar.keyboardType = UIKeyboardType.default
            navigationItem.titleView = searchBar
            navigationItem.titleView?.frame = searchBar.frame
            self.searchBar = searchBar
        }
    }
    func searchBarShouldBeginEditing(_ searchBar: UISearchBar) -> Bool {
        searchBar.showsCancelButton = true
        return true
    }
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        searchBar.showsCancelButton = false
        searchBar.resignFirstResponder()
    }
}
```
Could you please check [the line](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L195) whether `surfaceFrame.minY == layoutAdapter.positionY(for: state)`  is true?

**Comment by salvimayur89** [comment]
Facing same issue. Can you help me??

**Comment by SCENEE** [comment]
@salvimayur89 
Of course. But on this issue I'm in trouble because I can reproduce it. Could you please tell me some differences from [the above code](https://github.com/SCENEE/FloatingPanel/issues/237#issuecomment-510840232) or Maps.app sample?
