### ISSUE TITLE
when searchpanel full, tableview reset, by dragging down the grabber

### ISSUE THREAD

**Issue by bienciel** [SCENEE/FloatingPanel#242]
### Short description
when SearchPanelView is expanded fully
table view can be scrolling
at that moment
if i close the searchpanel by dragging grabber
tableview was reset

### Expected behavior
table view should be locked

### Actual behavior
table view reset

### Steps to reproduce
searchpanel : expanded
tableview : scroll some
grabber drag down
table view reset

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

**Xcode version**

**Comment by SCENEE** [comment]
Let me ask 3 questions.
* Do you reproduce this issue on Examples/Maps? 
* Could you send me a screen record?

A last, I tried to fix an issue which I found by dragging down in the grabber. 
* Could you try `fix-scroll-lock-in-grabbar` branch?
