### ISSUE TITLE
Swipe with button 

### ISSUE THREAD

**Issue by pnaqash** [SCENEE/FloatingPanel#245]
It is possible to swipe view with button when press button already open panel go to up and when press again panel swipe to half

**Comment by ajRiverav** [comment]
I did something similar by doing the following: 

1) in the content's view controller, create your IBAction as you would normally do. 
2) in the same view controller, create a protocol (you can call it ContentViewControllerDelegate) and add a function called buttonTapped(), or whatever name you'd like. 
3) in the IBAction func, call the buttonTapped() func. 
4) Now, in the view controller that instantiates the FloatingPanelController, implement the protocol (that is, implement ContentViewControllerDelegate's buttonTapped()). 
5) Use the position var to determine the panel's position and use the move func to move it.

**Comment by StackHelp** [comment]
@ajRiverav Do you have some code to elaborate?
