### ISSUE TITLE
Change constraints depending on panel's position

### ISSUE THREAD

**Issue by ajRiverav** [SCENEE/FloatingPanel#246]
### Short description
I would like to change the surface view constraints depending on its position. This is to have a wider panel when it is in its FULL position, and a narrower panel when it is at the HALF position. 

I see that there is only one place to change the constraints (in `prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint]`). 

Is this possible with the current code? Or would it need to be implemented another parameter to that func so that one can return the constraints depending on the panel's position?
### Steps to reproduce

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [x] Carthage
- [ ] Git submodules

**iOS version(s)**
11.0
**Xcode version**

**Comment by SCENEE** [comment]
You can change the constraints for each position.  Here is the sample code 😄 
https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Sources/ViewController.swift#L1039
https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Sources/ViewController.swift#L1115

**Comment by ajRiverav** [comment]
@SCENEE which example in Samples hits these lines?
I am running Samples in the simulator.

**Comment by SCENEE** [comment]
> @SCENEE which example in Samples hits these lines?
> I am running Samples in the simulator.

Could you try the following steps?
1. Launch Samples.app
2. Tap "Show Tab Bar"
3. Tap "Layout 3"
4. Swipe a pane down and up

**Comment by ajRiverav** [comment]
Saw it. 
Thank you!
