### ISSUE TITLE
Show content above safe area

### ISSUE THREAD

**Issue by StackHelp** [SCENEE/FloatingPanel#255]
### Short description
How to show content above a safe area? Check the image where content also shows in a safe area that displayed with a red box at the bottom of the image.

![Screenshot 2019-08-27 at 5 47 43 PM](https://user-images.githubusercontent.com/41230403/63770585-2717f380-c8f3-11e9-96b7-cf4cb1df8f04.png)

**Code example that reproduces the issue**
I am using the same constraints that are available in map demo

### Environment

**Library version**
1.6.4

**Installation method**
- [x] CocoaPods

**iOS version(s)**
11 and above

**Xcode version**
10.3

**Comment by SCENEE** [comment]
Ok. Let me know more in detail. Would you like to display the bottom content like a footer bar? That means the content with a red box always settle above the safe area.
If so, could you please try to use [`fitToBounds` content mode](https://github.com/SCENEE/FloatingPanel#scale-the-content-view-when-the-surface-position-changes)?

**Comment by StackHelp** [comment]
@SCENEE It gives me error `Value of type 'FloatingPanelController?' has no member 'contentMode'`

**Comment by SCENEE** [comment]
I guess you still use v1.6.4, or remain SDK caches.

**Comment by StackHelp** [comment]
I have updated library yesterday and I got 1.6.4 version from that. Is there anything I am missing here?

**Comment by SCENEE** [comment]
Could you please use the master branch? Because the feature, `fitToBounds` content mode, hasn't been not released yet.
```ruby
 pod 'FloatingPanel', :git => "https://github.com/SCENEE/FloatingPanel.git"
```
On the master branch, you can use it as below.
```swift
fpc.contentMode = .fitToBounds
```

**Comment by StackHelp** [comment]
ok let me try this

**Comment by StackHelp** [comment]
@SCENEE And one more thing, how to make it full screen from half on button click?

**Comment by SCENEE** [comment]
This looks related to height change of your content view in `fitToBounds` mode.

**Comment by StackHelp** [comment]
Is it? I think it's related to bottom constraint change `<NSLayoutConstraint:0x600003981770 UIView:0x7fb5745736d0.bottom == UILayoutGuide:0x6000023f31e0'UIViewSafeAreaLayoutGuide'.bottom (active)>`

**Comment by SCENEE** [comment]
I'm sorry it's just a guess. Actually I don't understand the condition and I'm not sure the fitToBounds mode is what you expects.

**Comment by StackHelp** [comment]
Is it? I think it's related to bottom constraint change `<NSLayoutConstraint:0x600003981770 UIView:0x7fb5745736d0.bottom == UILayoutGuide:0x6000023f31e0'UIViewSafeAreaLayoutGuide'.bottom (active)>`

**Comment by StackHelp** [comment]
`FitToBounds` works for sure. There is no doubt for me but with this case, it brings some constraint issue as well. Will check it anyway if I can solve it.

**Comment by SCENEE** [comment]
Thank you, @StackHelp. Could you make a sample app based on yours to repro it?(no problem to send it to me by email) If I have it, I can help you.

**Comment by StackHelp** [comment]
ok. Will try
