### ISSUE TITLE
Possible to swipe right to close panel?

### ISSUE THREAD

**Issue by flyinghawker** [SCENEE/FloatingPanel#260]
Right now, the panel supports vertical drag to show or hide itself which is already great.

But as I research in market that there is some great APP using floating panel to display subCommentList to users, and they support both horizontal and vertical swipe to hide it which is super convenient. 

Of course, these two are exclusive to each other.

**Comment by SCENEE** [comment]
It's possible to combine two pan gestures of horizontal swipe and vertical one(built-in for panel scroll) using the following APIs. A pan gesture of horizontal swipe can be added to the root view of FloatingPanelController.

* func floatingPanelShouldBeginDragging(_ vc: FloatingPanelController) -> Bool
* func floatingPanel(_ vc: FloatingPanelController, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool

Finally, I would like to know the great apps :)
