### ISSUE TITLE
How do I use derived FloatingPanelPosition insets / invalidate and recalculate the layout ?

### ISSUE THREAD

**Issue by horseshoe7** [SCENEE/FloatingPanel#261]
### Short description

My panel insets will be different depending on iOS device (screen) size, and so far I can only get this to work if I set up some trial-and-error and determine some constants by hand then do a lookup at runtime, which device the user has, then use those pre-determined values.  This sort of works, but isn't 100% perfect because my content can be different for each user's scenario.

I would like to, for example, wait for a table view to finish loading / laying out, THEN tell the FloatingPanel to recalculate these insets in this method of my FloatingPanelLayout subclass.

`public func insetFor(position: FloatingPanelPosition) -> CGFloat?`

in a custom FloatingPanelLayout subclass.

### Expected behavior

I could just call "invalidateLayout" on the FPC.  It would re-calculate then animate the currentPosition to the new values.

Is there a way to accomplish something like this with the existing code?

### Environment

**Library version**

1.6.4

**Installation method**

- [ X] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
12

**Xcode version**
10.2

**Comment by SCENEE** [comment]
Yes, it's `FloatingPanelController.updateLayout()` although I think that naming as `invalidateLayout()` is better.

And I recognize the `public func insetFor(position: FloatingPanelPosition) -> CGFloat?` is not best for the purpose. Now I'm planning to release v2 so I welcome any proposal the enhancement!
