### ISSUE TITLE
Podspec for version 1.6.5 not listed in trunk

### ISSUE THREAD

**Issue by joshuafinch** [SCENEE/FloatingPanel#262]
Hi @SCENEE,

Looks like the Podspec for the tagged release `v1.6.5` has not been pushed to the cocoapods trunk.

Any chance you're able to push the updated podspec so that we're able to use it?

**Comment by SCENEE** [comment]
Oh, so sorry😱 I pushed it now 👍
 Thank you so much for your mention. I appreciate it.
