### ISSUE TITLE
Disable scrolling on everything except the surface view

### ISSUE THREAD

**Issue by DustinnBel** [SCENEE/FloatingPanel#267]
How to disable the scrolling gesture on the whole view except for the surface view?
I ask this because I have a few buttons in the few, touchup inside is not registered when moving the view a bit up or down. 

How can I lock the view to stay in place, or how can I get all touch events of the buttons in the view? The other solution is to disable scrolling in the view except for the upper part (surfaceview).

**Comment by SCENEE** [comment]
You can disable the pan gesture recognizer as below.
```
fpc.panGestureRecognizer.isEnable = false
```
And also you let it stay in place by returning false in the following delegate method 
```
    func floatingPanelShouldBeginDragging(_ vc: FloatingPanelController) -> Bool {
        return false
    }
```
