### ISSUE TITLE
Cocoapods version outdated

### ISSUE THREAD

**Issue by andreaslindahl** [SCENEE/FloatingPanel#269]
The version available on Cocoapods seems to be outdated, and does for not - for example - include `s.swift_versions      = ["4.0", "4.2", "5.0"]` in the podspec file. Can it be updated?

**Comment by SCENEE** [comment]
Thanks for your mention! I will take care of it soon.

**Comment by SCENEE** [comment]
Today I released and published v1.6.6 to CocoaPods CDN. There is no problem on the installation/update to me. How about you? (v1.7.0 supports `s.swift_versions = ["4.0", "4.2", "5.0"]` and I will release it soon.)

**Comment by SCENEE** [comment]
Now v1.7.0 includes `s.swift_versions = ["4.0", "4.2", "5.0"]`! Thank you.
