### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by Shrikant-iOS** [SCENEE/FloatingPanel#271]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Steps to reproduce

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

**Xcode version**

**Comment by SCENEE** [comment]
Please check #152
