### ISSUE TITLE
Swipe to dismiss randomly removing its parent controller

### ISSUE THREAD

**Issue by paulsUsername** [SCENEE/FloatingPanel#274]
Every now and then (very intermittently) when swiping to dismiss the Floating panel, it dismisses its parent view controller as well.

Has anyone else experienced this? I was hoping it would just go away itself, but it still exists and users are complaining.

**Comment by SCENEE** [comment]
Is the parent view controller also an instance of `FloatingPanelController`?

**Comment by paulsUsername** [comment]
No, it's a FloatingPanelControllerDelegate, but not a floating panel controller. Inside my floating Panel, I have one content ViewController that is a tableView. 

What's most annoying is it seems to happen most often on the first time the user uses the app. I have searched high and low on my side for a cause, but I can't see anything.

Is there anything in a Floating Panel Controller that could cause this?

Thanks
Paul

**Comment by SCENEE** [comment]
If FloatingPanelController is related to this issue, [FloatingPanelController.fp_dismiss](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelController.swift#L602) can cause this.

**Comment by paulsUsername** [comment]
Is that to say that, if this is called it might cause it:

        self.fp_original_dismiss(animated: flag, completion: completion)

**Comment by SCENEE** [comment]
Yes, it is.

**Comment by paulsUsername** [comment]
Is there any solution that you can recommend. Removing that method causes serious issues beyond Floating Panel. Could it be a timing issue that sometimes when swiping to remove perhaps the Floating Panel is fully off the screen before dismiss is called and therefore it ends up being called on the parent VC. That's a complete guess but otherwise, it works great and it would be brilliant to get it resolved.

**Comment by SCENEE** [comment]
I'm sorry I didn't explain it enough. `self.fp_original_dismiss` must not be removed from there.  I'd like to say its method call just indirectly causes this issue so debugging the call helps to investigate it.

At first, I recommend you to detect who dismisses its parent controller. For example, you can override `dismiss(animated flag: Bool, completion: (() -> Void)? = nil)` of the parent controller and add a breakpoint to detect someone.

By the way, if this issue happens on iOS 13, I know the related issue like [here](https://stackoverflow.com/questions/56903030/ios-13-uiactivityviewcontroller-automatically-present-previous-vc-after-image-sa) so it can be iOS 13 issue.

**Comment by paulsUsername** [comment]
I can tell you this issue is very much alive. I have tried everything from above. We may just need to replace the SDK. It was otherwise great but this bug is prooving frustrating for users.

**Comment by SCENEE** [comment]
Alright. Actually I'm not sure the library causes this issue and the above comments are not a solution for you, but hint for debugging. As my previous comment, I would like you to investigate what dismisses the parent controller actually.
```
override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil) {
    print(self.presentedViewController) // <--- Is `self.presentedViewController` a `FloatingPanelController` instance?
    super.dismiss(animated: flag, completion: completion)
}
```

**Comment by SCENEE** [comment]
Hi, @paulsUsername. This issue might be related to #289. I will release v1.7.1 including the fix before long. So I would be glad if you could try the version.

**Comment by FlashTang** [comment]
Hi @SCENEE  @paulsUsername 
Same issue here , it removes it's parent view every time when you swipe to hide ,  not "very much alive" but "every time" 
version 1.7.4  ios 11 and ios 13 real device 
but it's ok  if you use fpc.hide()
P.S. I use fpc.addPanel(toParent: self) and fpc.show() , not present 
And I use DocumentBrowserViewController , fpc's parent's parent's parent is DBVC

**Comment by SCENEE** [comment]
@FlashTang Do you call both of fpc.addPanel(toParent: self) and fpc.show()?

**Comment by FlashTang** [comment]
@SCENEE  
Hi SCENEE, whether call both or not call both , it removes
Now I know if the parent ViewController was added (use addChild and addSubView) then the parent will not be removed
but if the parent ViewController was presented (use UIViewController.present) , then the parent ViewController will be removed by swipe dismiss (this affects parent's parent.... untill non-presented ViewController) 
Here I created an example xcode project 
https://drive.google.com/file/d/1pFuw-plkBV3MbNyXD1Xer8yAUJHTyvpe/view

**Comment by SCENEE** [comment]
Hi @FlashTang. Thanks to your example. It's much helpful for me. I created #358 to fix your reported issues. It would be helpful if you could check it as well.

**Comment by FlashTang** [comment]
@SCENEE 
Thank you very much SCENEE ,  issue fixed 👍 , and maybe you should add a close button to the sample to make people happy :)
           ```
 let mvc = UIViewController()
      //======
     let closeButton = CloseButton()
     mvc.view.addSubview(closeButton)
     closeButton.translatesAutoresizingMaskIntoConstraints = false
     NSLayoutConstraint.activate([
         closeButton.rightAnchor.constraint(equalTo: mvc.view.rightAnchor, constant: -50),
         closeButton.topAnchor.constraint(equalTo: mvc.view.topAnchor, constant: 50),
         closeButton.widthAnchor.constraint(equalToConstant: 44),
         closeButton.heightAnchor.constraint(equalToConstant: 44)
     ])
     closeButton.addTarget(self, action: #selector(dismissPresentedVC), for: .touchUpInside)
```
