### ISSUE TITLE
Interaction with underneath view in when the floating panel is in full position

### ISSUE THREAD

**Issue by WaqarKhalid** [SCENEE/FloatingPanel#277]
### Steps to reproduce

**Code example that reproduces the issue**
This is my layout for panel 
class RemovablePanelLayout: FloatingPanelIntrinsicLayout {
    var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .half]
    }
    var initialPosition: FloatingPanelPosition {
        return .half
    }

    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .half: return 100.0
        default: return nil
        }
    }
   
}

And this is my code of adding the panel on controller

 func addMainPanel(with contentVC: UIViewController) {
        mainPanelObserves.removeAll()
        
        let oldMainPanelVC = mainPanelVC
        
      
        mainPanelVC = FloatingPanelController()
        mainPanelVC.delegate = self
        
    
        
        mainPanelVC.surfaceView.shadowHidden = true
        
        // Set a content view controller
        mainPanelVC.track(scrollView: contentVC.menuCollectionView)

        mainPanelVC.set(contentViewController: contentVC)
        mainPanelVC.contentMode = .static
        
        mainPanelVC.backdropView.backgroundColor = UIColor.clear
        mainPanelVC.surfaceView.backgroundColor = UIColor.clear
      

        let surfaceTapGesture = UITapGestureRecognizer(target: self, action: #selector(handleSurface(tapGesture:)))
        surfaceTapGesture.cancelsTouchesInView = false
        surfaceTapGesture.numberOfTapsRequired = 1
        contentVC.headerView.addGestureRecognizer(surfaceTapGesture)
        
        if let oldMainPanelVC = oldMainPanelVC {
            oldMainPanelVC.removePanelFromParent(animated: true, completion: {
                self.mainPanelVC.addPanel(toParent: self, belowView: nil, animated: true)
            })
        } else {
            mainPanelVC.addPanel(toParent: self, belowView: nil, animated: true)
        }
    }
### Environment

**Library version**
Latest 
**Installation method**

- [ ] CocoaPods

**iOS version(s)**
iOS 12.3
**Xcode version**
11.1

**Comment by SCENEE** [comment]
When the interaction is disabled in full position of the panel, does this line's code return `false`?
https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L206
```swift
    return surfaceFrame.minY == layoutAdapter.positionY(for: state)
```

**Comment by SCENEE** [comment]
Does this issue still happen on v1.7.1?

**Comment by federiconicoli** [comment]
Hey! Thank you for the great work!
I think this issue is still happening on v1.7.4
I have the following:

```
private func setupFloatingPanel() {
    floatingPanelController = FloatingPanelController(delegate: self)
    let jobInfoVC = storyboard?.instantiateViewController(withIdentifier: "JobInfoVC") as! JobInfoVC
    floatingPanelController.set(contentViewController: jobInfoVC)
    floatingPanelController.track(scrollView: jobInfoVC.tableView)
    floatingPanelController.addPanel(toParent: self)
    floatingPanelController.surfaceView.cornerRadius = 6.0
}
```

```
class JobInfoFloatingPanelPadLayout: FloatingPanelLayout {
    
    public var initialPosition: FloatingPanelPosition {
        return .tip
    }

    public var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .tip]
    }

    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 100
        case .tip: return 210
        default: return nil
        }
    }

    public func prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint] {
       return [
        surfaceView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 8.0),
        surfaceView.widthAnchor.constraint(equalToConstant: 400),
       ]
    }
}
```
When the panel is in full position I'm not able to interact with the underneath view.

iOS 13.1.2
Xcode 11.3

**Comment by SCENEE** [comment]
Thank you for your report! I will check it later.

**Comment by SCENEE** [comment]
@federiconicoli 
Does your issue means the underneath view which is covered by the backdrop view semi-transparent(black alpha 0.3) is not able to interact with user gestures?

**Comment by federiconicoli** [comment]
Oh I see! The other way would be implementing 
```func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat``` returning 0.0
Thank you very much!
