### ISSUE TITLE
How to change FloatingPanelController.backdropView opacity and add gradient to it?

### ISSUE THREAD

**Issue by v57** [SCENEE/FloatingPanel#279]
I need to draw backdropView in opened state as gradient with 0.9 alpha. But i cannot override this property to add my custom view to it. Also when i add my gradient view as subview (with autolayout) it doesn't appears

**Comment by SCENEE** [comment]
Autoresizing mask for a subview of the backdrop view is not working. Please set up Auto Layout constraints.  For example, 
```
        mainPanelVC.backdropView.addSubview(gradView)
        gradView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            gradView.topAnchor.constraint(equalTo: mainPanelVC.backdropView.topAnchor),
            gradView.leftAnchor.constraint(equalTo: mainPanelVC.backdropView.leftAnchor),
            gradView.bottomAnchor.constraint(equalTo: mainPanelVC.backdropView.bottomAnchor),
            gradView.rightAnchor.constraint(equalTo: mainPanelVC.backdropView.rightAnchor),
        ])
```
![Simulator Screen Shot - iPhone X - 2019-10-24 at 19 00 38](https://user-images.githubusercontent.com/899487/67475372-0967d000-f691-11e9-83ca-4ea525145ca5.png)
