### ISSUE TITLE
Floating panel height doesn’t update when large title navigation bar shrinks to normal size from scrolling 

### ISSUE THREAD

**Issue by Kohdepitcher** [SCENEE/FloatingPanel#28]
When trying out the floating panel, the panel’s height is correct and the bottom safe area sticks to the screen correctly as seen in this screen shot...
![d74a2ede-3769-493f-b074-8f3e5fbf9b8f](https://user-images.githubusercontent.com/15321325/47888139-74236880-de8e-11e8-8ac4-92f8a432e1f0.png)

But when the large title navigation bar shrinks to the normal size due to scrolling the collection view on my home VC, pulling up the floating panel quickly causes the bottom safe area constraint to be above the bottom of the screen as seen in this screen shot... notice the large grey bar underneath the pink button, that shouldn’t be there
![a09c7dec-1957-4a11-ae2f-e5eed206c32b](https://user-images.githubusercontent.com/15321325/47888211-cebcc480-de8e-11e8-9282-30cf82f560b2.png)

But when panning the floating panel, it snaps back down so that the bottom of my stack view touches the bottom safe area of the home vc as the stack view in the floating panel has a constraint to the bottom safe area of the floating panel. This snapping also causes the floating panel to ignore my 18 point gap inset between the top of the panel and the nav bar which is set in the panel’s custom layout
![48c55dce-98f0-489c-b201-1418299d0a18](https://user-images.githubusercontent.com/15321325/47888285-47bc1c00-de8f-11e8-9559-e87ab0b38183.png)

**Comment by Kohdepitcher** [comment]
Only just changed my Podfile to the fix-navigation-bar-problem branch and had some weird bad access codes when trying to use a floating panel object but that was fixed by just de-integrating and reinstalling my pods. I can confirm that your solution has fixed this issue of the floating panel being affected by the changing height of the navigation bar. Cheers mate. Just need to try your other fix for the translucency affecting the positioning. Definitely some awesome work by you.

**Comment by SCENEE** [comment]
Thank you for your confirmation! Could you try my other fix for #26 ?
