### ISSUE TITLE
didSelectItemAt not called for UICollectionView inside FloatingPanel

### ISSUE THREAD

**Issue by eospi** [SCENEE/FloatingPanel#282]
### Short description
This issue seems similar to #222, but for collection views. 
My content view controller has a `UICollectionView`, which should call the `didSelectItemAt` delegate method when an item is tapped, but it is not called. I have verified that the content view controller works as expected when it is not inside a floating panel.
### Steps to reproduce

**Code example that reproduces the issue**
```swift
fileprivate func setupPickerPanel() {
        floatingPanel = FloatingPanelController()
        floatingPanel.delegate = self
        floatingPanel.surfaceView.cornerRadius = 20
        floatingPanel.surfaceView.shadowHidden = false
        
        contentVC = ContentViewController()
        floatingPanel.set(contentViewController: contentVC)
        floatingPanel.track(scrollView: contentVC.collectionView)
}
```
### Environment

**Library version**
1.7.0
**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules
- [x] Swift Packages

**iOS version(s)**
13.1.2
**Xcode version**
11.1

**Comment by thatnaoki** [comment]
For my `UICollectionView`, `didSelectItemAt` gets called,  but `performSegue` inside a floating panel does not work...

### Environment
**Library version**
1.7.0
**Installation method**
- [x] CocoaPods

**iOS version(s)**
13.2
**Xcode version**
11.2.1

**Comment by thatnaoki** [comment]
For my `UICollectionView`, `didSelectItemAt` gets called, but `performSegue` does not get called inside a floating panel.

Environment
**Library version**
1.7.0
**Installation method**
CocoaPods
**iOS version(s)**
13.2
**Xcode version**
11.2.1

**Comment by SCENEE** [comment]
Isn't didSelectItemAt always called on any panel states in your case? Or only after dragging a panel? This is because #222 is that didSelectItemAt sometimes isn't called after dragging a panel.

**Comment by SCENEE** [comment]
I hope [this improvement](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelCore.swift#L208) on 1.7.1 would have an effect on this issue.

**Comment by eospi** [comment]
Thank you so much for looking into this! Unfortunately, the fix doesn't seem to work. didSelectItemAt is never called regardless of panel state.

**Comment by SCENEE** [comment]
@eospi 
Hmm it's weird. I try to repo this by a content view controller including UICollectionView, but `didSelectItemAt` is called propely. Moreover, I know an app using FloatingPanel which contains a collection view and it also works well.

**Comment by eospi** [comment]
It looks like a tap gesture recognizer on my main view controller was interfering with the floating panel. When I remove that recognizer, it works! Is there a way to use a floating panel with other gestures on the main view?

**Comment by SCENEE** [comment]
Hi, it's not the lib's issue(I could repro this by adding a tap gesture). The problem is resolved using `UIGestureRecognizerDelegate` as below.
```swift
    func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer is UITapGestureRecognizer {
            let loc = gestureRecognizer.location(in: floatingPanel.view)
            return floatingPanel.surfaceView.frame.contains(loc) == false
        }
        return true
    }
```

**Comment by eospi** [comment]
That fixes it. Thanks so much for your help and the library!
