### ISSUE TITLE
How to Track Y position of floading panel view 

### ISSUE THREAD

**Issue by forTJ555** [SCENEE/FloatingPanel#283]
i want to add button on top of floating view that floats with the view

**Comment by zntfdr** [comment]
Hi @forTJ555,

I do something similar in my apps, basically what I do is attach the view (in your case the button) to the top of the floating panel view.

Here's how:

```swift
    let panelController: FloatingPanelController = ....
    let buttonView: UIView = ...

    panelController.view.addSubview(buttonView)
    buttonView.translatesAutoresizingMaskIntoConstraints = false

    let constraints: [NSLayoutConstraint] = [
      buttonView.bottomAnchor.constraint(equalTo: panelController.surfaceView.topAnchor,
                                         constant: 0),
      buttonView.rightAnchor.constraint(equalTo: panelController.surfaceView.rightAnchor,
                                         constant: 0),
      buttonView.leftAnchor.constraint(equalTo: panelController.surfaceView.leftAnchor,
                                         constant: 0)
    ]

    NSLayoutConstraint.activate(constraints)
```

Feel free to change the constant values to add padding, or change/replace the left/right anchors with something more suitable to your needs :)

Cheers!
Federico

**Comment by tomislav** [comment]
`floatingViewController.surfaceView.frame.origin.y`

**Comment by paulnicolet** [comment]
Hi guys, 

I'm trying to achieve something similar and it's working fine. 
However there is one small issue: when dragging the floating panel, the button follows it properly. But when releasing the panel, the button will not move in an animated manner (like the panel does), and will immediately go to its next position.

@zntfdr Did you achieve to animate the `buttonView` position change as well ? 

Thanks!

**Comment by zntfdr** [comment]
Hi @paulnicolet,
I manage to get the following by using the code mentioned above:
![RPReplay_Final1573269035 2019-11-09 10_16_20](https://user-images.githubusercontent.com/5277837/68522087-03513080-02da-11ea-99cf-88e8e36b2833.gif)

I don't do any changes beside adding the constraints as mentioned 😃

**Comment by forTJ555** [comment]
@zntfdr thanks for your help man :)
