### ISSUE TITLE
Tapping outside of panel to dismiss panel. 

### ISSUE THREAD

**Issue by abudobby** [SCENEE/FloatingPanel#284]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Short description
How do you dismiss the panel by tapping outside of the panel. Is this a default behavior or do I have to manually add gestures to do this? 
### Steps to reproduce

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**

**Xcode version**

**Comment by SCENEE** [comment]
You can use `FloatingPanelBackdropView.dismissalTapGestureRecognizer`.
https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelBackdropView.swift#L10` 
By default, the gesture recognizer is disabled for backward compatibility so you need to enable it.
```swift
fpc.backdropView.dismissalTapGestureRecognizer.isEnabled = true
```
