### ISSUE TITLE
Button in content view controller doesn't call target

### ISSUE THREAD

**Issue by rohdester** [SCENEE/FloatingPanel#286]
### Short description
I have a content view controller designed in a Storyboard. The view controller has two buttons which are connected to proper action methods. 

This content view controller is added set as the content view controller of the FloatingPanelController.

When tapping the buttons, the target methods isn't called.

The buttons are in the bottom of the floating view, and when debugging int he View debugger it is as if they are part of the surface view and not the content view. If I change my layout so button are at the top it works as expected.

### Expected behavior

That the action method are called upon tapping button.

### Actual behavior

Nothing happens, as if the taps never reaches the button

### Steps to reproduce
I use this when settings up the FloatingPanelController

```
       fpc = FloatingPanelController()
        fpc.delegate = self
                
        let infoVC = DetailsInfoViewController.instantiateFromAppStoryboard(.voucherArchive)
        infoVC.configure(infoModel: infoModel)
        fpc.set(contentViewController: infoVC)
        
        fpc.addPanel(toParent: self)
```

My layout class has this function:

 ```
public var initialPosition: FloatingPanelPosition {
        return .tip
    }

 var supportedPositions: Set<FloatingPanelPosition> {
        return Set(arrayLiteral: FloatingPanelPosition.tip, FloatingPanelPosition.half)
    }

 func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .half:
            return 200
        case .tip:
            return 30
        default:
            return nil
        }
    }

```

### Environment

**Library version**

Latest

**Installation method**

- [ ] CocoaPods
- [x] Carthage
- [ ] Git submodules

**iOS version(s)**

13.2.2

**Xcode version**

11.2.1

**Comment by SCENEE** [comment]
Thanks @rohdester for your precise description!

> The buttons are in the bottom of the floating view, and when debugging int he View debugger it is as if they are part of the surface view and not the content view. 

I need to understand this behavior in detail. At first, The [Samples.app](https://github.com/SCENEE/FloatingPanel/tree/master/Examples/Samples) also use `DetailViewController` including buttons defined in Main.storyboard like below.. Their buttons has no issue on tap action.
<img width="160" alt="Screen Shot 2019-11-15 at 14 55 06" src="https://user-images.githubusercontent.com/899487/68920266-0e173400-07b8-11ea-98f9-17a408489789.png">

Could you let me know the difference between yours  and the above view controller?

**Comment by rohdester** [comment]
Thanks for the replay and assistance @SCENEE. Much appreciated.

My issue is that contrary to the sample, my buttons are at the bottom. Look at this:

<img width="852" alt="Skærmbillede 2019-11-15 kl  08 44 25" src="https://user-images.githubusercontent.com/8090882/68925852-60d6f880-0784-11ea-96ed-3258c8ed8f4b.png">

The two buttons at the bottom doesn't register the taps. The highlighted blue rectangle is the containing root view from the view controller. This view contains all the controls, but in the debugger you can see how none of them are in the blue highlighted area.

If I change the value for .half like so:

<img width="812" alt="Skærmbillede 2019-11-15 kl  08 25 35" src="https://user-images.githubusercontent.com/8090882/68925992-abf10b80-0784-11ea-8bf4-02b31f8e6b32.png">

Then notice how now all my controls are in the blue highlighted area. The only changed thing here is that instead of a value of 200 for .half it is now 400. And now the buttons work.

**Comment by rohdester** [comment]
This now is funny. This time the value for .half is 250. The buttons stille seem not to be out of the blue containing view, although should be? The buttons still don't work but if I tap outside the blue area (including the buttons), the taps goes to the PDF view below and the PDF zooms in and out.

<img width="671" alt="Skærmbillede 2019-11-15 kl  09 14 32" src="https://user-images.githubusercontent.com/8090882/68927724-b1e8eb80-0788-11ea-9e7a-ad2a89883f44.png">

**Comment by rohdester** [comment]
Hi,

Well I fixed it by adding this line:

`fpc.contentMode = .fitToBounds`

It seems this is necessary to handle this about the view's height.

I therefore close the issue. 

Thanks for the help tho' and for making this great project!

**Comment by SCENEE** [comment]
Thank you for your investigation, too! I'm glad to hear that. As you mentioned, the root view layout of your content view controller seems to be related to this issue. If you encounter a problem using `.fitToBbounds` mode, please feel free to let me know. Thank you.😄
