### ISSUE TITLE
didMove(toParent:) using wrong parameter in addPanel method

### ISSUE THREAD

**Issue by TadeasKriz** [SCENEE/FloatingPanel#289]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Short description

The method `addPanel` in `FloatingPanelController.swift` is calling `self.didMove(toParent: self)`. The `self` in both cases is an instance of the `FloatingPanelController`.

### Expected behavior

The value of `parent` should be passed in.

### Actual behavior

The value of `self` is passed in.

### Environment

**Library version**
1.7.0

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
13.2.1

**Xcode version**
11.1

**Comment by SCENEE** [comment]
Oh...It's my fault😞  I mistook it in 4ad7f11 commit.
Thank you very much, @TadeasKriz. I will fix it in #290.

**Comment by TadeasKriz** [comment]
@SCENEE No need to be ashamed! Things like this happen all the time. I wanted to send you a PR once you verified this is indeed an issue, but you were faster, so thank you very much!

Also, I'd like to let you know that in README.md, there's a bit of a confusion where you explain usage of the `hide` and `show`. It seems you use some of the code from the `addPanel` method. It can be a bit confusing for newcomers. Would you like me to send a PR with updated README?

Thank you again for such a quick fix and response. Don't ever feel ashamed for making a small mistake, and in OpenSource no less.

**Comment by SCENEE** [comment]
Thank you for the kind words. They were very encouraging 😄 

> Would you like me to send a PR with updated README?

Yes, of course! I'm looking forward to your PR 👍

**Comment by TadeasKriz** [comment]
@SCENEE https://github.com/SCENEE/FloatingPanel/pull/292 Please take a look and let me know.
