### ISSUE TITLE
Is it possible to add middle view? 

### ISSUE THREAD

**Issue by ramrcram** [SCENEE/FloatingPanel#295]
### Short description
Is it possible to add another view between `surfaceView` & `backdropView`. And then dragging up let middle view slightly appearing. 

### Expected behavior
Something like google map behavior. Once the user sliding up the details, the photos will appear from the middle, behind the top view.

Thanks in advance!.

Happy coding

**Comment by SCENEE** [comment]
I think it's possible if the middle view has constraints to `surfaceView`. The middle view appearance can be changed as a user interaction by handling the constraints with these delegate method.
* [func floatingPanelDidMove(_ vc: FloatingPanelController) ](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelController.swift#L22)
    * example: https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Sources/ViewController.swift#L1056
* [func floatingPanelDidChangePosition(_ vc: FloatingPanelController) ](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelController.swift#L17)
    * example: https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Sources/ViewController.swift#L1102
