### ISSUE TITLE
Prevent content view from moving to key positions

### ISSUE THREAD

**Issue by Nikolaiko** [SCENEE/FloatingPanel#297]
### Short description
I want Floating panel work as it is except returning to supported key positions after I stop dragging it.

### Expected behavior
When I drag panel up and down and then release it, it should stay at same position where I released it.

### Actual behavior
Panel is returning to the closest supported position (.tip, .full ...) after release

### Steps to reproduce
Usual code for using panel

**Installation method**
- [ ] CocoaPods

**iOS version(s)**
11.0

**Xcode version**
11.2

**Comment by SCENEE** [comment]
How about this API update to handle a target position?

```diff
-    func floatingPanelDidEndDragging(_ vc: FloatingPanelController, withVelocity velocity: CGPoint, targetPosition: FloatingPanelPosition)
+    func floatingPanelDidEndDragging(_ vc: FloatingPanelController, withVelocity velocity: CGPoint, targetPosition: inout FloatingPanelPosition)
```

It allows a panel to behave the expected one as below.

```swift
    func floatingPanelDidEndDragging(_ vc: FloatingPanelController, withVelocity velocity: CGPoint, targetPosition: inout FloatingPanelPosition) {
        if velocity.y == 0 {
            targetPosition = vc.position
        }
   }
```

**Comment by SCENEE** [comment]
The above new API will be supported in v2.0.

**Comment by SCENEE** [comment]
This API has been added in v2. Thank you for your request.
https://github.com/SCENEE/FloatingPanel/blob/master/Documentation/FloatingPanel%202.0%20Migration%20Guide.md#floatingpanelcontrollerdelegate
