### ISSUE TITLE
iOS 13 Card Style Presentation

### ISSUE THREAD

**Issue by chriskilpin** [SCENEE/FloatingPanel#298]
Floating panel does not behave correctly when added to a modal ViewController presented using the new card style presentation on iOS 13. (modalPresentationStyle = .automatic)

If you remove line 286 inside ViewController.swift inside the samples project this should now present the ViewController as a card. Run and hit show modal. The panel tracking when dragging up works but as soon as you drag down things go wrong.

iOS 13 Simulator iPhone 11
Xcode 11.2.1
Floating Panel 1.7.1

https://imgur.com/a/bLIcDdw

**Comment by SCENEE** [comment]
It's not good idea to use A floating panel in Sheet modal because a sheet modal should be used for nonimmersive modal content that doesn’t enable a complex task according to [HIG](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/).

A floating panel allows users to handle multi-tasks concurrently in a scene so that it can be used for a complex task.

**Comment by chriskilpin** [comment]
Hi there, apologies for only getting back to this now. Not sure if I agree with your interpretation of the HIG there. I am using the floating panel to display extra information at the bottom of a presented view. You can slide up to see the extra information in the panel and not interact with it. I wouldn't call this a complex task. The bottom line is that sheet modal is default presentation behavior moving forwards and currently Floating panel is broken with that presentation style. So anyone using this library on iOS 13 with presented ViewControllers will probably run into this bug.

**Comment by SCENEE** [comment]
Alright, I would like to think about this issue again so I reopen now.

**Comment by chriskilpin** [comment]
@SCENEE Thanks for looking into this, appreciate it.

**Comment by SCENEE** [comment]
I'm sorry to keep you waiting so long. I improve the panel behavior in a sheet modal in #358 although a bit limitation remain.
