### ISSUE TITLE
Any Object in ContentView Cann't tap

### ISSUE THREAD

**Issue by mrgaolei** [SCENEE/FloatingPanel#299]
### Short description
Any Object in ContentView Cann't tap

### Expected behavior
UIButton, Segment Control and so on 
Cann't response tap

### Steps to reproduce
When using this Layout

```swift

    func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
        return TNXPanelLayout()
    }


class TNXPanelLayout: FloatingPanelIntrinsicLayout {
    var supportedPositions: Set<FloatingPanelPosition> {
        return [.tip, .half]
    }
    var initialPosition: FloatingPanelPosition {
        return .half
    }
    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .tip: return 10
        case .half: return 514.0
        default: return nil  // Must return nil for .full
        }
    }
}
```

**Code example that reproduces the issue**

### Environment

**Library version**

**Installation method**

- [x] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
13.2
**Xcode version**
Version 11.2.1 (11B500)

**Comment by SCENEE** [comment]
It might be related to https://github.com/SCENEE/FloatingPanel/issues/282.

**Comment by SCENEE** [comment]
Does this issue happens on FloatingPanel 1.7.1?
