### ISSUE TITLE
Enhancement: Extending landscape panel to length of view

### ISSUE THREAD

**Issue by Yonodactyl** [SCENEE/FloatingPanel#3]
When I used the test application i noticed that the small view on the left side could use some stretching. Having it compact is nice but when you want to type to search, IMO, you arent looking at how aesthetically pleasing it is. Functionality would trump all else.

I would love to give a go at this feature.

**Comment by SCENEE** [comment]
I agree with your opinion. It’s reflected to master branch. Thanks.
