### ISSUE TITLE
Cannot close panel without scrolling to top

### ISSUE THREAD

**Issue by ffittschen** [SCENEE/FloatingPanel#30]
When I embed and track a scroll view in the floating panel, and the position is `.full`, it is not possible to close the panel without scrolling to the top of the scroll view.

I'd expect to be able to drag the panel using the grab handler regardless of the scrolling position, but this doesn't work.

I tried to investigate the behavior: to solve the issue I think it is necessary to somehow avoid calling [this code-path](https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanel.swift#L237-L245) when the pan was started at the grab handler, what do you think?

**Comment by SCENEE** [comment]
Thank you @ffittschen! I didn't notice the use case. It's common behavior of Apple Stocks, and Shortcuts app. I'm gonna fix it.

**Comment by SCENEE** [comment]
Could you try PR #32?

**Comment by ffittschen** [comment]
Thanks for the quick follow-up, but #32 did not fix the issue.. It still exits the method at [this statement](https://github.com/SCENEE/FloatingPanel/blob/922c0e53d2a406e387dbc16d5f2e90cf2e3d4c7b/Framework/Sources/FloatingPanel.swift#L252)

I created a quick video of the issue to clarify: https://imgur.com/T62XX3k

**Comment by SCENEE** [comment]
Thank you for your video. I understand your situation!

Briefly it is an expected behavior(but I'm sorry it might be confusing) because the scroll view's top fits to the surface's top and the floating panel has no 'grabber area`. So your touch gesture are handled by the scroll view. No 'grabber area` is enable you to arrange the whole area in the surface view.

If you prevent this behavior, you can add an appropriate margin between the scroll view's top and the surface's top. See a storyboard of "Scroll tracking(UITextView)" sample for detail.

But "Scroll tracking(UITableView)" might be confusing. So I will add a margin at the top like "Scroll tracking(UITextView)" sample.

**Comment by SCENEE** [comment]
Great work 🎉 I like it 😄 
Could you create your PR from your folk? 

Let me modify one point😌 I'd like you to reverse changes on scroll offset as below because scroll offset can get a wrong position. https://imgur.com/a/LMDZvDJ
```diff
diff --git a/Framework/Sources/FloatingPanel.swift b/Framework/Sources/FloatingPanel.swift
index 620eddd..d6a4d15 100644
--- a/Framework/Sources/FloatingPanel.swift
+++ b/Framework/Sources/FloatingPanel.swift
@@ -222,14 +222,11 @@ class FloatingPanel: NSObject, UIGestureRecognizerDelegate, UIScrollViewDelegate
         switch panGesture {
         case scrollView?.panGestureRecognizer:
             guard let scrollView = scrollView else { return }
-            if panGesture.state == .began {
-                initialScrollOffset = scrollView.contentOffset
-            }
             if surfaceView.frame.minY > layoutAdapter.topY {
                 switch state {
                 case .full:
                     // Prevent over scrolling from scroll top in moving the panel from full.
-                    scrollView.contentOffset.y = initialScrollOffset.y
+                    scrollView.contentOffset.y = scrollView.contentOffsetZero.y
                 case .half, .tip:
                     guard scrollView.isDecelerating == false else {
                         // Don't fix the scroll offset in animating the panel to half and tip.
@@ -358,6 +355,9 @@ class FloatingPanel: NSObject, UIGestureRecognizerDelegate, UIScrollViewDelegate
     private func startInteraction(with translation: CGPoint) {
         log.debug("startInteraction")
         initialFrame = surfaceView.frame
+        if let scrollView = scrollView {
+            initialScrollOffset = scrollView.contentOffset
+        }
         transOffsetY = translation.y
         viewcontroller.delegate?.floatingPanelWillBeginDragging(viewcontroller)
 ```

**Comment by ffittschen** [comment]
Sorry, those scroll offset changes fixed another bug I encountered, which I should have explained.

I'll create a new issue for it to not bloat this one 😊

**Comment by SCENEE** [comment]
Thanks! We'll continue to discuss #35 :)
