### ISSUE TITLE
Parent view controller 'cling' to child view controller while dragging

### ISSUE THREAD

**Issue by fedorpashin** [SCENEE/FloatingPanel#308]
I add a child view controller using [this](https://github.com/SCENEE/FloatingPanel#showhide-a-floating-panel-in-a-view-with-your-view-hierarchy) approach, but in most cases (not all the time) when I'm dragging the child view controller, a parent view controller moves too as if they were connected.

**Comment by SCENEE** [comment]
Hmmm, it looks an AutoLayout problem between the parent view controller and the child view controller(FloatingPanelController)'s views.

**Comment by fedorpashin** [comment]
What can I do to fix this problem? I've tried layoutIfNeeded() and many other methods related to Auto Layout but nothing works.

**Comment by SCENEE** [comment]
@fedorpashin I needs more information about issue. Is it easy to reproduce in the Samples.app?

**Comment by fedorpashin** [comment]
Yep, here it is: [Samples.zip](https://github.com/SCENEE/FloatingPanel/files/4164922/Samples.zip).

**Comment by fedorpashin** [comment]
The same problem with addPanel method.

**Comment by SCENEE** [comment]
Thank you, @fedorpashin. I will investigate it this weekend.

**Comment by SCENEE** [comment]
@fedorpashin I acknowledged this problem. It's an absolutely unexpected behavior. Thank you for your cooperation, again. I will try to fix it.

**Comment by SCENEE** [comment]
@fedorpashin Hi, I confirm this issue is fixed on `fix-2nd-panel-pan-gesture` branch! Could you try it?

**Comment by fedorpashin** [comment]
@SCENEE Hi, it seems to work well, thank you for resolving this problem! Now waiting for a new pod version :)

**Comment by SCENEE** [comment]
Glad to hear that 😄! So I closed this issue. And now I've released v.1.7.3! Please try it 👍
