### ISSUE TITLE
Present modally height

### ISSUE THREAD

**Issue by StackHelp** [SCENEE/FloatingPanel#309]
I am using `UITableViewController` as a content view for `FloatingPanel`. And opened `UITableViewController` modally. Normally it opens with some height according to constraints but here it just comes up with minor height. So, what to do to open controller modally with intended height.

**Code example that reproduces the issue**
```
    fileprivate func setupFloatingPanel() {
        let contentVC = ContentVC.instantiate()
        contentVC.loadViewIfNeeded()
        fpc = FloatingPanelController()
        fpc.set(contentViewController: contentVC)
        fpc.delegate = self

        fpc.surfaceView.shadowHidden = false
        fpc.isRemovalInteractionEnabled = true

        present(fpc, animated: true, completion: nil)
    }

   class ModalPanelLayout: FloatingPanelIntrinsicLayout {

    var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .half]
    }
    var initialPosition: FloatingPanelPosition {
        return .half
    }

    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .half: return 272
        default: return nil
        }
    }
    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        return 0.3
    }
}

```
Now with the above code, it gives some weird view above `UITableView`

![Simulator Screen Shot - iPhone 11 - 2020-01-28 at 14 36 11](https://user-images.githubusercontent.com/41230403/73250003-04f50b00-41dc-11ea-9aa6-4f227c44f205.png)

**Library version**
1.7.1

**Installation method**
 CocoaPods

**Comment by SCENEE** [comment]
Could you try to return a value for `.full` position  in `insetFinsetFor(position:)`?

**Comment by StackHelp** [comment]
@SCENEE you mean full and half both?

**Comment by SCENEE** [comment]
I'm sorry I was confused. The invalid panel layout is caused by  the table view which doesn't have an  intrinsic height So it should work if its table view returns a `intrinsicContentSize`.
```swift
class YourTableView: UITableView {
    override var intrinsicContentSize: CGSize {
        return CGSize(...)
    }
}
```

**Comment by StackHelp** [comment]
@SCENEE But this is `UITableViewController` and not a `ViewController`

**Comment by StackHelp** [comment]
@SCENEE Thank you :) It does work. Closing out the issue.

**Comment by StackHelp** [comment]
@SCENEE one more question, how to push a view controller from presented view controller like above?
