### ISSUE TITLE
Presenting Floating Panel

### ISSUE THREAD

**Issue by ziya2018** [SCENEE/FloatingPanel#313]
Hello, thanks for the great library. I have an issue, I want to present floating panel each time user presses button, I am using Present a floating panel as a modality approach, however on the second click of button I get "Application tried to present modally an active controller" error, dismissing floating panel spoils the default animation of closing floating panel. Can you please suggest me a solution?

**Comment by SCENEE** [comment]
The floating panel controller seems to be already used anywhere as the error said.
https://stackoverflow.com/questions/7429014/application-tried-to-present-modally-an-active-controller
