### ISSUE TITLE
Tap events get passed to the parent

### ISSUE THREAD

**Issue by Mattijah** [SCENEE/FloatingPanel#317]
Only a perfect, direct taps get recognised by UIButton. In case of a little movement, the tap event is passed to the parent and handled by the pan gesture.

**Can be tested in:** _Samples > Show Panel Modal_ (contains 3 buttons)

Steps:
- Tap and move the cursor/finger a little bit, then lift up (this tends to happen frequently in a real-world with fast taps done in a rush)
- Tap is ignored and "_Detail panel is tapped!_" message gets printed

Instead, any _touchUpInside_ that happens within the actual button should be registered. This makes more sense in cases where buttons are displayed in the content view, but the stay fixed at certain position and don't move with the panel (imagine something like a tabbar that comes up, but then stays fixed). How can the pan gesture in such cases be disabled? I couldn't find any relevant delegate methode, moreover `panGestureRecognizer.delegate` cannot be modified.

**Comment by SCENEE** [comment]
I will check this issue after releasing v1.7.3.

**Comment by SCENEE** [comment]
@Mattijah 
Sorry it took me so long to reply. The problem you pointed out is the one we face when dealing with a gesture recognizer and UIButton at the same time.
To solve this, we can use set `FloatingPanelController.panGestureRecognizer` up as follows.
```
fpc.panGestureRecognizer.cancelsTouchesInView = false
```
I think this will make it work the way you expect it to.

**Comment by Mattijah** [comment]
Thanks @SCENEE. This does seem to help. It is still not 100% and hovering with a finger over the button affects the underlying panel (it moves up/down - so that means it also accepts touches), but at least the _touchUpInside_ event now gets recognised.

**Comment by SCENEE** [comment]
@Mattijah 
Oh I see. Alright, I'm going to consider the solution again for hovering a button with a finger.

**Comment by make2a** [comment]
@SCENEE    pod 'FloatingPanel', '~> 2.0.0-beta.1' has same issue.

**Comment by SCENEE** [comment]
Thank you, @make2a. I will take a look at his issue on v2.

**Comment by SCENEE** [comment]
This issue seems to be resolved by stoping `UITapGestureRecognizer` with the panel pan gesture simultaneously by the following options.

v1: Returns false in "floatingPanel(_:shouldRecognizeSimultaneouslyWith:)" delegate method.
v2: Returns false in "gestureRecognizer(_:, shouldRecognizeSimultaneouslyWith:)" method of the delegate assigned to `fpc.panGestureRecognizer.delegateProxy`.

**Comment by macshodan** [comment]
Hi, first of all thanks for this great library.
I'm having a similar issue after updating to version 2.0.x. Basically I've implemented something similar the actual Maps app, where the user has a floating panel displaying a collection view with the details of each poi visible on the map. 
When the user taps a poi on the map the current floating panel automatically hides and a new one with only the content of the selected poi (or cluster) is shown instead. 
The two controllers that handle the floating panel are the same, only different instances with some parameters the add a button to dismiss the panel on the "second" one.

On both instances the collection view works normally, it scrolls and select items, but the uibutton to programmatically close the floating panel don't work unless I first drag the floating panel. I can see the button tapped but the associated action won't be called. I've tried to add the same button on the first instance, and it works flawlessly. One side note is that when I instantiate the first fpc I didn't set the panGestureRecognizer.delegateProxy, I've tried adding it for the second panel with no luck.

**Comment by SCENEE** [comment]
Hi, @macshodan. Does your problem still occure on v2.0.1? Because v2.0.1 has a bug fix on a button tap, https://github.com/SCENEE/FloatingPanel/pull/396.

**Comment by macshodan** [comment]
> Hi, @macshodan. Does your problem still occure on v2.0.1? Because v2.0.1 has a bug fix on a button tap, #396.

Hi @SCENEE, just tried and it's fixed. Thanks a lot for your support!

**Comment by gunnarsson** [comment]
The 2.0.1 fix solved a similar issue for me, moving the panel using move(to:animated:) made all buttons inside stop working until the panel was dragged. Thank you so much for the fix!
