### ISSUE TITLE
Issue in iOS 13.2

### ISSUE THREAD

**Issue by rakheendz** [scenee/FloatingPanel#318]
floatingPanelWillBeginDragging and floatingPanelDidEndDragging delegate method not getting called in iOS 13.2 (only in iPhones). Working fine in iPads. When tried debugging, 'startInteraction' method in FloatingPanelCore.swift doesn't get called in iPhones with version iOS 13.2. But gets fired in iPad with same version and also in iPhones with below OS 13

 Environment - iPhone 11 (OS 13.2.2)

Library version - 1.7.2

Installation method
- [ ] CocoaPods

iOS version(s) - 13.2.2

Xcode version - 11.2.1

**Comment by scenee** [comment]
I closed this issue. If this is also reproduced on 2.x, please reopen this.
