### ISSUE TITLE
Samples app - Build script error

### ISSUE THREAD

**Issue by richardgroves** [SCENEE/FloatingPanel#319]
### Short description
If the project folder has a space in the path then building the Samples app fails due to an error in the build script phase
### Expected behavior
It builds
### Actual behavior
Errors with 

"Command PhaseScriptExecution failed with a nonzero exit code"

### Steps to reproduce
Build Sample app from a folder that has a space in the path

**Code example that reproduces the issue**

### Environment
Catalina 10.15.3, XCode 11.3.1

**Library version**
1.7.2
**Installation method**
git clone of repo
- [ ] CocoaPods
- [ ] Carthage
- [ ] Git submodules

**iOS version(s)**
13.3 
**Xcode version**
11.3.1

Can be fixed by changing Run Script command to:

`/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(git rev-parse --abbrev-ref HEAD)($(git rev-parse --short HEAD))" "$SRCROOT/$INFOPLIST_FILE"`

[Added " around final file argument]

**Comment by SCENEE** [comment]
Thank you @richardgroves! I will fix it.
