### ISSUE TITLE
Scrolling behavior in Page Content View (Short content size) not as expected

### ISSUE THREAD

**Issue by patricknieves** [scenee/FloatingPanel#328]
### Description

When setting content size to short in "Show Page Content View" scrolling up and down only works smoothly when panel is displayed in full mode. Otherwise scrolling only works if swiping up or down fastly.
The behavior should be like in the "Scroll tracking (Tableview)" example where scrolling also works smoothly for all modes when content size is set to short.

### Expected behavior

Smooth scrolling in "Show Page Content View" when content size is set to short

### Steps to reproduce

* Samples App: Comparing the behavior of showcases "Scroll tracking (Tableview)" and "Show Page Content View" 

**How do you display panel(s)?**

* Using Page Content View Example from Sample App

**How many panels do you displays?**

* 1 Page Content View Panel

### Environment

**Library version**
1.7.4
**Installation method**
* CocoaPods
 
**iOS version(s)**
13

**Xcode version**
11.3.1

**Comment by patricknieves** [comment]
It seems to be a problem with locking and unlocking the scroll view in FloatingPanelCore

**Comment by voronoff2803** [comment]
same problem

**Comment by scenee** [comment]
I've confirmed that this problem occurs in v1.7.6, but v2.6.1 does not have it. I'd like you to migrate from v1 to v2. The migration guide is [here](https://github.com/scenee/FloatingPanel/blob/master/Documentation/FloatingPanel%202.0%20Migration%20Guide.md). Thanks for all.
