### ISSUE TITLE
floatingPanelDidChangePosition : origin wrong value

### ISSUE THREAD

**Issue by marcheimendinger** [SCENEE/FloatingPanel#329]
### Description
In `floatingPanelDidChangePosition()`, when a panel is presented modally the `vc.surfaceView.frame.origin` values are wrong.

### Expected behavior
The `vc.surfaceView.frame.origin` values should be the current ones, after the panel did change its position.

### Actual behavior
`vc.surfaceView.frame.origin` contains the values from the panel position before it opens, so useless. For example on my iPhone XS I get a value of `812.0` for `vc.surfaceView.frame.origin.y` which is actually the bottom of the screen (is equal to `view.frame.maxY`).

### Steps to reproduce

**Code example that reproduces the issue**
```
present(fpc, animated: true, completion: nil)
func floatingPanelDidChangePosition(_ vc: FloatingPanelController) {
    print("floatingPanelDidChangePosition", vc.surfaceView.frame.origin.y)
}
```

**How do you display panel(s)?**
Present modally

**How many panels do you displays?**
1 

### Environment

**Library version**
1.7.4

**Installation method**
Swift Package Manager
 
**iOS version(s)**
13.3.1

**Xcode version**
11.3.1

**Comment by SCENEE** [comment]
FloatingPanel creates and runs an animation to the next position after a user finishes dragging it. So you need to access `vc.surfaceView.presentation()?.frame` to get the actual surface frame.
