### ISSUE TITLE
Problem with the safe area when using a UITableView with static cells

### ISSUE THREAD

**Issue by mhdhejazi** [SCENEE/FloatingPanel#330]
### Description
There is a very weird issue where the `safeAreaInsets` of the content controller isn't updated and stays `.zero` when the content is a `UITableViewController` with static cells, and only when using the release configuration.

### Expected behavior
This is how it looks in debug mode:

![image](https://user-images.githubusercontent.com/121827/76167888-27832800-617b-11ea-8801-42af30a2aa59.png)

### Actual behavior
And this is how it looks in release mode:

![image](https://user-images.githubusercontent.com/121827/76167863-f0147b80-617a-11ea-88dc-e681205f2130.png)

I found the source of the problem after some debugging, and it's here:
https://github.com/SCENEE/FloatingPanel/blob/bed519f0c0152440aa75cf40813415e17fc0d5f7/Framework/Sources/FloatingPanelController.swift#L425-L427

What happens is that `change.oldValue` and `change.newValue` are always `nil` in release mode when the content is a table view with static cells. The value of `view.safeAreaInsets` is actually updated, but `change.newValue` stays `nil`!

I tried using dynamic cells instead of static cells and the problem is solved. So, it seems to be a bug in iOS itself.

As a workaround, I had to change the condition to the following:
```guard change.oldValue != self?.view.safeAreaInsets else { return }```

### Steps to reproduce

You can run the project here in release mode: https://github.com/MhdHejazi/CoronaTracker/tree/62075763e830a10681b5038fe0aca1dbbb2e2d47

**How do you display panel(s)?**

Add as child view controllers

**How many panels do you displays?**
* 1 

### Environment

**Library version**
1.7.4

**Installation method**
* Swift Package Manager
 
**iOS version(s)**
13.3.1

**Xcode version**
11.3.1

**Comment by SCENEE** [comment]
I'm so sorry I overlooked your issue. I will check this issue in detail and consider to merge the workaround to the library.

**Comment by SCENEE** [comment]
I tried to repro this issue using Xcode_11.3.1 + iOS 13.4.1 in your app, but it doesn't seem to reproduce in 13.4.1 now. (Unfortunately, I don't have an iOS 13.3.1 device, so I couldn't confirm it there).

However, your workaround is considered perfectly fine to apply to the lib, so I would change it to apply it.

Thank you very much for your report. I'm glad for you to use the lib on your excellent app.

**Comment by mhdhejazi** [comment]
> I tried to repro this issue using Xcode_11.3.1 + iOS 13.4.1 in your app, but it doesn't seem to reproduce in 13.4.1 now. (Unfortunately, I don't have an iOS 13.3.1 device, so I couldn't confirm it there).

It could very well have been fixed in iOS 13.4, but I can't confirm that as I recently switched to using dynamic cells.

Thank you for the great library and glad you like the app!
