### ISSUE TITLE
Drag and Hold

### ISSUE THREAD

**Issue by spyrosskordos** [SCENEE/FloatingPanel#332]
### Expected behavior
Is there a way to have one supported position and make the panel draggable (not dismissible).Specifically I want to have it in full position and the user to be able to hold an drag it till the tip.When the user leaves it I want to go to the default position
### Steps to reproduce

**Code example that reproduces the issue**

**How do you display panel(s)?**

* Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**

**Installation method**

* CocoaPods
* Carthage
* Swift Package Manager
 
**iOS version(s)**

**Xcode version**

**Comment by spyrosskordos** [comment]
Is there a way to have one supported position and make the panel draggable (not dismissible).Specifically I want to have it in full position and the user to be able to hold an drag it till the tip.When the user leaves it I want to go to the default position

**Comment by SCENEE** [comment]
Could you try the following way?

1. Set false to FloatingPanelController.isRemovalInteractionEnabed
```
    fpc.isRemovalInteractionEnabled = false
```
2. Set a large height in your FloatingPanelLayout.
```
    let topInteractionBuffer: CGFloat = UIScreen.main.bounds.height
    let bottomInteractionBuffer: CGFloat = UIScreen.main.bounds.height // or .greatestFiniteMagnitude
```
NOTE: `CGFloat.greatestFiniteMagnitude` is working for `bottomInteractionBuffer`.

**Comment by spyrosskordos** [comment]
It worked but now if the user hold it’s in the up direction the controller goes up and a blank space is created in the bottom..Is it possible to have it only in the down direction?
