### ISSUE TITLE
Panel doesn't get removed on swipe down

### ISSUE THREAD

**Issue by xGoPox** [SCENEE/FloatingPanel#334]
### Description

I would like to show the panel with my tableViewController, as .half and .full, and when swiping down it should remove the view.

### Expected behavior

the view should be removed on swipe down

### Actual behavior

the view is not removed on swipe down, but remains in the .half position

### Steps to reproduce

```
class ViewController: UIViewController {
    func showPanel() {
        let fpc = FloatingPanelController()
        fpc.isRemovalInteractionEnabled = true
        fpc.backdropView.dismissalTapGestureRecognizer.isEnabled = true
        fpc.delegate = self
        fpc.surfaceView.cornerRadius = 10
        fpc.surfaceView.grabberTopPadding = -15
        fpc.surfaceView.shadowHidden = false
       let tableViewController = UITableViewController()
        fpc.set(contentViewController: tableViewController)
        fpc.track(scrollView: tableViewController.tableView)
        present(fpc, animated: true)
    }
}

extension ViewController: FloatingPanelControllerDelegate {
    
    func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
        return MyFloatingPanelLayout()
    }
    
    func floatingPanel(_ vc: FloatingPanelController, behaviorFor newCollection: UITraitCollection) -> FloatingPanelBehavior? {
        return MyFloatingPanelBehavior()
    }
    
}

class MyFloatingPanelLayout: FloatingPanelLayout {

    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        return position == .full ? 0.9 : 0.8
    }

    public var initialPosition: FloatingPanelPosition {
        return .half
    }

    public var supportedPositions: Set<FloatingPanelPosition> {
        return [.full, .half]
    }

    public func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 44 
        case .half: return 300.0 
        default: return nil // Or `case .hidden: return nil`
        }
    }
}

class MyFloatingPanelBehavior: FloatingPanelBehavior {
    func shouldProjectMomentum(_ fpc: FloatingPanelController, for proposedTargetPosition: FloatingPanelPosition) -> Bool {
        return true
    }
    
}
```

**How do you display panel(s)?**

 Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**

1.7.4

**Installation method**

* CocoaPods
 
**iOS version(s)**

13.3.1

**Xcode version**

Version 11.3.1 (11C504)

**Comment by SCENEE** [comment]
For now v1 is just able to invoke the removal interaction from a bottom most position(.half in your case). But I'm going to investigate whether it's able to take off the bottom most limitation or not.

**Comment by SCENEE** [comment]
@xGoPox Could you please try `allow-removal-interaction-with-projection` branch?

**Comment by xGoPox** [comment]
Hey, I have tried and It does get removed from .full position when I swipe
down, but it doesn't work from .half position

I have :

    *public* *var* supportedPositions: Set<FloatingPanelPosition> {

        *return* [.full, .half]

    }

**Comment by polurezov8** [comment]
Hi guys, have the same issue, the panel doesn't dismiss after swipe down.

**Comment by SCENEE** [comment]
> Hey, I have tried and It does get removed from .full position when I swipe down, but it doesn't work from .half position I have : *public* *var* supportedPositions: Set<FloatingPanelPosition> { *return* [.full, .half] }
> […](#)

Hmm.. I'm testing it with "Samples.app" > "Multi Panel Modal", but it's working well. (I also tried to set `initialPosition` to `half`, though)
https://github.com/SCENEE/FloatingPanel/pull/335/files

What's different from your code?

**Comment by SCENEE** [comment]
@polurezov8 
Could you try to set `SearchSortingFloatingPanelBehavior.removalVelocity` to less than 10.0? On my testing, I can hide a panel by swiping down with your FloatingPanelLayout and Behavior.

**Comment by polurezov8** [comment]
> @polurezov8
> Could you try to set `SearchSortingFloatingPanelBehavior.removalVelocity` to less than 10.0? On my testing, I can hide a panel by swiping down with your FloatingPanelLayout and Behavior.

Thanks for the quick reaction 👍🏻
Tried to set value from 0..10 
```
    var removalVelocity: CGFloat {
        return 5
    }
```
But it didn't work.
Maybe you know other things that can turn off swiping down?

**Comment by SCENEE** [comment]
Hmm.. I tried the repro using your code except for the following code, but "allow-removal-interaction-with-projection" branch is working so that a panel can be removed by swiping down from .half position.
```
    func floatingPanelDidEndDragging(_ vc: FloatingPanelController, withVelocity velocity: CGPoint, targetPosition: FloatingPanelPosition) {
        if targetPosition == .tip {
            hideFloatingPanel()
        }
    }
```

**Comment by warpling** [comment]
I am having the same issue with a panel presented [.half, .full]. Adjusting the velocity doesn't seem to make it any more possible to dismiss the modal from .full height.
