### ISSUE TITLE
dismissalTapGestureRecognizer isEnable doesn't work

### ISSUE THREAD

**Issue by Banck** [SCENEE/FloatingPanel#341]
Hello!
Seems there is an issue with dismissalTapGestureRecognizer. If you disable dismissalTapGestureRecognizer when creating floatingPanel, it will be enabled in this file:
In FloatingPanelTransitioning.swift `override func containerViewWillLayoutSubviews() ` contains         `fpc.backdropView.dismissalTapGestureRecognizer.isEnabled = true`

**Comment by SCENEE** [comment]
Oh you're right but it's the spec problem because the modal panel's dismissal action has been enabled since the release. The spec change will affect the library users so I will modify the spec in FloatingPanel v2. Thank you so much.

**Comment by mschonvogel** [comment]
When will this be fixed? 👀
