### ISSUE TITLE
Strange layout constraint errors

### ISSUE THREAD

**Issue by kevinrenskers** [SCENEE/FloatingPanel#342]
I'm having strange layout errors when using FloatingPanel with a specific content view controller, where I am using a `UITableViewDiffableDataSource` and applying the snapshot asynchronously.

I've created a project showing the error: https://github.com/kevinrenskers/FloatingTest.

The interesting part is `TableViewController`:

``` swift
import UIKit
import Combine

class TableViewController: UIViewController {
  @IBOutlet private var tableView: UITableView!

  @Published private var text = ""
  private lazy var dataSource = makeDataSource()
  private var cancellables = Set<AnyCancellable>()

  override func viewDidLoad() {
    super.viewDidLoad()
    tableView.dataSource = dataSource

    $text
      .receive(on: DispatchQueue.main)
      .map { _ -> Void in () }
      .sink(receiveValue: applySnapshot)
      .store(in: &cancellables)
  }

  private func makeDataSource() -> UITableViewDiffableDataSource<String, AnyHashable> {
    return UITableViewDiffableDataSource<String, AnyHashable>(tableView: tableView) { tableView, indexPath, item in
      fatalError()
    }
  }

  private func applySnapshot() {
    let snapshot = NSDiffableDataSourceSnapshot<String, AnyHashable>()
    dataSource.apply(snapshot)
  }
}
```

```
2020-04-23 13:48:46.788298+0200 FloatingTest[8724:10202719] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600001a44780 h=--& v=--& FloatingPanel.FloatingPanelSurfaceView:0x7ff0f7b08560.height == 0   (active)>",
    "<NSLayoutConstraint:0x600001a44a50 V:[UITableView:0x7ff108022000]-(0)-|   (active, names: '|':UIView:0x7ff105f1ef60 )>",
    "<NSLayoutConstraint:0x600001a44c80 V:[UILabel:0x7ff105f12ec0'Label']-(16)-[UITableView:0x7ff108022000]   (active)>",
    "<NSLayoutConstraint:0x600001a45270 UILabel:0x7ff105f12ec0'Label'.top == UILayoutGuide:0x600000089c00'UIViewSafeAreaLayoutGuide'.top + 16   (active)>",
    "<NSLayoutConstraint:0x600001a45180 UIView:0x7ff105f1ef60.height == FloatingPanel.FloatingPanelSurfaceView:0x7ff0f7b08560.height   (active)>",
    "<NSLayoutConstraint:0x600001a45040 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x600000089c00'UIViewSafeAreaLayoutGuide']   (active, names: '|':UIView:0x7ff105f1ef60 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001a44c80 V:[UILabel:0x7ff105f12ec0'Label']-(16)-[UITableView:0x7ff108022000]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

I think the big problem there is the `FloatingPanelSurfaceView:0x7ff0f7b08560.height == 0` part. Why does `FloatingPanelSurfaceView` want to be 0 pixels tall?

Now, if I remove the `.receive(on: DispatchQueue.main)` operator, no error. Which is of course an easy workaround in this case, but in a real-world app this can be a necessary operator!

Also interesting: if I only show a full screen `UITableView`, also no error. But as soon as I show anything above the table, I get the error.

The error only happens when I show this view controller via FloatingPanel. If I just push it onto the navigation stack, no error.

**How do you display panel(s)?**
Present modally

**How many panels do you display?**
1 

### Environment
**Library version**
1.7.4

**Installation method**
Swift Package Manager

**iOS**
13.4.1

**Xcode**
11.4.1

**Comment by kevinrenskers** [comment]
I am also always getting `UITableView was told to layout its visible cells` warning by the way.

**Comment by SCENEE** [comment]
Thank you for your test repo. I debug your repo, bit actually It's not this library's issue because
The constraint error is at `floatingPanelController.set(contentViewController: contentVC)` before calling `present(floatingPanelController, animated: true, completion: nil)`. The reason why the surface view's height is zero.

You can fix it to override `func viewWillAppear(_ animated: Bool)` and move the following code block into it.
```
    $text
      .receive(on: DispatchQueue.main)
      .map { _ -> Void in () }
      .sink(receiveValue: applySnapshot)
      .store(in: &cancellables)
```

**Comment by kevinrenskers** [comment]
You're right, that solves all the warnings and errors. So annoying of UIKIt that workarounds like these are necessary 🤦
