### ISSUE TITLE
Background Oppacity 

### ISSUE THREAD

**Issue by OmarJalil** [SCENEE/FloatingPanel#343]
### Description
I would like to have the option to set like an opacity to let the user know there is a menu above. In the maps example when the floating panel is `.full` we can see the background gets darker. 
I would like to have that option in `.half` or '.tip'.

**Comment by SCENEE** [comment]
Is this API not enough? https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelLayout.swift#L94
