### ISSUE TITLE
Memory leak during changing contentViewController

### ISSUE THREAD

**Issue by alexander-lsvk** [SCENEE/FloatingPanel#347]
Hi all,
I use floating panel to mimic Apple's "FindMe" app. 

Means I have a view controller where I add floating panel, and when I tap on tab the - new content should be set in the floating panel.

Recently I started the leaks tests and found that each time I set new content the new leak happens.

Moreover leaks happen just during the panning gestures or calling `.move` methods.

Do I implement it in a wrong way or it is expected behavior? 
Thanks.

Attaching the example of the code where leak happens + stack trace for panning leaks
<img width="1131" alt="Screenshot 2020-05-09 at 20 13 44" src="https://user-images.githubusercontent.com/15164826/81480543-15813c80-9233-11ea-8fa1-915f4f29f0ee.png">
<img width="1647" alt="Screenshot 2020-05-09 at 20 20 44" src="https://user-images.githubusercontent.com/15164826/81480549-1b771d80-9233-11ea-8290-c94d3ae79c83.png">
<img width="1649" alt="Screenshot 2020-05-09 at 20 20 53" src="https://user-images.githubusercontent.com/15164826/81480550-1d40e100-9233-11ea-9c36-5e16e5fb4fde.png">

Version is 1.7.1

**Comment by SCENEE** [comment]
Thank you for your report! I investigated this issue and then I found memory leaks in FloatingPanel framework so I fixed them in #350. The backtrace I encountered is a bit different from yours, but I think Both of them have the same root cause.
