### ISSUE TITLE
Set up alpha for a view underneath backdrop view

### ISSUE THREAD

**Issue by akashnimare** [SCENEE/FloatingPanel#348]
@SCENEE great project. Thanks for putting your time on this. I was wondering if it's possible to set up the alpha/opacity for a child view. This is possible in the normal scenario but I'm setting up the background of that child view + using backdrop alpha. 

![image](https://user-images.githubusercontent.com/2263909/81686987-6df44c00-9476-11ea-8a46-0b21d21d8ba1.png)

So if you see the above image there is one folder icon (which is there in the main controller) and I want to set up it's alpha to 1 (make it visible on top of backdrop view) when the overlay is open. I can achieve this if I remove the backdrop alpha but then I lose the background effect. I have tried setting up the alpha + adding the main view to backdrop + bringing folder icon into the front but no luck yet.

Relevant code -

```
  func openChecklistOverlay() {
        fpc = FloatingPanelController()
        let contentVC = OverlayController()
        fpc.set()
        
        fpc.delegate = self
        
        fpc.surfaceView.cornerRadius = 12.0
        
        fpc.backdropView.backgroundColor = .blue
        
        fpc.isRemovalInteractionEnabled = true
        
        fpc.surfaceView.grabberHandle.isHidden = true
    }



class MyCustomLayout: FloatingPanelLayout {
    var initialPosition: FloatingPanelPosition {
        return .half
    }
    
    var topInteractionBuffer: CGFloat { return 0.0 }
    var bottomInteractionBuffer: CGFloat { return 0.0 }
    
    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 656.0
        case .half: return 400.0
        case .tip: return 85.0 + 44.0 // Visible + ToolView
        default: return nil
        }
    }
    
    // Background color
    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        return 0.7
    }
}
```

**Comment by akashnimare** [comment]
@SCENEE any idea on this one 😅

**Comment by SCENEE** [comment]
I think this code will achieve layout as you expect. How about it?
```
fpc.addPanel(toParent: mainVC, belowView: mainVC.folderButton, animated: true)
```
note: `mainVC` can be `self`.
