### ISSUE TITLE
When insetFor full is set to a negative value, the grab animation is broken.

### ISSUE THREAD

**Issue by kohei1218** [SCENEE/FloatingPanel#349]
### Description
I want to set the FloatingPanel to off-screen.
If I set insetFor's full to negative, the grab-and-lower animation will be broken.
Do you have a solution?

**Code example that reproduces the issue**

```
func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return -200
        case .half: return 262.0
        case .tip: return 69.0
        case .hidden: return nil
        }
    }
```

**How do you display panel(s)?**

* Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**
Latest
**Installation method**

* CocoaPods
 
**iOS version(s)**
11.4.1

**Xcode version**
11.4

I attach the URL of the video.
https://imgur.com/a/XU2qZYk

**Comment by SCENEE** [comment]
Thank you for your bug report. I confirmed it and then I created PR #352 to fix this issue. I'm happy for you to double-check it to fix this issue.

**Comment by kohei1218** [comment]
It's confirmed!
Thanks for the great library!

**Comment by SCENEE** [comment]
Thank you for your confirmation!

**Comment by rryan2** [comment]
when I set the inset to a negative value, the floating panel does not work like when that is a positive value. I tried to continue scrolling from bottom to top without lifting my finger, and my tracking scrollview was moving with my finger(also scrolling). After I lift my finger, the tracking scrollview bounce back to the correct position. Is there a way to fix this?

**Comment by SCENEE** [comment]
@rryan2 I need more information to grasp your problem because the lib's working well when I try a layout including a negative inset as described in this issue's description. I would like you to create a new issue and fill in details following the template.

**Comment by warpling** [comment]
@kohei1218 perhaps it would be more native if you set your top anchor to `0` so it doesn't extend off screen and allow the library to manage the UITableView's scrolling behavior to allow users to scroll through this oversized content? If you're having trouble getting UITableView to expand to fit it's contents I recommend [trying to give it an intrinsic content size](https://medium.com/infancyit/a-simple-solution-for-self-sizing-tableview-with-auto-resizing-cell-a3f82c4a1b34).
