### ISSUE TITLE
How to display it as a bubble ?

### ISSUE THREAD

**Issue by FlashTang** [SCENEE/FloatingPanel#351]
Hi Shin Yamamoto
I want to show FloatingPanel as a bubble ,like so:
-----------------------^-----
|                                               |
|                                               |
|                                               |
|_____________________________|

I just want FloatingPanel to be able to pan when screen is Portrait , turn into bubble when Lanscape (or in iPad)
so I use :

```
func floatingPanelShouldBeginDragging(_ vc: FloatingPanelController) -> Bool {
        return !AppDelegate.isLandscape
    }
```

```
func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> 
       FloatingPanelLayout? {
        return (newCollection.verticalSizeClass == .compact) ?FloatingPanelLandscapeLayout():FloatingPanelPortraitLayout() // Returning nil indicates to use the default layout
    }
```
 
and  here is the  prepareLayout in FloatingPanelLandscapeLayout :
```
public func prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint] {
        return [
            surfaceView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 50),
            surfaceView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor, constant: -18.0),
            surfaceView.widthAnchor.constraint(equalToConstant: 291),
            surfaceView.heightAnchor.constraint(equalToConstant: 200)
            
        ]
    }

```
but the result : can not see the bottom edge (it's all the way down to the bttom of the device),the height is not 200, I think maybe the inner "layout constraint" effects the result , so I want to know if there is a way to disable  inner "layout constraint" or any other way to make it to be able to decide the height of the panel 
I know I can hide the FloatingPanel when isLandscape ,then create a bubble view by myself , but this is not a smart way (consume memory)
and if it's possible ,then how to make bottom left right corner to be rounded ?
Thank you Shin Yamamoto for your hard work, this is super great project 👍

**Comment by SCENEE** [comment]
FloatingPanel actually hasn't yet expected your use case, but I think the problem, " can not see the bottom edge (it's all the way down to the bttom of the device)", which can be resolved to set the bottom value of `FloatingPanelSurfaceView.containerMargin` to a positive and non-zero value 🤔 

> I know I can hide the FloatingPanel when isLandscape ,then create a bubble view by myself , but this is not a smart way (consume memory)

If the content view controller is same on both of portrait and landscape orientations, I think it's better to only reuse the content view controller and create and destroy the pane container controller(FloatingPanelController) only when needed(in portrait mode).

**Comment by FlashTang** [comment]
@SCENEE  Thanks for your reply , really appreciated , I'm going to use second solution ,destroy and create new , it's  nice to work with FloatingPanel 👍
