### ISSUE TITLE
Removing damping animation on child view controller while dragging

### ISSUE THREAD

**Issue by DiwakarThapa** [scenee/FloatingPanel#361]
I realized that there is a **damping** animation when i **swipe child view controller** from half to top and vice versa because it bounces. **Is there a way to remove that animation or bounce effect ?**, I tried to remove bounce effect by setting **false allowsRubberBanding** but it didn't work.

**Comment by akashnimare** [comment]
`allowsRubberBanding` is already false by default I think cc @SCENEE

**Comment by SCENEE** [comment]
@DiwakarThapa 
You need to use a critical damping aniamtion. To change the animation, you can create a custom behavior object and return it in `floatingPanel(_:behaviorFor:)` delegate method. Here is an example of a behavior object
```swift
class FloatingPanelCustomBehavior: FloatingPanelBehavior {
    func interactionAnimator(_ fpc: FloatingPanelController, to targetPosition: FloatingPanelPosition, with velocity: CGVector) -> UIViewPropertyAnimator {
        let dampingRatio: CGFloat
        switch targetPosition {
        case .half, .full:
            dampingRatio = 1.0 // critical damping
        default:
            dampingRatio = 0.7
        }
        let timingParams =  UISpringTimingParameters(dampingRatio: 1.0,
                                        frequencyResponse: 0.4,
                                        initialVelocity: velocity)
        return UIViewPropertyAnimator(duration: 0, timingParameters: timing)
    }
}
```
[Stocks app's code](https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Stocks/Stocks/ViewController.swift#L128) helps you to use a custom behavior object.
