### ISSUE TITLE
Hello. How can change the data on FloatingPanel  depending on the value of segmented Control?

### ISSUE THREAD

**Issue by IKorabel** [SCENEE/FloatingPanel#366]
> Please remove this line and everything above it before submitting.

### Description
I want to change the data on floatingPanel depending on the value of segmentedControl. I found just the one way: With every segmentedControlAction I dismiss and show floating VC again, but I  am getting an error "Application tried to present modally an active controller <–ï–ì–≠Book.WritingPartViewController: 0x7f80c6008c00>.". How can I fix it?

<img width="1093" alt="Снимок экрана 2020-06-19 в 12 41 50" src="https://user-images.githubusercontent.com/43014903/85127298-7424d780-b22f-11ea-9f6e-ff59268301e1.png">
<img width="1093" alt="Снимок экрана 2020-06-19 в 12 39 42" src="https://user-images.githubusercontent.com/43014903/85127318-7dae3f80-b22f-11ea-86a6-1c66ab58030c.png">

### Steps to reproduce

**How do you display panel(s)?**

* Add as child view controllers
* Present modally

**How many panels do you displays?**

* 1 
* 2+

### Environment

**Library version**

**Installation method**
CocoaPods

 
**iOS version(s)**
ios 13

**Xcode version**
Xcode 11

**Comment by SCENEE** [comment]
Hello, you need to call `fpc.dismiss(animated: true)` instead of `fpc.removeFromParent()` because `fpc` is presented modally.

**Comment by IKorabel** [comment]
Thank you. But I have one more question. How can I pass data back to parent VC from FloatingVC?

**Comment by SCENEE** [comment]
It depends on your architecture. The above code lets `fpc` present modally so you are able to use `fpc.presentingViewController` to access the view controller which presented `fpc`.

**Comment by IKorabel** [comment]
Thanks for your answer, but i didn’t understand how can I pass data back from Fpc VC to Parent VC, where I called out FloatPanel. I tried everything, but it doesn’t work.

**Comment by SCENEE** [comment]
Hmm... I'm sorry I don't know your use case. `FloatingPanelController` is just a container view controller like UINavigationController. I think the `contentVC` has the data which you want to return to 'Parent VC'. There are so many ways to share the view controller having a `fpc` property. For example, you can add a property to retain `contentVC` in the view controller to access the `contentVC` data.

**Comment by IKorabel** [comment]
I want to pass data from  FPC to ParentViewController when user clicking on button. (2nd Screenshot)
Please help me, I can not understand how to fix it for a week.

<img width="1147" alt="Снимок экрана 2020-06-26 в 23 51 29" src="https://user-images.githubusercontent.com/43014903/85904119-42e87080-b808-11ea-9b6d-ea04e892f6e6.png">
<img width="1147" alt="Снимок экрана 2020-06-26 в 23 52 03" src="https://user-images.githubusercontent.com/43014903/85904123-44b23400-b808-11ea-9522-e2443fc559b2.png">

**Comment by SCENEE** [comment]
You can access `WritingPartViewController` like below in your FloatingPanelController subclass.
```
guard let vc = self.parent as? WritingPartViewController else { return }
vc.task.tasks[0] = criterions
self.dismiss(animated: true)
```
