### ISSUE TITLE
change the background view controller opacity depend on floatingLayout position

### ISSUE THREAD

**Issue by R-Ashh** [SCENEE/FloatingPanel#368]
Hello, first I wanted to thank you for this amazing stuff, the second is that I am trying to change the opacity of the background viewController depend on FloatingLayout position, 

I have seen there is a method "backgroundAlphaFor" that I can make the background opacity lower than 1.0, but the thing I am trying to do here is that I wanna check when the position is .half make the opacity of the background 0.7 and when its on .full make the opacity 0.5 and when its on the .tip position opacity go back to 1.0, is that possible?

this is my Code:

Hello, first I wanted to thank you for this amazing stuff, the second is that I am trying to change the opacity of the background viewController depend on FloatingLayout position, 

I have seen there is a method "backgroundAlphaFor" that I can make the background opacity lower than 1.0, but the thing I am trying to do here is that I wanna check when the position is .half make the opacity of the background 0.7 and when its on .full make the opacity 0.5 and when its on the .tip position opacity go back to 1.0, is that possible?

right now I am using the backdropAlphaFor method which make the background viewcontroller disable, can you help me with this?
this is my Code:

```
class FloatingPanelAdvertisingLayout: FloatingPanelLayout {
    var initialPosition: FloatingPanelPosition {
        return .tip
    }
    
    var topInteractionBuffer: CGFloat { return 0.0 }
    var bottomInteractionBuffer: CGFloat { return 0.0 }
    
    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 0.0
        case .half: return 262.0
        case .tip: return 48.0
        default: return nil
        }
    }
    
    // Background color
    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        return 0.7
    }
}

class FloatingPanelAdvertisingBehavior: FloatingPanelBehavior {
    var velocityThreshold: CGFloat {
        return 15.0
    }
    
    func interactionAnimator(_ fpc: FloatingPanelController, to targetPosition: FloatingPanelPosition, with velocity: CGVector) -> UIViewPropertyAnimator {
        let timing = timeingCurve(to: targetPosition, with: velocity)
        return UIViewPropertyAnimator(duration: 0, timingParameters: timing)
    }
    
    private func timeingCurve(to: FloatingPanelPosition, with velocity: CGVector) -> UITimingCurveProvider {
        let damping = self.damping(with: velocity)
        return UISpringTimingParameters(dampingRatio: damping,
                                        frequencyResponse: 0.4,
                                        initialVelocity: velocity)
    }
    
    func shouldProjectMomentum(_ fpc: FloatingPanelController, for proposedTargetPosition: FloatingPanelPosition) -> Bool {
        return true
    }
    
    private func damping(with velocity: CGVector) -> CGFloat {
        switch velocity.dy {
        case ...(-velocityThreshold):
            return 0.7
        case velocityThreshold...:
            return 0.7
        default:
            return 1.0
        }
    }
}
```

**Comment by SCENEE** [comment]
```
    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        switch position {
        case .full: return 0.5
        case .half: return 0.7
        default: return 1.0
        }
    }]
```
