### ISSUE TITLE
Keyboard opened above camera picker

### ISSUE THREAD

**Issue by arthurchambsp** [SCENEE/FloatingPanel#369]
### Description
I put a view controller with a textfield and a button to open camera inside a `FloatingPanelController()` presented modally.
When the textfield has the focus and the keyboard is opened, I tap the button to open camera and the keyboard is above it.
If I do the same thing in a classic modal, without a floating panel, no issue.

### Expected behavior
Keyboard should be dismissed.

### Actual behavior
Keybaord is above camera.

### Steps to reproduce
Video here : [RPReplay_Final1593593807.MP4.zip](https://github.com/SCENEE/FloatingPanel/files/4856765/RPReplay_Final1593593807.MP4.zip)

**Code example that reproduces the issue**
[test.zip](https://github.com/SCENEE/FloatingPanel/files/4856743/test.zip)

**How do you display panel(s)?**
Present modally

**How many panels do you displays?**
1 

### Environment

**Library version**
Latest : `1.7.4`

**Installation method**
CocoaPods
 
**iOS version(s)**
`13.3.5`

**Xcode version**
`XCode 11.5`

**Comment by arthurchambsp** [comment]
Anything new about it ?

**Comment by SCENEE** [comment]
I'm sorry for the delay in my response. Today I investigated and fixed this issue by this patch #381.
