### ISSUE TITLE
Ambiguous use of 'borderColor'

### ISSUE THREAD

**Issue by seki-ne** [SCENEE/FloatingPanel#370]
### Description
same as https://github.com/SCENEE/FloatingPanel/issues/152

i also tried to use `fpc.surfaceView.container.layer.borderColor = UIColor.red.cgColor`
but the border color is black, it does not change.

### Steps to reproduce
```
fpc.surfaceView.borderColor = .red  // Ambiguous use of 'borderColor'
```

### Environment

**Library version**
1.7.5

**Installation method**

* CocoaPods
 
**iOS version(s)**
13.4

**Xcode version**
11.4.1

**Comment by SCENEE** [comment]
This issue was resolved on v2 👍
