### ISSUE TITLE
Background doesn't dim as expected

### ISSUE THREAD

**Issue by warpling** [SCENEE/FloatingPanel#376]
Expected behavior:
The `backdropView` behind panels will dim or turn a translucent black.

Actual behavior:
The `backdropView` appears clear.

How to reproduce:
Run the stocks example. I tested on iOS 12 and 14.

Using: The latest copy of the repository as of July 30th 2020.

**Comment by warpling** [comment]
It turns out the dimming DOES work it just doesn't show up until the panel is nearly fully expanded. I think this also means that tap to dismiss does not work when a panel is at half height though as I am unable to get touch events when the panel is at half height but can at full height.

**Comment by jnwagstaff** [comment]
I experienced the same thing with .half, it seems like the backdrop view isn't there. If you implement the `backdropAlpha` function for the FloatingPanelLayout and return a value for .half it is present and tap to dismiss works again.

**Comment by WrathChaos** [comment]
@SCENEE, I think @jnwagstaff answer should be on README.

**Comment by SCENEE** [comment]
@WrathChaos I agree with you 👍 I will add an explanation about the backdrop alpha API.
