### ISSUE TITLE
The initial height for .half doesn't fit many screens. How to dynamically implement it?

### ISSUE THREAD

**Issue by yashjain27** [SCENEE/FloatingPanel#377]
### Steps to reproduce

**Code example that reproduces the issue**

**How do you display panel(s)?**

* Add as child view controllers
* Present modally

**How many panels do you displays?**

* 1 
* 2+

### Environment

**Library version**

**Installation method**

* CocoaPods
* Carthage
* Swift Package Manager
 
**iOS version(s)**

**Xcode version**

**Comment by warpling** [comment]
There are instructions for how to do this in the README.

**Comment by SCENEE** [comment]
Thank you, @warpling!
