### ISSUE TITLE
Click the blank are how to dismiss current panel

### ISSUE THREAD

**Issue by make2a** [SCENEE/FloatingPanel#384]
version: `2.0.0-beta.1`
![IMG_0A8376CC5DBD-1](https://user-images.githubusercontent.com/64578036/91696998-ff610880-eba2-11ea-9685-35249d8b03d9.jpeg)

**Comment by SCENEE** [comment]
Please try to set `fpc.backdropView.dismissalTapGestureRecognizer.isEnabled` to `true` and return a value greater than 0 in `backdropAlpha(for:)` in your `FloatingPanelLayout` object.

**Comment by Mehdi-Sohrabi0** [comment]
`backdropAlpha(for:)` did the trick for half screen panel, Please put that int the documentation;
