### ISSUE TITLE
Adding FloatingPanel to navigation controller

### ISSUE THREAD

**Issue by decanus** [scenee/FloatingPanel#388]
### Description

I would like to be able to add a FloatingPanel to the navigation controllers view, this would allow me to have a floatingpanel that is overlayed on all the ViewControllers in my app. Is there any quick way where we could get this functionality working. I tried doing it locally and got it to work, however it looks like the NavigationController stack messes up. The navbar isn't shown when pushing to a new view etc.

**Comment by SCENEE** [comment]
@decanus 
By the design of UINavigationController, we are able to add a panel as a child view controller. Instead, we're able to present a panel over a navigation controller as a modality. For more detail, please see [this section](https://github.com/SCENEE/FloatingPanel#present-a-floating-panel-as-a-modality).

**Comment by decanus** [comment]
@SCENEE modality doesn't really work for me, because sometimes I still need to present action controllers etc over the panel. The reason I want it on the navigation controller is because the panel should be above all my other view controllers.
