### ISSUE TITLE
FloatingPanel is hard to dismiss if isRemovalInteractionEnabled is enabled

### ISSUE THREAD

**Issue by aclassen** [SCENEE/FloatingPanel#389]
### Description
If isRemovalInteractionEnabled enabled, the panel is actually "hard" to dismiss compared to panel v1.
In v1 the panel was also dismissed if it was dragged no near bottom.
In v2 the panel is only dismissed if the panel is dragged with a very high velocity.
### Expected behavior
The panel is easier to dismiss if isRemovalInteractionEnabled is enabled.
### Steps to reproduce
Open a example app panel where isRemovalInteractionEnabled is enabled.
**Code example that reproduces the issue**

**How do you display panel(s)?**

* Add as child view controllers

**How many panels do you displays?**

* 1 

### Environment

**Library version**
2.0.0
**Installation method**

* CocoaPods
 
**iOS version(s)**
14.0

**Xcode version**
Version 12.0.1 (12A7300)

**Comment by SCENEE** [comment]
@aclassen Thank you for your feedback. You can make it easy to remove a panel using `floatingPanel(_:shouldRemoveAt location:with)` delegate method which is called [here].(https://github.com/SCENEE/FloatingPanel/blob/master/Sources/Core.swift#L717).

But now I'm thinking the API should be reconsidered because the logic, which the velocity vector is calculated from a distance to a point of the hidden state and the pan gesture's velocity, is not appropriate for a gesture. So I have an idea that the core will use just a velocity of the panel pan gesture to determine whether a pane is removed or not, and then the delegate method will pass it to the argument.

**Comment by tnmendes** [comment]
I was able to do a workaround and now is working nicely.
@aclassen you just need to add state "tip" and when you are going to that step he will automatically dismiss

```
    func floatingPanelWillBeginAttracting(_ fpc: FloatingPanelController, to state: FloatingPanelState) {
                
        if state == FloatingPanelState.tip {
            fpc.dismiss(animated: true, completion: nil)
        }
    }
```


```
class MyFloatingPanelLayout: FloatingPanelLayout {
    let position: FloatingPanelPosition = .bottom
    let initialState: FloatingPanelState = .half
    var anchors: [FloatingPanelState: FloatingPanelLayoutAnchoring] {
        return [
            .full: FloatingPanelLayoutAnchor(absoluteInset: 60.0, edge: .top, referenceGuide: .safeArea),
            .half: FloatingPanelLayoutAnchor(fractionalInset: 0.5, edge: .bottom, referenceGuide: .safeArea),
            .tip: FloatingPanelLayoutAnchor(fractionalInset: 0.25, edge: .bottom, referenceGuide: .safeArea),
        ]
    }
    func backdropAlpha(for state: FloatingPanelState) -> CGFloat {
        return 0.5
    }
}
```

**Comment by sipersso** [comment]
@SCENEE I also find it very hard to remove the panel after upgrading to 2.0.0 today. Do you have an example of how to use the "ShouldRemoveAt" method to determine if the panel should be removed or not? I am not sure how to use location and velocity to calculate if the shouldRemoveAt method should return true or false here.

**Comment by SCENEE** [comment]
@sipersso 
Here is an example to ease removing a panel in 'shoudlRemoveAt' delegate method.
```swift
    func floatingPanel(_ fpc: FloatingPanelController, shouldRemoveAt location: CGPoint, with velocity: CGVector) -> Bool {
        let threshold: CGFloat = 5.0
        switch fpc.layout.position {
        case .top:
            return (velocity.dy <= -threshold)
        case .left:
            return (velocity.dx <= -threshold)
        case .bottom:
            return (velocity.dy >= threshold)
        case .right:
            return (velocity.dx >= threshold)
        }
    }
```
The default value of `threshold` is 10.0 in 2.0.0. It causes that it's hard to remove a panel. So I'm thinking it will be between 5.0 and 6.0.

**Comment by sipersso** [comment]
@SCENEE I just tried this with 5.0 and it works perfectly. Thank you!

**Comment by SCENEE** [comment]
>  the velocity vector is calculated from a distance to a point of the hidden state and the pan gesture's velocity, is not appropriate for a gesture. So I have an idea that the core will use just a velocity of the panel pan gesture to determine whether a pane is removed or not, and then the delegate method will pass it to the argument.

After I try the above new logic, I confirmed the current logic is better because a swipe speed to dismiss a panel and ease of the acceleration can changes depending on a distance from a screen edge to hide it.

As a result, I'm going to ease a threshold to remove a panel in PR #395.
