### ISSUE TITLE
get progress of panel as it is dragged upward or downward.

### ISSUE THREAD

**Issue by Frankenxtein** [SCENEE/FloatingPanel#391]
### How can i get the current progress of the panel so that i can adjust the opacity of the UI elements in the content viewcontroller as the panel is dragged up or down.

**Comment by SCENEE** [comment]
Hi, @Frankenxtein. To calculate a progress to a state, you are able to use `surfaceLocation` and `surfaceLocation(for:)` in `FloatingPanelController`.  [This example](https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Maps/Maps/ViewController.swift#L174) could also help you.
