### ISSUE TITLE
Undefined behavior when controlling panel only by move(to: FloatingPanelState

### ISSUE THREAD

**Issue by mstana** [SCENEE/FloatingPanel#392]
### Description
When the client tries to change panel state just with method `move(to:` and buttons the panel acts weirdly and does not allow to tap on buttons every time. When client moves the panel by dragging in every tappable position the buttons and panel are working as expected.

Steps to reproduce:
1. Tap move to full
2. Tap move to half **(button does not work)**
3. Drag a couple of pixels in the full state (stay on full state)
4. Tap move to half **(button works)**

### Expected behavior
The buttons should be tappable on the first hit and panel should change it's state.
### Actual behavior
The buttons are not tappable on the first tap - sometimes it works after couple of taps.
### Steps to reproduce

**Code example that reproduces the issue**
Use `DebugTableViewController` and add 2 buttons to `buttonStackView` with actions: 
`
    @objc func moveToFull() {
        (self.parent as! FloatingPanelController).move(to: .full, animated: true)
    }
`
`
    @objc func moveToHalf() {
        (self.parent as! FloatingPanelController).move(to: .half, animated: true)
    }
`

**How do you display panel(s)?**
Use default implementation of `DebugTableViewController` from Samples target.

### Environment

**Library version**
2.0.0

**Installation method**
CocoaPods
 
**iOS version(s)**
iOS 13

**Xcode version**
XCode 11.7

**Comment by SCENEE** [comment]
Thank you for your detail report, @mstana! Thanks to your repro steps, I confirmed and fixed this issue quickly. I believe this issue has already fixed in PR #396.

**Comment by mstana** [comment]
Thank you @SCENEE. When I should expect it merged into master, please?

**Comment by SCENEE** [comment]
Hi, @mstana. I'm going to release v2.0.1 on this week. Please wait for a little while longer.

**Comment by mstana** [comment]
> v2.0.1

Hey @SCENEE thanks for your help. When I can expect 2.0.1 to be available for update thru CocoaPods? I see the changes are merged into master but version is not bumped to 2.0.1 in podspec.

**Comment by SCENEE** [comment]
Hi, now I've released v2.0.1 and published the podspec to CocoaPods trunk! Thank for your patient.
