### ISSUE TITLE
How to customize modal animation speed? 

### ISSUE THREAD

**Issue by sipersso** [SCENEE/FloatingPanel#393]
### Description
I just upgrade to 2.0.0. I am presenting FloatingPanel modally. The dismiss animation is a lot faster than the default iOS transitions. Any way to slow it down? It is definitely a faster transition after the update to 2.0.0

### Expected behavior
Present and dismiss should match default iOS behavior

### Actual behavior
Present and dismiss animation have a much shorter duration than default iOS behavior. 

### Steps to reproduce

1: Present timerpanel modally
2: Dismiss the modal viewcontroller

### Environment

**Library version**
2.0.0

**Comment by SCENEE** [comment]
You are able to specify presentation and dismissal animations using the following 2 delegate methods. Here is an example.
```swift
    func floatingPanel(_ fpc: FloatingPanelController, animatorForPresentingTo state: FloatingPanelState) -> UIViewPropertyAnimator {
        return UIViewPropertyAnimator(duration: 0.25, curve: .easeOut)
    }
    func floatingPanel(_ fpc: FloatingPanelController, animatorForDismissingWith velocity: CGVector) -> UIViewPropertyAnimator {
        return UIViewPropertyAnimator(duration: 0.25, curve: .easeOut)
    }
```

**Comment by sipersso** [comment]
Thank you @SCENEE! That was easy. I almost feel bad that I couldn't figure this out myself. Thank you so much!
