### ISSUE TITLE
Incredible Library has no option for sponsoring the author

### ISSUE THREAD

**Issue by warpling** [SCENEE/FloatingPanel#400]
### Description
This library is exceptionally crafted and provides a level of control and customization that Apple never could have. It would be nice to be able to pay forward our thanks for making and managing such an endeavor! 

### Expected behavior
I expect to be able to pay my saved time and thanks forward 

### Actual behavior
I don't see a Sponsor button :(

**Comment by SCENEE** [comment]
Thank you so much, @warpling. I'm very touched that you've shown your appreciation as the above. 
I'm happy enough just with your gratitude, but I would like to respond to your request and will consider setting up a Sponsor button.

**Comment by zntfdr** [comment]
If Github sponsor is available in Japan, please consider to enable it! 

I'm more than happy to join @warpling on the sponsorship side 😁

**Comment by SCENEE** [comment]
Thank you for @warpling and @zntfdr! I'm sorry I ‘m late to respond your requests. Today I have displayed the sponsor button in this repo. I so appreciate that you have already joined my sponsors.
