### ISSUE TITLE
On add to panel animation complete event

### ISSUE THREAD

**Issue by ziv-mishloha** [scenee/FloatingPanel#402]
Is it possible to get notified after .addPanel(toParent: vc, animated: true) finished animating?

**Comment by SCENEE** [comment]
I'm sorry it isn't possible for now and you need to `show(animated:completion)`. However I'm considering to add `completion` argument to addPanel method.

**Comment by scenee** [comment]
`addPanel(toParent:)` has been added a completion handler since v2.4.0. Thank you for your request.
