### ISSUE TITLE
FloatingPanelBehavior & rubber-band effect activation

### ISSUE THREAD

**Issue by groue** [SCENEE/FloatingPanel#405]
Hello,

Thanks for keeping FloatingPanel the best library in town :-) My upgrade to v2 was super smooth, thanks to the migration guide, but for one point:

### Description

It is difficult to profit from the [fine-tuned](https://github.com/SCENEE/FloatingPanel/blob/2.0.1/Sources/Behavior.swift#L50) `FloatingPanelDefaultBehavior` and activate the rubber-band effect at the same time.

I need the rubber-band effect, or else my view controller whose only anchors states are `.half` and `.hidden` lets the user drag it to the top as if the `.full` state were available. Thanks to the rubber-band effect, the user understands that there is no purpose dragging this view controller to the top: it "resists". And since FloatingPanel 2 does not enable this effect [by default](https://github.com/SCENEE/FloatingPanel/blob/2.0.1/Sources/Behavior.swift#L82), I need to do it explicitly.

### Expected behavior

- `FloatingPanelDefaultBehavior` is an open class and can be subclassed so that only `allowsRubberBanding(for:)` has to be overriden. 
- OR `FloatingPanelDefaultBehavior` has a public initializer so that one can create a `FloatingPanelBehavior` class that returns all the fine-tuned values of `FloatingPanelDefaultBehavior`, except in `allowsRubberBanding(for:)`.
- OR `FloatingPanelDefaultBehavior` has both a public initializer and a property that changes the result of its `allowsRubberBanding(for:)`.
- OR anything that prevents the "Actual behavior" described below:

### Actual behavior

I had to copy and paste the full `FloatingPanelDefaultBehavior` class in my app so that I can both profit from the fine-tuned default behavior, and return `true` from `allowsRubberBanding(for:)`.

This pasted code:

- looks full of magic values.
- pretends the app cares about it, when it doesn't (instead, it wants to profit from this library's experience and delegate a maximum of subtle UI code).
- won't update when you tweak and improve `FloatingPanelDefaultBehavior` in the future.
- won't update when `FloatingPanelBehavior` gets more `@objc optional` methods in the future and `FloatingPanelDefaultBehavior` fine-tunes them.

### Steps to reproduce

**Code example that reproduces the issue**

```swift
/// This class is copy-pasted from `FloatingPanelDefaultBehavior`, with
/// a twist in `allowsRubberBanding(for:)`.
///
/// Please keep it up to date when the FloatingPanel dependency
/// is updated.
private class MyFloatingPanelBehavior: FloatingPanelBehavior { ... }
```

**How do you display panel(s)?**

* Add as child view controllers

**How many panels do you displays?**

* 2+

### Environment

**Library version**

* 2.0.1

**Installation method**

* CocoaPods
 
**iOS version(s)**

* iOS 14.2

**Xcode version**

* Xcode version 12.2

**Comment by groue** [comment]
For the record, I tried to keep the default behavior and change the available anchors to `.hidden` and `.full` (what's bigger than `.full`?)

But the rubber-band effect is still not enabled by default, and I still need to copy & paste `FloatingPanelDefaultBehavior`.

```swift
private class MyFloatingPanelLayout: FloatingPanelBottomLayout {
    override var initialState: FloatingPanelState { .full }
    
    override var anchors: [FloatingPanelState: FloatingPanelLayoutAnchoring] {
        [
            .full: FloatingPanelLayoutAnchor(
                absoluteInset: 250,
                edge: .bottom,
                referenceGuide: .safeArea),
            .hidden: FloatingPanelLayoutAnchor(
                absoluteInset: 0,
                edge: .bottom,
                referenceGuide: .superview),
        ]
    }
}
```

**Comment by SCENEE** [comment]
@groue Thank you for your detail request about `FloatingPanelDefaultBehavior`. I created `open-default-behavior` branch to response to it.  #406

**Comment by groue** [comment]
Thanks! I'll try on on Monday 🙂
