### ISSUE TITLE
Scroll indicators are hidden after hitting the top once

### ISSUE THREAD

**Issue by futuretap** [SCENEE/FloatingPanel#41]
The scroll indicators of an embedded scroll view are hidden once the user hits the top once and subsequently scrolls back down. See here:

![floatingpanel-scrollindicators](https://user-images.githubusercontent.com/110374/48281329-884f0300-e456-11e8-9d0f-068658b3275f.gif)

**Comment by SCENEE** [comment]
Thanks for your report! I fix it at `fix-scroll-indicator-hidden` branch. Could you please try it?

**Comment by futuretap** [comment]
The scroll indicators are still hidden **while tracking** once the user hits the top once. They do reappear only in the deceleration phase when the user lifts the finger.

**Comment by SCENEE** [comment]
Hmm..., It works what you say if my understanding is correct.
I tested 'fix-scroll-indicator-hidden' branch again and captured a gif.
Is not the following behavior what you expect?
![issue41](https://user-images.githubusercontent.com/899487/48379477-9b442a80-e717-11e8-83fe-9d750dc8db3e.gif)

**Comment by futuretap** [comment]
Indeed, it works fine now. Don't know why it didn't at the first try.
So please merge into master.

**Comment by SCENEE** [comment]
Good to hear that! Thanks for your confirmation and report!
