### ISSUE TITLE
Fatal error: vc is nil

### ISSUE THREAD

**Issue by mschonvogel** [SCENEE/FloatingPanel#419]
https://github.com/SCENEE/FloatingPanel/blob/7114f545ff98644c93c345a77719f9e045bd698f/Sources/Layout.swift#L193

Sometimes `vc` is nil and causing a fatal error here.

**Comment by SCENEE** [comment]
Thank you for your report! I assume that the root cause is a memory leak of the `Core` or the layout adapter object. I'm working on this issue so I'm going to create a PR soon.

**Comment by mschonvogel** [comment]
Thank you @SCENEE 👍👍

**Comment by SCENEE** [comment]
Do you display a panel as a modality like `self.present(fpc, animated: true, completion: nil)`?

**Comment by SCENEE** [comment]
I've pushed [iss-491](https://github.com/SCENEE/FloatingPanel/tree/iss-419) branch which has possible fixes for this issue. I hope it resolves the fatal error.
