### ISSUE TITLE
[Bug/Feature Request] Increase priority of Layout.interactionConstraint

### ISSUE THREAD

**Issue by Argent** [SCENEE/FloatingPanel#424]
### Description

I have the requirement that my floating panel always displays a button at the bottom of the sheet. If the panel size is increased (dragged up) the button should stay at the bottom of the screen.
To achieve this I'm using `fpc.contentMode = .fitToBounds` to fit the content of my custom ViewController to the size of the panel.

However with `fitToBounds` it prevents my panel from being dragged out of the screen in the bottom direction.

I found out that the reason for this is the priority of `Layout.interactionConstraint` which is set to `.defaultHigh`. If the priority is set to `.required` everything works as expected.

Unfortunately the constraint is not accessible from outside the framework and thus its not easy to change the priority.

It would be good to change the priority to `.required` for default or at least make it configurable.

### Expected behavior

I can drag the panel in bottom direction even if `.fitToBounds` is enabled

### Actual behavior

The priority of `interactionConstraint` is too low so that the VCs intrinsic height blocks the panel from being dragged in bottom direction

Actual behavior|Expected behavior
-|-
![2021-01-02 10 04 40](https://user-images.githubusercontent.com/717301/103454450-96baa180-4ce4-11eb-9f6e-d79a3cfef1f1.gif)|![2021-01-02 10 05 11](https://user-images.githubusercontent.com/717301/103454453-9fab7300-4ce4-11eb-88df-e4ca5f570ec6.gif)

**Comment by SCENEE** [comment]
Thank you for your request. I agree that its priority will be set to `.required`. I supposed that `. defaultHigh` priority would reduce the layout problem, but I was wrong.

**Comment by SCENEE** [comment]
I've updated the priority to `.required`. Thank you for your report.
