### ISSUE TITLE
Panel gets dismissed when swiping to delete on a tableView items. 

### ISSUE THREAD

**Issue by mazvydasb** [SCENEE/FloatingPanel#427]
### Description

Panel seems to be super sensitive. Unless swiped in a perfectly horizontal line. panel is set to track the tableView. This mostly happens when the list is scrolled to top.

### Expected behavior

Would expect it to ignore tableView interactions, except for actual scrolling.

### Steps to reproduce

**How do you display panel(s)?**
* Presented modally

**How many panels do you displays?**
* 1 

### Environment

**Library version**
2.1.0

**Installation method**
* CocoaPods
 
**iOS version(s)**
All

**Xcode version**
12.3

**Comment by SCENEE** [comment]
I confirmed that a panel moves while closing edit actions of UITableViewCell where the content offset of a table view is zero. I've pushed `iss-427` branch to address this issue. Please try the branch and give me your feedback.

**Comment by mazvydasb** [comment]
Yup, this did the trick. Thx!

**Comment by SCENEE** [comment]
@mazvydasb Thank you for your confirmation. I've merge the patch to master 😄
