### ISSUE TITLE
Multiple panel how to hide previous

### ISSUE THREAD

**Issue by andrii-lisovskiy** [SCENEE/FloatingPanel#432]
I am using multiple panels with different layouts (half/tip/top) in our app. How can I hide or just bind them to the top view's top position? (Like Find My app does)

**Comment by SCENEE** [comment]
You can hide the backed panel by calling `fpc.move(to: .hidden, animated: false)`. FindMy app doesn't look like binding them actually, but the technic that its surface position changes in `floatingPanelDidMove` of the front panel might allow the backed panel to follow front one.

**Comment by andrii-lisovskiy** [comment]
Thanks a lot, it works!
