### ISSUE TITLE
EKProperty.TextFieldContent(<args>) : Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by idevChandra6** [SCENEE/FloatingPanel#433]
### Description
Initializing `EKProperty.TextFieldContent` gives compilation error `Type of expression is ambiguous without more context`

### Expected behavior
EKProperty.TextFieldContent gets initialized with out any errors

### Actual behavior
Gives build error

### Steps to reproduce
1. import SwiftEntryKit
2. Init a variable as mentioned in code example.

**Code example that reproduces the issue**

```
        let passwordTextField = EKProperty.TextFieldContent(
            keyboardType: .default,
            placeholder: EKProperty.LabelContent(text: "New Password", style: EKProperty.LabelStyle(font: UIFont(name: "OpenSans", size: 13)!, color: EKColor(light: .lightGray, dark: .lightGray))),
            tintColor: .none,
            displayMode: .inferred,
            textStyle: EKProperty.LabelStyle(font: UIFont(name: "OpenSans", size: 13)!, color: EKColor(light: .darkGray, dark: .darkGray)),
            isSecure: true,
            leadingImage: .none,
            bottomBorderColor: EKColor(light: UIColor(hex: kAppColor_GreenSeparator), dark: UIColor(hex: kAppColor_GreenSeparator)),
            accessibilityIdentifier: "Password")
```

### Environment

**Library version**
1.2.7

**Installation method**
CocoaPods

**iOS version(s)**
iOS 14.3

**Xcode version**
Version 12.3 (12C33)

**Comment by SCENEE** [comment]
Hello, @idevChandra6. You created this issue in the wrong repository.
