### ISSUE TITLE
Slow animations in Simulator

### ISSUE THREAD

**Issue by sebastiandevuy** [scenee/FloatingPanel#439]
### Description

Recently i upgraded from 1.7.0 to 2.2.0 and after making all api changes based on the migration guide i am noticing that in the Simulator the animation when going from lets say tip to full is tremendously slow (and viceversa). This does not happen in an actual device where the animation is smooth. Slow animations are disabled in the simulator and i can see other animations in the app going smoothly in the simulator. I am using the FloatingPanelDefaultBehavior.

### Expected behavior

- Animation to work in the simulator the same way as in the actual device

### Actual behavior

- Animation is slow, so much i can see the bouncing when reaching each state in slow motion.

### Steps to reproduce

- Use 2.2.0 with FloatingPanelDefaultBehavior

**How do you display panel(s)?**

As child view controller

**How many panels do you displays?**

1

### Environment

2.2.0

**Installation method**

Cocoapods
 
**iOS version(s)**

14.4

**Xcode version**

12.4

**Comment by scenee** [comment]
Thank you for your report, @sebastiandevuy. Does this issue also happen on the example apps for this lib(Maps, Stocks and Samples) on your mac? Because I'm not able to reproduce this issue on my mac.

**Comment by sebastiandevuy** [comment]
@scenee Thanks for the response. I tried those samples in my Mac and they are OK so whatever the issue, is certainly in my project and not widespread in the library. Closing the issue. Thanks for checking!
