### ISSUE TITLE
Layout.swift: Fatal error: Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by mschonvogel** [scenee/FloatingPanel#440]
Sometimes when dismissing the panel with a swipe gesture, it crashes in Layout.swift, line 307.

![image](https://user-images.githubusercontent.com/370839/108427683-d8c08800-723d-11eb-8370-71ca73393a09.png)

I'm using version 2.2.0

This is how create the panel:
```swift
    static func createPanel(userId: String) -> FloatingPanelController {
        let panelViewController = FloatingPanelController()
        let viewController = ProfileViewController(userId: userId)
        viewController.panelController = panelViewController
        panelViewController.layout = IntrinsicFloatingPanelLayout()
        let behavior = FloatingPanelDefaultBehavior()
        behavior.removalInteractionVelocityThreshold = 2.5
        panelViewController.behavior = behavior
        panelViewController.set(contentViewController: viewController)
        panelViewController.isRemovalInteractionEnabled = true
        panelViewController.surfaceView.appearance.cornerRadius = Metrics.Panel.cornerRadius
        panelViewController.surfaceView.backgroundColor = UIColor.defaultBackground
        panelViewController.backdropView.dismissalTapGestureRecognizer.isEnabled = true
        panelViewController.surfaceView.grabberHandle.isHidden = true
        return panelViewController
    }
```

And this is the layout I'm using:

```swift
class IntrinsicFloatingPanelLayout: FloatingPanelLayout {
    let position: FloatingPanelPosition = .bottom
    let initialState: FloatingPanelState = .full
    var anchors: [FloatingPanelState: FloatingPanelLayoutAnchoring] {
        [
            .full: FloatingPanelIntrinsicLayoutAnchor(absoluteOffset: 0, referenceGuide: .superview),
        ]
    }
}
```

**Comment by scenee** [comment]
Thank you for your report. I've been wondering about a possibility of a memory leak in updateScrollView() since before but I've had no evidence. But now I'm convinced the inner function must be change thanks to your report. I will take care of this crash this weekend.

**Comment by scenee** [comment]
Hello, @mschonvogel. I've created a branch to attempt to fix this issue(PR #441). Could you please check whether this branch fixes your reporting issue or not?

**Comment by mschonvogel** [comment]
Yes, will do. As I am not really able to reproduce the bug, I'd say I'll just use the app and let you know in 2-3 days if it crashed again or not?

**Comment by mschonvogel** [comment]
Looking good, no crash so far @scenee 👍

**Comment by scenee** [comment]
Thank you so much, @mschonvogel 🎉  I will merge PR #441 and release the new version in a week.
