### ISSUE TITLE
How to animate the contents while pan gesture being progress? 

### ISSUE THREAD

**Issue by Thavasidurai** [scenee/FloatingPanel#445]
I like to animate the content view controller's subviews using UIViewPropertyAnimator like the Google Map app does when you scroll up/down the panel.  Can you please guide me on how to achieve using this library?

**Comment by scenee** [comment]
You're able to start a UIViewPropertyAnimator animation in `func floatingPanelDidEndDragging(_ fpc: FloatingPanelController, willAttract attract: Bool)` delegate method and also cancel in ` func floatingPanelDidEndAttracting(_ fpc: FloatingPanelController)` if it's interrupted.

However I highly recommend you to change constraints of its contents in `func floatingPanelDidMove(_ fpc: FloatingPanelController)` delegate to animate them like an animation following a scroll of UIScrollView.
