### ISSUE TITLE
CollectionView within Tableview scrollTrack issue

### ISSUE THREAD

**Issue by Ahmed-Masoud** [scenee/FloatingPanel#446]
Firstly I wanna thank you so much for the great effort 
I have an issue with my layout I have a tableview with collection view nested in its cell i set my fps track to the tableview and start initially in half the problem is I can't swipe up to make the panel go to full mode as the collection captures the vertical scroll but when i start in full position everything works fine until i change the position back to half any ideas how i can fix this and thanks

**Comment by scenee** [comment]
Thank you, too. I tried to repro the problem, but unfortunately I couldn't. Could you give me a sample code to investigate it?

**Comment by Ahmed-Masoud** [comment]
I created a mock project to show the issue you can find it here
https://github.com/Ahmed-Masoud/FloatingPanelDemo
also please note that sometimes it works fine on the simulator but never on the physical device
please advice and thanks a lot in advance

**Comment by scenee** [comment]
Thanks to your example, I could detect the cause of this issue. This is because FloatingPanel's pan gestures doesn't recognize a pan gesture until no tracking scroll views(the collection views in this case)'s pan gesture is failed. FloatignPanel gives priority to no tracking scroll views’ gesture by default.

And then this issue can be resolved by `FloatingPanelController.panGestureRecognizer.delegateProxy` as below to change its priority to gestures.

```diff
diff --git a/FloatingPanelDemo/ViewController.swift b/FloatingPanelDemo/ViewController.swift
index da03ce8..566cb66 100644
--- a/FloatingPanelDemo/ViewController.swift
+++ b/FloatingPanelDemo/ViewController.swift
@@ -32,9 +32,14 @@ class ViewController: UIViewController {
         fpc.surfaceView.grabberHandle.isHidden = true
         fpc.surfaceView.contentPadding = .init(top: 0, left: 0, bottom: 0, right: 0)
         fpc.surfaceView.containerMargins = .init(top: 0, left: 0, bottom: 0, right: 0)
+        fpc.panGestureRecognizer.delegateProxy = self
         fpc.addPanel(toParent: self)
     }
+}
 
 
+extension ViewController: UIGestureRecognizerDelegate {
+    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRequireFailureOf otherGestureRecognizer: UIGestureRecognizer) -> Bool {
+        false
+    }
 }
-
```

**Comment by Ahmed-Masoud** [comment]
Yup that fixed the Issue 🎉 thanks a lot for your reply and keep the great work 👍
