### ISSUE TITLE
Floating panel pull down also triggers modal dismissal

### ISSUE THREAD

**Issue by jdelaune** [scenee/FloatingPanel#447]
Hi thanks for the great library.

I'm hitting a bit of an issue with the new iOS 14 interactive swipe dismiss for modals and this library. I want to have a floating panel within a modal. When I pull down to collapse the floating panel I would expect it to just dismiss the floating panel. However it is also triggering the modal to dismiss as well.

Example project here: https://github.com/jdelaune/FloatingExample

In ModalViewController which I present the floating panel from I have tried things like `isModalInPresentation = false`. However you still get a bounce on dismiss.

Next when I tried `navigationController?.presentationController?.presentedView?.gestureRecognizers?.first?.isEnabled = false` (which is a bit hacky I know) it works for the ModalViewController but the floating panel still triggering the dismissal.

Do you know what is going on in the floating panel to cause this. Can we stop it from triggering other touch recognisers?

Thanks

**Comment by scenee** [comment]
The root cause is this dismissal functionality of the sheet modal.

> Swiping down from anywhere on the screen when card content is scrolled to the top
https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/

Unfortunately, there seems to be no way for us to disable the scroll tracking of a sheet modal. However I figured out 2 ways to mitigate this issue. They are not perfect, but either of them might be useful for your use case.

One way is the following patch. We are able to solve the modal dismissal issue, but as a trade-off a scroll view inside a panel isn't able to scroll.
```diff
diff --git a/FloatExample/ModalViewController.swift b/FloatExample/ModalViewController.swift
index 54a91d6..a9615c0 100644
--- a/FloatExample/ModalViewController.swift
+++ b/FloatExample/ModalViewController.swift
@@ -16,9 +16,10 @@ class ModalViewController: UIViewController, FloatingPanelControllerDelegate {
         // Initialize a `FloatingPanelController` object.
         fpc = FloatingPanelController()
 
+        /*
         // First Attempt: But but still get the bounce using isModalInPresentation
         isModalInPresentation = false
-        
+
         // Second Attempt: A bit hacky but disable the recognizer. Works for the ModalViewController.
         // However when dismissing the floating panel it is pulling down the modal again.
         let recognizers = navigationController?.presentationController?.presentedView?.gestureRecognizers
@@ -26,6 +27,7 @@ class ModalViewController: UIViewController, FloatingPanelControllerDelegate {
         if let firstRecognizer = recognizers?.first {
             firstRecognizer.isEnabled = false
         }
+         */
 
         // Assign self as the delegate of the controller.
         fpc.delegate = self // Optional
@@ -39,5 +41,13 @@ class ModalViewController: UIViewController, FloatingPanelControllerDelegate {
 
         // Add and show the views managed by the `FloatingPanelController` object to self.view.
         fpc.addPanel(toParent: self)
+
+        fpc.panGestureRecognizer.delegateProxy = self
+    }
+}
+
+extension ModalViewController: UIGestureRecognizerDelegate {
+    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldBeRequiredToFailBy otherGestureRecognizer: UIGestureRecognizer) -> Bool {
+        return true
     }
 }
```

Another way is to present a panel as a modality. However it also has a trade off. Instead we can scroll a scroll view in a panel, we are not able to swipe down a sheet modal.
```swift
self.present(fpc, animated: true, completion: nil)
```

**Comment by rordeix** [comment]
Hey! First at all, this library is awesome! Thank you!

I ran on the same issue on a project on my own, and found this issue of course. What I did was setting the refresh control to the `UITableView` which seems to work  (scroll works to expand/collapse the panels, and swipe down to dismiss still works on the main view controller). On your example:

```diff
diff --git a/FloatExample/ModalViewController.swift b/FloatExample/ModalViewController.swift
index 54a91d6..8c96f4e 100644
--- a/FloatExample/ModalViewController.swift
+++ b/FloatExample/ModalViewController.swift
@@ -16,22 +16,12 @@ class ModalViewController: UIViewController, FloatingPanelControllerDelegate {
         // Initialize a `FloatingPanelController` object.
         fpc = FloatingPanelController()
 
-        // First Attempt: But but still get the bounce using isModalInPresentation
-        isModalInPresentation = false
-        
-        // Second Attempt: A bit hacky but disable the recognizer. Works for the ModalViewController.
-        // However when dismissing the floating panel it is pulling down the modal again.
-        let recognizers = navigationController?.presentationController?.presentedView?.gestureRecognizers
-
-        if let firstRecognizer = recognizers?.first {
-            firstRecognizer.isEnabled = false
-        }
-
         // Assign self as the delegate of the controller.
         fpc.delegate = self // Optional
 
         // Set a content view controller.
         let contentVC = UITableViewController()
+        contentVC.refreshControl = UIRefreshControl()
         fpc.set(contentViewController: contentVC)
 
         // Track a scroll view(or the siblings) in the content view controller.
 ```
 
 I hope it helps :)

**Comment by jdelaune** [comment]
@rordeix spooky and amazing at the same time. Thanks. Also works for UICollectionViews in the floating panel :)
