### ISSUE TITLE
didSelectRowAt not called for ASTableNode inside FloatingPanel

### ISSUE THREAD

**Issue by althurzard** [scenee/FloatingPanel#450]
This issue seems similar to #282, but for ASTableNode - This is a part of ASDisplayKit lib.
My content view controller has a ASTableNode, which should call the didSelectRowAt delegate method when an item is tapped, but it is not called.

**Comment by scenee** [comment]
Which version of ASDisplayKit do you use? I would like to reproduce this issue in a sample app.

**Comment by althurzard** [comment]
> Which version of ASDisplayKit do you use? I would like to reproduce this issue in a sample app.

I'm using Texture 3.0.0.

**Comment by scenee** [comment]
Thanks, @althurzard. I just tried to repro this issue using [texture-sample-d7c4bf2.tar.gz](https://github.com/scenee/FloatingPanel/files/6310942/texture-sample-d7c4bf2.tar.gz) today. But. `tableNode(:didSelectRowAt:)` delegate works as expected. 🤔

**Comment by althurzard** [comment]
My bad.. I figured out there was some gesture code that tap to dismiss keyboard. I removed it and everything worked fine..
Btw thanks for one of the best lib out there
