### ISSUE TITLE
Update intrinsic height of view based off new layout constraints 

### ISSUE THREAD

**Issue by daihovey** [scenee/FloatingPanel#453]
### Description
While using an intrinsic layout (IntrinsicPanelLayout see below) I would like to update the content inside the view, which can mean a change in height. Is it possible to tell the layout adaptor to recalculate its constraints based off the content's new height. I've tried `fpc.invalidateLayout()` after setting up the new constraints, but the height of the fpc remains the same.

```
class IntrinsicPanelLayout: FloatingPanelBottomLayout {
    override var initialState: FloatingPanelState { .full }
    override var anchors: [FloatingPanelState: FloatingPanelLayoutAnchoring] {
        [
            .full: FloatingPanelIntrinsicLayoutAnchor(absoluteOffset: 0.0, referenceGuide: .safeArea)
        ]
    }
}
```
Thanks 🙏

**How do you display panel(s)?**
* Present modally

**How many panels do you displays?**
* 1 

### Environment

**Library version**
2.3.0
**Installation method**
* CocoaPods

**iOS version(s)**
14.0

**Xcode version**
12.4

**Comment by daihovey** [comment]
Possibly related to https://github.com/scenee/FloatingPanel/pull/208

**Comment by scenee** [comment]
Does your code call `layoutIfNeeded()` of the root view of the content changing its constraints before calling `fpc.invalidateLayout()`? I suspect that `SurfaceView.intrinsicContentSize` hugging the content isn't changed before calling `fpc.invalidateLayout()`.

**Comment by daihovey** [comment]
Yep 
```
buttonHeightContraint.constant = 100

UIView.animate(withDuration: 0.2) {
      self.view.layoutIfNeeded()
      self.fpc.invalidateLayout()
}
```

**Comment by daihovey** [comment]
Are there examples of changing the surfaceView's contents while using a `FloatingPanelIntrinsicLayoutAnchor` and the fpc's height automatically changes to fit?

**Comment by daihovey** [comment]
Realised it was my fault: Autolayout broke within the StackView 🤦‍♀️.
