### ISSUE TITLE
How do i check if a floating panel is currently open ? 

### ISSUE THREAD

**Issue by SheikhZayed** [scenee/FloatingPanel#457]
I need to check if a floating panel is currently open, If its open i need to close it before adding a panel on top of it.

**Comment by scenee** [comment]
Hmm..., a panel doesn't have 'open' and 'close' states. Isn't enough `FloatingPanelController.state`?

**Comment by SheikhZayed** [comment]
fine, thanks anyway.. i managed to implement my requirement 👍🏻
