### ISSUE TITLE
How to set the floating panel at the bottom(.tip state) initially instead of it being in the middle(.half state)?

### ISSUE THREAD

**Issue by anandpq** [scenee/FloatingPanel#458]
**Library version**
Latest

**Installation method**
* Carthage

**Comment by scenee** [comment]
[README > Change the initial layout](https://github.com/scenee/FloatingPanel#change-the-initial-layout) can help you.

**Comment by khenissimehdi** [comment]
When i try to set the layout its says that the layout is get only prop do you have any idea how can i fix this please
