### ISSUE TITLE
Tap-to-dismiss in the backdrop view not enabled by default

### ISSUE THREAD

**Issue by mihaicris-adoreme** [scenee/FloatingPanel#463]
### Description
Tap-to-dismiss in the backdrop view not enabled by default.

### Expected behavior
To be activated by default or to have a setting to activate or deactivate

### Actual behavior
Tap on dismiss in the backfrop view is by default not enabled.

From code:
```swift
// Set tap-to-dismiss in the backdrop view
let tapGesture = UITapGestureRecognizer(target: self, action: #selector(handleBackdrop(tapGesture:)))
tapGesture.isEnabled = false
```

**Comment by scenee** [comment]
Hi, you can enable it like [this](https://github.com/scenee/FloatingPanel/blob/master/Examples/Samples/Sources/UseCaseController.swift#L73).

**Comment by ShenYj** [comment]
> Hi, you can enable it like this!
> 
> https://github.com/scenee/FloatingPanel/blob/43c7e8c2a05a32d8b1e3018e341ba3fab8285d14/Examples/Samples/Sources/UseCaseController.swift#L73

`backdropView.dismissalTapGestureRecognizer.isEnabled = true` is conflict with `isRemovalInteractionEnabled = true`

**Comment by scenee** [comment]
There is no conflict between them 🤔

**Comment by mihaicris-adoreme** [comment]
Thanks @scenee , it works!

Indeed `isRemovalInteractionEnabled` is a different thing, it is for dismissing by swiping to the edge.
