### ISSUE TITLE
Backdrop flickering after upgrading from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by sipersso** [scenee/FloatingPanel#466]
> Please fill out this template appropriately when filing a bug report.
>
> Please remove this line and everything above it before submitting.

### Description

After upgrading from 2.3.0 to 2.3.1 there is a flickering effect when the backdrop is dimmed. 

This is a video from 2.3.1
https://user-images.githubusercontent.com/6479433/119173355-7149ec80-ba67-11eb-8b95-50d31f4cd8a4.MP4

And this is how it looks after downgrading to 2.3.0

https://user-images.githubusercontent.com/6479433/119173412-8888da00-ba67-11eb-91f9-6c215e80fd97.MP4

### Steps to reproduce

**Code example that reproduces the issue**

**How do you display panel(s)?**

I present it modally

**How many panels do you displays?**
1 

**Library version**
2.3.1

**Installation method**
Swift Package Manager

**Comment by scenee** [comment]
Oh, i'm really sorry it's a regression in 2.3.1. Thanks for your quick report. I would like to fix this ASAP but I can't reproduce it. Could give more information about your implementation, or give me a sample code to reproduce it?

**Comment by scenee** [comment]
I might have found the cause of this issue. So I created a patch in [iss-466](https://github.com/scenee/FloatingPanel/tree/iss-466) branch. It would be helpful if you could try the branch.

**Comment by sipersso** [comment]
Thanks... Sorry for not being responsive and providing you with details. Have had a super busy week. Thanks for all the hard work you put into this.

**Comment by scenee** [comment]
No problem, @sipersso :) I'm ok whenever you can.

**Comment by sipersso** [comment]
Finally had a chance to try out the branch and can confirm that the iss-466 branch fixes the issue. Great job!

**Comment by scenee** [comment]
@sipersso Thank you so much! I've merged the patch into master. I will release v2.4.0 later.

**Comment by sipersso** [comment]
Glad I could help! @scenee
