### ISSUE TITLE
Panning gesture doesn't work when content is short

### ISSUE THREAD

**Issue by futuretap** [SCENEE/FloatingPanel#47]
Please see my [variation of the sample app](https://github.com/futuretap/FloatingPanel/tree/panning-issue) where I added a panel presented below a subview which uses a UITableViewController as content vc that has only 3 cells.

When I pan rather slowly, the panel doesn't track the movement and one can not change the panel positions. Only a fast swipe works but the gesture in general becomes very hard to use.

The problem seems to be related to the contentSize of the tableView. When I increase the number of cells to 20, everything works fine (albeit with the [bottom inset problem](https://github.com/SCENEE/FloatingPanel/pull/40#issuecomment-438302718) I described).

**Comment by SCENEE** [comment]
I think `fix-gesture-failure-requirements` branch fix this issue. Could you try it?

**Comment by SCENEE** [comment]
I created PR #48  for this issue. I found some critical bugs by your report. I really appreciate you.

**Comment by futuretap** [comment]
Thanks, your fix works fine.
