### ISSUE TITLE
set floating panel on top of tabbar in all pages

### ISSUE THREAD

**Issue by bmp123** [scenee/FloatingPanel#474]
### Description
is it posible to set floating panel looks like apple music player on top of tabbar in all pages? I need open floating panel in first tab and use that on all tabs. Can get some example to use this case. Thank you

**Comment by scenee** [comment]
Unfortunately, there is no solution writing a global panel once according to the UITabBarController's design. You need to add a panel for each tab but I think you could reuse the logic using something like protocol extensions.
