### ISSUE TITLE
Inverted FloatingPanel?

### ISSUE THREAD

**Issue by joseantoniogarciay** [scenee/FloatingPanel#490]
Is there a way to invert the floating panel? That is, it starts from the top and expands towards the bottom.

**Comment by scenee** [comment]
Of course. Please try "Show Top Positioned Panel" in Samples.app. The panel uses this layout, https://github.com/scenee/FloatingPanel/blob/2.4.0/Examples/Samples/Sources/Layouts.swift#L23.

**Comment by joseantoniogarciay** [comment]
Thank you very much ^_^!
