### ISSUE TITLE
Fit to content

### ISSUE THREAD

**Issue by TSCombine** [SCENEE/FloatingPanel#50]
Hi this looks really great, I have a question more than an issue, is it possible to initially fit the height to content, instead of using the 3 positions?
If content is larger than screen height, it should go to .full and scroll should be enabled.

**Comment by Durkslol** [comment]
would be great if `FloatingPanelPosition` included `case intrinsic`

**Comment by SCENEE** [comment]
Thanks for your requests! But I'm sorry I can't understand what you expect. 
Could you please give me more detail?

**Comment by Durkslol** [comment]
I created this PR https://github.com/SCENEE/FloatingPanel/pull/57

Please have a look :)

**Comment by Durkslol** [comment]
glad to see you've picked this up! 😄

**Comment by SCENEE** [comment]
Thanks you, too. You PR gave me a great insight! 
Now i'm trying to take consistency between the intrinsic height layout and the default layout using 3 positions because .full position should be the full contents.

**Comment by SCENEE** [comment]
@TSCombine, @Durkslol 

This feature has been implemented on `next`branch for v1.3.0. If possible, please try it. Thanks.
Note I will merge `next` branch  to master and then delete it.

**Comment by SCENEE** [comment]
I supported this feature at v1.3.0 👍 Thanks for your proposal!
