### ISSUE TITLE
Some suggestions and bugs

### ISSUE THREAD

**Issue by Mosaics** [scenee/FloatingPanel#501]
FloatingPanel version 2.4.0
bug:
ftp.panGestureRecognizer.isEnabled = false does not take effect,
Only use the proxy method func floatingPanelShouldBeginDragging(_ fpc: FloatingPanelController) -> Bool returns false to achieve

Suggest：
Open the handleBackdrop(tapGesture:) api of backdropView, allowing users to customize actions,
Instead of the user, write a gesture and add it to the backdropView

**Comment by scenee** [comment]
This was fixed at 821b03376cad8d8c8fbf8c7458eb5084c5df4d6a. Could you please try the master branch?

**Comment by Mosaics** [comment]
> This was fixed at [821b033](https://github.com/scenee/FloatingPanel/commit/821b03376cad8d8c8fbf8c7458eb5084c5df4d6a). Could you please try the master branch?

I found that you have released version 2.4.1, single pod cannot be updated to 2.4.1, please confirm whether you publish

**Comment by scenee** [comment]
@Mosaics I've update the pod truck to release 2.4.1 now. Thank you for letting me know 😄
