### ISSUE TITLE
`invalidateLayout()` is not asking `delegate` for new Layout object

### ISSUE THREAD

**Issue by asiliuk** [scenee/FloatingPanel#509]
### Description
`invalidateLayout()` is not actually getting new layout object from `delegate`.

Documentation says:
>    Updates the layout object from the delegate and lays out the views managed
>    by the controller immediately.
>    
>    This method updates the `FloatingPanelLayout` object from the delegate and
>    then it calls `layoutIfNeeded()` of the root view to force the view
>    to update the layout immediately. It can be called in an
>    animation block.

But based on the code and behaviour looks like that only constraints are updated, but new layout object is not asked from the delegate.

### Expected behavior
One of the following delegate methods is called
```swift
func floatingPanel(_ fpc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout
func floatingPanel(_ fpc: FloatingPanelController, layoutFor size: CGSize) -> FloatingPanelLayout
```

### Actual behavior
Delegate methods are not called

### Steps to reproduce

**Code example that reproduces the issue**

**How do you display panel(s)?**
* Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**: 
2.5

**Installation method**:

* CocoaPods
 
**iOS version(s)**
15.1

**Xcode version**
13.1

**Comment by scenee** [comment]
Thank you so much for your mention. I will fix the method as following the doc comment. `invalidateLayout()` will reload the `func floatingPanel(_ vc:layoutFor:) -> FloatingPanelLayout`.
