### ISSUE TITLE
Issue with Maps UIKit Example

### ISSUE THREAD

**Issue by niklasgrewe** [scenee/FloatingPanel#511]
Hi, thank you very much for this library. I try to use the Maps App in the `Example` folder (without any changes). Compile with Xcode 13 and test it on iPhone 13 Pro (iOS 15) Simulator and on real iPhone 11 Pro (iOS 15) i noticed the following animation bug, when i try to swipe down the panel to the bottom position:

https://user-images.githubusercontent.com/61348836/141678616-53c240e8-6270-4611-91b2-62af7d970692.mp4

Is this a bug in the library or in the Example App?

**Comment by scenee** [comment]
@niklasgrewe I've fixed this issue on #513. Thank you so much.
