### ISSUE TITLE
TextField inside CollectionView Not working with Floating Panel show keyboard

### ISSUE THREAD

**Issue by hoangduong536** [scenee/FloatingPanel#516]
Dear admin,
TextField inside CollectionView Not working with Floating Panel show keyboard

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-11-23 at 13 53 33](https://user-images.githubusercontent.com/18218059/142982357-6c25a87b-94cc-4bb0-a35f-48614c49d03e.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-11-23 at 13 53 39](https://user-images.githubusercontent.com/18218059/142982362-1b22db31-260c-4809-8b63-eb0c8328abd1.png)

https://user-images.githubusercontent.com/18218059/142982514-d2ce082b-7050-4baa-bb6d-971da339a0a8.mov

Environment
Library version

2.5.0

Installation method

CocoaPods

iOS version(s)

15.0

Xcode version

13.1

**Comment by scenee** [comment]
This library doesn't support to change a panel's position following the keyboard. So you need to change your panel's layout manually following the keyboard notification and so on.

**Comment by Haroldthe24th** [comment]
Hi @scenee . How can we adjust it manually when the keyboard appears?
