### ISSUE TITLE
Scrolling jumps when tableView content is small

### ISSUE THREAD

**Issue by iharandreyev** [scenee/FloatingPanel#524]
### Description

Table view content jumps when content is not large

### Expected behavior

The scrolling continues properly when floating panel is expanded

### Actual behavior

The scrolling jumps

### Steps to reproduce

Open provided maps example. Go into `setUpSearchView()` function and replace `98` favorite items number with something small , for example `2`.

**How do you display panel(s)?**

Add as child view controllers

**How many panels do you display?**

1 

### Environment

**Library version**

2.5.1

**Installation method**

CocoaPods
 
**iOS version(s)**

14.5 simulator

**Xcode version**

12.5.1

https://user-images.githubusercontent.com/59689027/148980170-c6755b74-e0cb-4eb7-879e-661e7de69ef6.mp4

**Comment by iharandreyev** [comment]
Adding a large enough footer view to the table mitigates the issue. However, it is not a good enough solution since our table view base class already uses the footer, and tinkering with it will result in issues

**Comment by iharandreyev** [comment]
For anyone having the same issue, I've mitigated it with bottom inset adjustment. May share the code if someone else is interested

**Comment by scenee** [comment]
Thank you for your report. I acknowledged this issue. I will tried to fix this later.

**Comment by mustafaozdemir** [comment]
> For anyone having the same issue, I've mitigated it with bottom inset adjustment. May share the code upon request

Could you share your solution
Thanks

**Comment by scenee** [comment]
Thank you for your patience. I've fixed this issue on the master branch now. It will be released on 2.6.2.
