### ISSUE TITLE
Tap to move up

### ISSUE THREAD

**Issue by avjiang** [SCENEE/FloatingPanel#53]
Hi, nice library! Thanks for providing such helpful library!

Is there any way for us to activate the panel just by tapping on the top of the panel?

Thanks!

**Comment by SCENEE** [comment]
Hello, @avjiang.
If 'activate' means 'move up', you can use `FloatingPanelController.move(to:animated:)` method. For example, see https://github.com/SCENEE/FloatingPanel#move-a-position-with-an-animation.

**Comment by avjiang** [comment]
@SCENEE 

How can i get the top of the panel, so that i can add gesture recognizer? 

thanks
