### ISSUE TITLE
FloatingPanel detects a pan when there is only a single tap gesture.

### ISSUE THREAD

**Issue by iDevid** [scenee/FloatingPanel#533]
### Description

Hello everyone, I discovered that if we do something like pressing a button in the scrollview when the panel is ending the movement to another state, this will detect a pan gesture and it moves to another position.

I suggest somehow to add a delegate method to ask the user if the panel should move/attract to a specific state to avoid any problem.

### Expected behavior

The panel should not move to another position when the user is interacting with panel content.

### Actual behavior

The panel move to another position when the user is interacting with panel content.

### Steps to reproduce

Press a button during in the panel child while the panel is moving

**How do you display panel(s)?**

* Add as child view controllers

**How many panels do you displays?**

* 1 

### Environment

**Library version**

2.5.2

**Installation method**

* Swift Package Manager
 
**iOS version(s)**
15.1

**Xcode version**
13.2.1

**Comment by scenee** [comment]
Please try to use `FloatingPanelController.panGestureRecognizer.delegateProxy`. You are able to determine whether the panel handles a UITouch object related the button in `gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool`.
https://github.com/scenee/FloatingPanel#interrupt-the-delegate-methods-of-floatingpanelcontrollerpangesturerecognizer

```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
    if touch.view is UIButton {
        return false
    }
    return true
}
```

**Comment by iDevid** [comment]
@scenee thanks! It solved my issue 👍
