### ISSUE TITLE
How do I hide or remove the top indicator

### ISSUE THREAD

**Issue by BeingCode** [scenee/FloatingPanel#539]
![屏幕截图 2022-04-21 102048](https://user-images.githubusercontent.com/44461496/164358934-5166f1d3-891c-4086-b589-1378ba6346ae.png)

**Comment by scenee** [comment]
Grabbar is just a UIView. You are able to hide the below 😉 
```swift
fpc.surfaceView.grabberHandle.isHidden = true
```

**Comment by BeingCode** [comment]
@scenee  thank you
