### ISSUE TITLE
Customise containerView

### ISSUE THREAD

**Issue by icedice** [scenee/FloatingPanel#541]
Let me just start by applauding the great work that is done here. This is an excellent framework!

Now on to my question:
Is the anyway to customise `containerView`  that sits inside the SurfaceView?

I realise that my use-case is pretty specific but I need part of my Panel to be transpartant and to let touch events through to the views below it. Right now I'm solving it by extending `SurfaceView` and overriding `point(inside:with:)` with this implementation:

```
extension SurfaceView {
    public override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        for subview in subviews.first!.subviews { // FIXME: force uwrap not safe. This could break if floatingPanel view structure changes. Better solution needed.
            if !subview.isHidden && subview.isUserInteractionEnabled && subview.point(inside: convert(point, to: subview), with: event) {
                return true
            }
        }
        return false
    }
}
```

This does work however I dont feel good about the solution since it relies on internals of FloatingPanel and could break with a future update.  Am I missing a more cleaver solution to this problem?

**Comment by scenee** [comment]
How about access to 'SurfaceView.containerView` directly? The property is public so you can access to it instead of using 'subviews.first!'.
