### ISSUE TITLE
Panel layout doesn’t update when device rotates

### ISSUE THREAD

**Issue by Kohdepitcher** [scenee/FloatingPanel#55]
When using the floating panel in the iPad version of my app, when the iPad is rotated, the panel’s layout doesn’t update. You can see the issue with the panel when the device rotates from being landscape to portrait, the floating panel floats above the bottom of the screen. Note that I am using a custom layout for the iPad version as seen in the example project.

![489bb842-ec44-463b-b21f-934a5dbab672](https://user-images.githubusercontent.com/15321325/48612579-1be37f00-e9d5-11e8-86eb-16528bd0d47e.jpeg)

And when rotating back to landscape the floating panel’s layout is correct.
![c8962303-1257-475b-879c-1ed5dcae5581](https://user-images.githubusercontent.com/15321325/48612580-1be37f00-e9d5-11e8-800a-97b94a9ce9ca.jpeg)

Also note that the incorrect layout occurs when the device rotates into a different orientation than when my app is opened, so the issue occurs with both landscape and portrait orientations.

**Comment by SCENEE** [comment]
Does this issue happen on v1.2.0(c15d236) ? I found the same issue and fixed it.

**Comment by Kohdepitcher** [comment]
Can confirm that 1.2.0 fixes the issue
