### ISSUE TITLE
Is it possible to add another view under grabber view?

### ISSUE THREAD

**Issue by davidhsu1115** [scenee/FloatingPanel#552]
What I want to do is to add a custom button and a label under the grabber view.
Is there any way to approach it ?

**Comment by scenee** [comment]
The grabber view is just a view in the surface view https://github.com/scenee/FloatingPanel#view-hierarchy
Any custom views can be added in `FloatingPanelController.surfaceView` below the grabber view using `UIView.insertSubview(_:belowSubview:)` 😉

**Comment by davidhsu1115** [comment]
Thanks I'll give it a try !

**Comment by scenee** [comment]
I closed this issue. If you still have a problem, please feel free to reopen this.
