### ISSUE TITLE
Problem with cornerCurve with XCode 14 beta

### ISSUE THREAD

**Issue by vitaminBW** [scenee/FloatingPanel#554]
### Description
Problem with cornerCurve with XCode 14 beta

### Expected behavior
No errors

### Actual behavior
in class SurfaceAppearance
@available(iOS 13.0, *)
    public lazy var cornerCurve: CALayerCornerCurve = .circular
Error text - "Stored properties cannot be marked potentially unavailable with '@available'"

### Steps to reproduce
Just try to build a project

**How do you display panel(s)?**
Present modally

**How many panels do you displays?**
1 

### Environment

**Library version**
pod 'FloatingPanel', '~> 2.5'

**Installation method**
CocoaPods
 
**iOS version(s)**
iOS 16 beta

**Xcode version**
XCode 14 beta

**Comment by andrewdmontgomery** [comment]
I believe this was addressed in #548 which merged into [v2.5.3](https://github.com/scenee/FloatingPanel/compare/2.5.2...2.5.3)

**Comment by scenee** [comment]
Yes it is. Please use [2.5.3](https://github.com/scenee/FloatingPanel/releases/tag/2.5.3) for Xcode 14 beta.
