### ISSUE TITLE
after tap-to-dismiss action of the backdrop view, Move a position with an animation not working

### ISSUE THREAD

**Issue by iosHumhae** [scenee/FloatingPanel#559]
Display via fpc.move function does not work after closing the floating panel by tapping the background. How can I solve this?

**Comment by scenee** [comment]
If it is presented as a child view controller: The dismiss action calls `FloatingPanelController.removePanelFromParent()` internally. So you need to call `addPanel(toParent:)`  again to present a panel.

If it is presented as a modality: The dismiss action calls `FloatingPanelController.dismiss` as its name implies . So you need to present a panel again.
