### ISSUE TITLE
Floating Panel close automatically after change in PR #551

### ISSUE THREAD

**Issue by bvaillant-clgx** [scenee/FloatingPanel#561]
I'm using the Floating Panel to show a page with lots of informations but since the last update (2.5.3) every times I try to open it the floating panel close itself.

I found out that if I put the line added in the PR #551 in comment, my problem is not there anymore.

My panel are shown modally

I also have special code that dismiss the FloatingPanelController when the state is hidden that I absolutely need.
`func floatingPanelDidMove(_ fpc: FloatingPanelController) {
        if fpc.state == .hidden {
            fpc.dismiss(animated: true, completion: {
                ...
                }
           })
        }
    }`

**Comment by scenee** [comment]
Thank you for this report. I understood the side effect of the code.
Let me check one thing. Is your panel's state always `.hidden` when this problem happens?
Because I'm thinking that I will replace it with an assertion.

**Comment by scenee** [comment]
Thanks. I created [iss-561](https://github.com/scenee/FloatingPanel/tree/iss-561) branch. Could you try it in your app?

**Comment by bvaillant-clgx** [comment]
Thanks for the quick reply. It is working with your new branch.

**Comment by scenee** [comment]
Thanks for your confirmation. I'm going to merge the branch into the main line in PR #563.

**Comment by scenee** [comment]
@bvaillant-clgx I merged iss-561 branch, and then I will release it in the next release, v2.5.4. Thank you so much.
