### ISSUE TITLE
Xcode 14 build error

### ISSUE THREAD

**Issue by ilosqut** [scenee/FloatingPanel#566]
### Description
Build error from the package FloatingPanel.
FloatingPanel/Sources/SurfaceView.swift:56:6: error build: Stored properties cannot be marked potentially unavailable with '@available'

@available(iOS 13.0, *)
    public lazy var cornerCurve: CALayerCornerCurve = .circular
### Expected behavior
No error.
### Actual behavior
Error
FloatingPanel/Sources/SurfaceView.swift:56:6: error build: Stored properties cannot be marked potentially unavailable with '@available'
### Steps to reproduce
Try to build
**Code example that reproduces the issue**

**Comment by th-mustache-dk** [comment]
See #554

**Comment by scenee** [comment]
This issue has been resolved since v2.5.3. See also https://github.com/scenee/FloatingPanel/pull/548
