### ISSUE TITLE
backdropAlpha does not change when layout changes without calling invalidateLayout

### ISSUE THREAD

**Issue by WillBishop** [scenee/FloatingPanel#572]
### Description

When moving from compact to a regular size class and switching layouts as detailed in the README.md, the `backdropAlpha` method is not called until the floating panel is interacted with.

### Expected behavior

Upon setting a new layout with the `layoutFor newCollection` method, `backdropAlpha` would be called and applied.

### Actual behavior

It is not called or applied

### Steps to reproduce

Open the Maps example project and slide the floating panel to the `.full` position, note the dimmed backdrop. Now rotate to landscape, and note how the backdrop is still dimmed, until it is interacted with then snaps to 0.

**Comment by scenee** [comment]
Thank you for your report. I acknowledged this issue and I'm working on iss-572 branch. I'm going to include a bug fix for this issue on 2.5.5.
