### ISSUE TITLE
When backdrop pressed, nothing reaction 

### ISSUE THREAD

**Issue by chondrosw** [scenee/FloatingPanel#575]
Hello my name is Chondro , Nice to meet you i want to ask about Backdrop

### Description
When i put addGesture in Backdrop to dismiss, backdrop nothing do something when i pressed
### Expected behavior
When i pressed backdrop button, i can dismiss the floatingPanel
### Actual behavior
i can pressed but nothing reaction, in my case i use present to show floatingPanel
### Steps to reproduce

`floatingPanelMenuContent = FloatingPanelController()
        floatingPanelMenuContent.delegate = self
        floatingPanelMenuContent.layout = MyPanelLayout()
        let menu = ContentMenuViewController()
        floatingPanelMenuContent.set(contentViewController: menu)
        
        floatingPanelMenuContent.contentMode = .fitToBounds
        floatingPanelMenuContent.isRemovalInteractionEnabled = false
        floatingPanelMenuContent.surfaceView.addGestureRecognizer(UIGestureRecognizer(target: self, action: #selector(closeMenu)))
        floatingPanelMenuContent.backdropView.dismissalTapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(closeMenu))
        floatingPanelMenuContent.backdropView.addGestureRecognizer(UIGestureRecognizer(target: self, action: #selector(closeMenu)))

@objc func closeMenu(){
        
        self.dismiss(animated: true)
        
    }
`

**How do you display panel(s)?**

* Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**
2.5.5

**Installation method**

* CocoaPods
 
**iOS version(s)**
iOS 16

**Xcode version**
14.0

**Comment by scenee** [comment]
You don't need to set `floatingPanelMenuContent.backdropView.dismissalTapGestureRecognizer` to a tap gesture.

`dismissalTapGestureRecognizer` is built-in. You are able to use the tap gesture by enabling it as follow.
https://github.com/scenee/FloatingPanel#enabling-the-tap-to-dismiss-action-of-the-backdrop-view
