### ISSUE TITLE
SurfaceView : Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by szewah** [scenee/FloatingPanel#576]
### Description

When building app,  error for SurfaceView: Stored properties cannot be marked potentially unavailable with '@available'.

### Expected behavior
The app to build without error.

### Actual behavior
Build fails.

### Steps to reproduce

```
 let fpc = FloatingPanelController()
 fpc.delegate = self
 fpc.isRemovalInteractionEnabled = true 

```

**How do you display panel(s)?**

* Add as child view controllers

**How many panels do you displays?**

* 2+

### Environment

**Library version**
2.5.5

**Installation method**
* CocoaPods

**iOS version(s)**
14

**Xcode version**
14.2

**Comment by scenee** [comment]
> Stored properties cannot be marked potentially unavailable with '@available'.

Does this error occur on SurfaceView.cornerCurve? If so, I'm wondering why it happens on v2.5.5 because it has been fixed since [v2.5.3](https://github.com/scenee/FloatingPanel/releases/tag/2.5.3) which includes #548.
