### ISSUE TITLE
'FloatingPanelController?' has no member 'set'

### ISSUE THREAD

**Issue by campeezjesse** [SCENEE/FloatingPanel#58]
Not sure what I am doing wrong here. I am trying to set up and getting this error: 
Value of type 'FloatingPanelController?' has no member 'set'
at this line:
        fpc.set(contentViewController: contentVC)
I tried to use fps.show(contentViewController: contentVC) but then only get the clear background,

**Comment by campeezjesse** [comment]
Sorry I realized that I was on v 1.1 and needed to update pod

**Comment by KingJammin** [comment]
Yeah, I'm getting the same thing.

**Comment by campeezjesse** [comment]
I ran pod update and it was solved for me.

**Comment by KingJammin** [comment]
Yeah, same!

**Comment by SCENEE** [comment]
I'm sorry for your confusing. But good to hear that 😄
