### ISSUE TITLE
Grabber Handle is above the content for top positioned floating panels in SwiftUI

### ISSUE THREAD

**Issue by ifarooqqdigilynx** [scenee/FloatingPanel#593]
### Description
Using SwiftUI i created floating panels for both bottom and top but Grabber Handle is showing above the content for Top Positioned Floating Panels. 

### Expected behavior
Garbber Handle should stick to bottom area of panel

### Actual behaviour
Grabber Handle is showing above the content

### Steps to reproduce

**Code example that reproduces the issue**

>  .floatingPanel(delegate: topMapPanelDelegate) { proxy in
                    SignInTopPanelView(proxy: proxy, isSignup: $isSignnup, getProxyCallback: { proxyCall in
                        proxyNavigationTop = proxyCall
                    }, panelType: $panelType)
                }

                .floatingPanelSurfaceAppearance(phone5())
                .floatingPanelContentMode(.static)
                .floatingPanelContentInsetAdjustmentBehavior(.never)

**How do you display panel(s)?**
* Add as child view controllers

**How many panels do you displays?**
I have 3 panels attached to SwiftUI View

![Simulator Screen Shot - iPhone 14 Pro - 2023-06-04 at 11 38 51](https://github.com/scenee/FloatingPanel/assets/130367289/904a5bb3-36b8-4a8b-9d21-40c2fe1396ed)

* 1 
* 2+

### Environment
Xcode 14.0+

**Library version**
Latest by today

**Installation method**

* CocoaPods
 
**iOS version(s)**
iOS 14.0+

**Xcode version**
Xcode 14.2

**Comment by scenee** [comment]
Do you have a FloatingPanelLayout object for the top positioned panel? 

For example:
https://github.com/scenee/FloatingPanel/blob/a0ba3af01207d21bb4800dda9f900470e1921613/Examples/Samples/Sources/PanelLayouts.swift#L23-L31

If not, just try to prepare it and assigned it to fpc.layout in `FloatingPanelView`.

**Comment by ifarooqqdigilynx** [comment]
` func floatingPanel(_ fpc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout {
        switch postionFPC {
        case let .top(pHalf, pFull):
            return SKFloatingPanelLayout(positionHalf: CGFloat(pHalf), positionFull: CGFloat(pFull), position: .top, initialState: .tip, edgePosition: .top, tipValue: 0, showbakDrop: showBackdrop)
        case let .bottomMapUsers(pHalf, pFull):
            return SKFloatingPanelLayout(positionHalf: CGFloat(pHalf), positionFull: CGFloat(pFull), position: .bottom, initialState: .tip, edgePosition: .bottom, tipValue: 166, showbakDrop: showBackdrop)

        case let .bottomFilter(pHalf, pFull):
            return SKFloatingPanelLayout(positionHalf: CGFloat(pHalf), positionFull: CGFloat(pFull), position: .bottom, initialState: .tip, edgePosition: .bottom, tipValue: 0, showbakDrop: showBackdrop)
        }
    }
`

**Comment by scenee** [comment]
> Can you please guide how can i invalidatelayout with animation?

`invalidateLayout()` api can be use with UIKit animation. So please use `UIView.animate` API.

> Thankyou i had to replace sample code, now its working.

Sounds good! I'll close this issue. Thank you.
