### ISSUE TITLE
Make interruptable animators

### ISSUE THREAD

**Issue by CedricGatay** [SCENEE/FloatingPanel#60]
Hi,
thank you for this great library. I faced a sneaky corner case that would require me to be able to interrupt my UIViewPropertyAnimator in specific conditions (I hide the tab bar dynamically as the FloatingPanel is revealed and if the user is fast enough, state is not properly synchronized). This is due to the fact that the animation is still ongoing and further seems not enqueued but rather ignored.

My workaround consists in stopping the animation (if any) before creating a new interruptible UIViewPropertyAnimator.

But in https://github.com/SCENEE/FloatingPanel/blob/v1.2.0/Framework/Sources/FloatingPanel.swift#L445 you force the animator to be un-interruptible, which causes the app to crash. If I comment out this, everything is ok for me.

Do you think we can provide a way to setup this flag ? 

If it is a yes, I'll be happy to contribute such a feature.

**Comment by SCENEE** [comment]
Thanks for your request, @CedricGatay.  I agree with you that the control should be provided to the user.

Instead of adding a new flag(or property), I would like to remove FloatingPanel.swift#L445 👍 
So I will reinvestigate why a backdrop color's punk and find the way to fix it without the 'false' flag

**Comment by CedricGatay** [comment]
@SCENEE this work as expected for me in the branch you pointed me, thank you :)

**Comment by SCENEE** [comment]
Thank you, too. I could improve the interruptibility by your report. I appreciate it.
