### ISSUE TITLE
Scroll/tracking issue on some devices

### ISSUE THREAD

**Issue by Zeynal7** [scenee/FloatingPanel#603]
### Description
Scroll views inside the panel doesn't scroll for versions after 2.6.1 (2.6.1 is Okay)

It happens only for some devices, like iPhone 13 Pro Max, 12 Pro Max. 
Most other devices that I tested seems fine.

* Add as child view controllers

**How many panels do you displays?**

* 1 

### Environment

**Library version**
2.6.2 and later

**Installation method**

* Swift Package Manager
 
**iOS version(s)**
Latest versions

**Comment by scenee** [comment]
I've fixed this issue on 2.6.6. Thanks.
