### ISSUE TITLE
Second floating panel doesn't update to width of landscape view

### ISSUE THREAD

**Issue by szewah** [scenee/FloatingPanel#621]
### Description
After selecting a search result in the searchVC, the detail floating panel comes into view and should be the same width as the search floating panel in its landscape mode.

### Expected behavior
After selecting a search result in the searchVC, the detail floating panel is shown and should be the same width as the search floating panel in its landscape mode.

### Actual behavior
The search floating panel works fine. 

When I select a search result for the first time, the detail floating panel has issues with layout consistency in landscape mode. It opens up to more than 

`surfaceView.widthAnchor.constraint(equalToConstant: 350)`

When rotated to portrait mode, it resizes. Only after I rotate back to the landscape layout does the detail floating panel resize to the correct width constraint.

If I do a second search, the detail floating panel will adjust to the correct width.

![IMG_8622](https://github.com/scenee/FloatingPanel/assets/32065713/c78e9080-eeed-4384-b57a-627b28132f2a)
![IMG_8623](https://github.com/scenee/FloatingPanel/assets/32065713/83ba0b42-b2a1-4cf5-ada7-d27b07095b09)
![IMG_8624](https://github.com/scenee/FloatingPanel/assets/32065713/f6a577e4-f24e-4025-87f8-ef78bb1c60af)
![IMG_8625](https://github.com/scenee/FloatingPanel/assets/32065713/292a0f78-b760-4c8c-a395-7fc1fd52808b)
![IMG_8626](https://github.com/scenee/FloatingPanel/assets/32065713/fbec3ad2-2eae-496d-ab99-4bd5b82b38f7)

### Steps to reproduce

**Code example that reproduces the issue**

```
class LandscapeLayout: FloatingPanelLayout {
    
    let position: FloatingPanelPosition  = .bottom
    let initialState: FloatingPanelState = .tip
    
    let anchors: [FloatingPanelState : FloatingPanelLayoutAnchoring] = [
        .full: FloatingPanelLayoutAnchor(absoluteInset: 16.0, edge: .top, referenceGuide: .safeArea),
        .lastQuart: FloatingPanelLayoutAnchor(fractionalInset: 14.0, edge: .top, referenceGuide: .safeArea),
           .half: FloatingPanelLayoutAnchor(fractionalInset: 0.4, edge: .top, referenceGuide: .safeArea),
           .firstQuart: FloatingPanelLayoutAnchor(fractionalInset: 0.35, edge: .bottom, referenceGuide: .safeArea),
           .tip: FloatingPanelLayoutAnchor(absoluteInset: 69.0, edge: .bottom, referenceGuide: .safeArea),
    
    ]
    
    func prepareLayout(surfaceView: UIView, in view: UIView) -> [NSLayoutConstraint] {
        print("layout prepared")
           return [
               surfaceView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor, constant: 8.0),
               surfaceView.widthAnchor.constraint(equalToConstant: 350),
           ]
       }
    
    func backdropAlpha(for state: FloatingPanelState) -> CGFloat {
        return 0.0
    }
}
```

```
detailFPC.set(contentViewController: detailVC)
detailVC?.loadViewIfNeeded()
detailFPC.addPanel(toParent: self)

```
**How do you display panel(s)?**

* Add as child view controllers

**How many panels do you display?**

* 2

### Environment

**Library version**
2.8.1

**Installation method**

* CocoaPods

 
**iOS version(s)**
17

**Xcode version**
15.2

**Comment by scenee** [comment]
I confirmed the behavior of the Maps example app was the same like that. This is because it doesn't assign a custom layout instance to the `detailVC` instance.

Therefore you need to assign a `LandscapeLayout` instance to `detailFPC` like the below:

```swift
detailFpc.layout = LandscapeLayout()
```

**Comment by szewah** [comment]
Okay let me try. Thanks!

**Comment by szewah** [comment]
I added detailFpc.layout = LandscapeLayout() in the mainviewcontrollers's viewWillTransition function, after checking the views size. It works for now.
