### ISSUE TITLE
Release 2.8.2 presents error in Xcode 16 beta: 'CALayerCornerCurve' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by billThePill** [scenee/FloatingPanel#635]
### Description
My project uses FoatingPanel as a dependency on an app with a minimum deployment of iOS 14. I installed Xcode 16 beta today  and a compilation error occurred with the message  'CALayerCornerCurve' is only available in iOS 13.0 or newer

### Expected behavior
Compilation without error

### Actual behavior
Error message presented in Xcode:  'CALayerCornerCurve' is only available in iOS 13.0 or newer

### Steps to reproduce
- Install Xcode 16 beta.
- Compile app with dependency on FloatingPanel v2.8.2
- Compilation error as described on SurfaceView.swift line 63

**Code example that reproduces the issue**

None is needed as the error is within compiling the framework.

**How do you display panel(s)?**

Not applicable

**How many panels do you displays?**

Not applicable

### Environment

Xcode 16 beta (16A5171c)
Floating Panel 2.8.2 via Xcode package dependency
Targeting iOS 18

<img width="696" alt="2024-06-10_15-46-10" src="https://github.com/scenee/FloatingPanel/assets/16886642/10dfa615-13c9-4502-a953-0b61f7159e32">

**Comment by scenee** [comment]
Thank you for your quick report about Xcode 16. This issue was fixed in #636. I will release this patch in v2.8.3.

**Comment by scenee** [comment]
I've released v2.8.3 now. Thanks.
