### ISSUE TITLE
Hide floating panel

### ISSUE THREAD

**Issue by attheodo** [SCENEE/FloatingPanel#64]
I have a use case where in some cases I need to hide the floating panel entirely, preferrably with a slide-to-bottom animation. 

What would the most appropriate way to do this?

**Comment by scandiumza** [comment]
I think this might be what you're looking for, to hide the panel:
`floatingPanelController.removePanelFromParent(animated: true)`

Then when you need to present it again...
`floatingPanelController.addPanel(toParent: viewController, belowView: nil, animated: true)`

**Comment by attheodo** [comment]
I just need to hide it though, not remove it. Removing it comes with the cost of having to recreate everything again when I need it back. 

In my use case I want to hide the panel when the user scrolls downwards but show it again (the tip of it) when scrolling upwards.

**Comment by scandiumza** [comment]
I was also looking for a way to simply hide/show the panel with animation, however, after browsing the floating panel controller source the best I could find was the add/remove panel methods.

Since the floating panel controller is not responsible for instantiation of your content view controller, it won't destroy it when you remove the panel and so your content view wouldn't be recreated when you add the panel again. I can't imagine it would be that costly but I stand corrected, my use case is somewhat more forgiving and so I haven't really done any profiling.

Sorry I couldn't be of more help :)

**Comment by SCENEE** [comment]
Thanks, @scandiumza.

Hello, @attheodo,

The @scandiumza's solution is an expected way to show and hide it by this library now. As he said, `floatingPanelController.removePanelFromParent(animated: true)` doesn't recreating everything and just remove the views from the parent view controller, but it would have a cost to render everything again on re-added.

Another option is, if you don't avoid the rerendering, that you can use `FloatingPanelController.updateLayou()` to switch to offscreen layout.

```
class MainViewController: UIViewController, FloatingPanelControllerDelegate {
    var fpc: FloatingPanelController!
    var isHidden: Bool = false

   ...
   // Invoke on tip position
   func updateLayout(_ sender: Any) {
        isHidden = !isHidden

        UIView.animate(withDuration: 0.5) {
            self.fpc.updateLayout()
        }
    }

    func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout? {
        return (isHidden) ? HiddenLayout() : nil
    }
}

class HiddenLayout: FloatingPanelLayout {
    var initialPosition: FloatingPanelPosition {
        return .half
    }

    func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return 18.0
        case .half: return 262.0
        case .tip: return -34.0
        }
    }
}
```

Finally, I'm developing `FloatingPanelController.{show,hide}(animated:completion)` APIs in this PR #63. They could be expected by you.

**Comment by scandiumza** [comment]
I'm looking forward to the update, thanks for the great library @SCENEE

**Comment by attheodo** [comment]
@SCENEE thanks for the update.

Since you're at it, I think that for added flexibility it might be useful to add a `FloatingPanelPosition.custom` case instead of utilizing, the otherwise pretty standard and useful, `.tip`.

Thoughts?

**Comment by scandiumza** [comment]
I'd say I'm more in favor of the explicit show/hide that @SCENEE is currently developing, I think adding a `.custom` position may complicate matters and also result in a case where, for example, folks try to define a position between `.half `and `.full` which would kind of break this reasonably well established UI pattern. 

The upside going with an explicit hide approach is that the library could ensure that regardless of orientation and device interface type, the panel would end up off screen. I guess one could have a `.hidden` position that would achieve the same goal?

Just my opinion :)

I do like @attheodo's suggestion of having a delegate method for tapping on the panel, perhaps also one for the backdrop view (i.e. one could then have the panel collapse/move to the `.tip` position when tapping on the backdrop view).

**Comment by SCENEE** [comment]
Thanks for your options, @attheodo and @scandiumza 👍 

First, I agree with @scandiumza about FloatingPanelPosition improvement. 

I think `.custom` will introduce complication into this library and I don't know how to implement it correctly.But `.hidden` position makes sense for me after implementing `{show,hide}(animated:completion)` because It's so natural that  a user expects the `position` is `.hidden` after calling `hide(animated:completion)`. 

Then I will try to add `.hidden` position on PR #63.

Second, I don't know why you need tap delegate.

Because you can add tap gestures as below easily and customize the area and condition to handle these gestures as your design spec.
```swift
        let surfaceTapGesture = UITapGestureRecognizer(target: self, action: #selector(handleSurface(tapGesture:)))
        fpc.surfaceView.addGestureRecognizer(surfaceTapGesture)

        let backdropTapGesture = UITapGestureRecognizer(target: self, action: #selector(handleBackdrop(tapGesture:)))
        fpc.backdropView.addGestureRecognizer(backdropTapGesture)
```
Why do you need the delegate on the library side?

**Comment by scandiumza** [comment]
Thanks for considering the `.hidden` panel position @SCENEE, apart from then being able to check against that to determine if the panel is hidden, one could also call `move(to:animated:completion)` passing in `.hidden` which I imagine would have the same effect as `hide(animated:completion)`

Admittedly I hadn't looked too closely at either surfaceView or backdropView and was somehow under the impression that they weren't directly accessible, given that they are, it is indeed easy enough to just add a tap gesture, so please ignore my suggestion :)

**Comment by attheodo** [comment]
@SCENEE in my case I have the following problem with tap gesture:

When the floating panel is in the default `.tip` position, I want to "tease" via a quick-n-short upwards spring animation it if the user taps on it so he can understand he has to swipe it up. So whenever I create the panel I add the gesture recognizer on the surface view. However, when the floating panel is in half or full positions, the tap gesture recognizer intercepts all other gestures on the floating panel so I have to remove it.  I have found this to be a PITA since the `willBegingDragging` and `didEndDragging` are not sufficient to capture all possible events and positions. 

I found the `didMove` delegate method to be more granular but there I am getting different, almost random, values for `surfaceView.frame.minY` thus again making it harder to derive whether gesture recognizer should be active or not.

**Comment by SCENEE** [comment]
To @scandiumza,

Thanks for your additional insight.  I could improve PR#63 with it. Thanks again.

To @attheodo, 

> I want to "tease" via a quick-n-short upwards spring animation it if the user taps on it so he can understand he has to swipe it up.

Yeah, it looks a great UX for hinting 👍 
> However, when the floating panel is in half or full positions, the tap gesture recognizer intercepts all other gestures on the floating panel so I have to remove it.

That's strange 🤔 it doesn't block tap/long gestures.

> it harder to derive whether gesture recognizer should be active or not.

What about `floatingPanelDidChangePosition` delegate supported on v1.2.1?  You can enable/disable your surface tap gesture in the delegate method.

**Comment by SCENEE** [comment]
I supported this feature at v1.3.0 👍 Thanks for your proposal!
