### ISSUE TITLE
Documentation errors on latest version 2.8.5

### ISSUE THREAD

**Issue by garlapatisatish** [scenee/FloatingPanel#643]
### Description
Documentation errors are being seen on latest version 2.8.5.

### Expected behavior
Builds shouldn't fail for a documentation error from a dependency

### Actual behavior
Builds are failing with documentation errors from dependency, floatingPanel

### Steps to reproduce
Integrate floating panel using SPM or Carthage and try to build the Xcode project

### Environment
Xcode 15.2

**2.8.5**

**Installation method**
* Swift Package Manager
 
**iOS version(s)**
Shouldn't matter

**Xcode version**
[15.2](
<img width="474" alt="Screenshot 2024-08-30 at 1 28 42 PM" src="https://github.com/user-attachments/assets/f29c5967-01d3-493c-9ee4-11d186ec7273">
<img width="1181" alt="Screenshot 2024-08-30 at 1 28 50 PM" src="https://github.com/user-attachments/assets/b6ae59da-0d4f-416b-945a-2bca62eb4f7a">)

**Comment by scenee** [comment]
Thanks for your report. I've fixed this issue on #644.

**Comment by garlapatisatish** [comment]
Awesome. When can we expect to get it merged and cut a new release?

**Comment by garlapatisatish** [comment]
following up! 

Main reason for update was to avoid the crash issue for transitioning() and the fix was in latest 2.8.5 but until above PR is merged and a new RC is available, we can upgrade so we are still struggling with crashes.

**Comment by scenee** [comment]
I'm going to release v2.8.6 on this weekends. Thank you for your patience.
