### ISSUE TITLE
Dismissing panel by swipe doesn't update FloatingPanelPosition

### ISSUE THREAD

**Issue by skelet2394** [SCENEE/FloatingPanel#67]
I'm trying to make same behaviour like in google maps:
Move panel to .half position every time i click on button on tabbar. The problem that when i dismiss panel by swipe, fpc is not nil and position is set to .tip, so i'm trying to move it to .half instead of presenting panel
`if fpc == nil 
{
//presenting new instance of fpc
} else 
{
// if fpc.position is .tip or .full - move panel to .half, else just addPanel. So when i dismiss by gesture my app is crashing while i'm trying to show panel again
}
`
Or maybe i should check another parameter for this?
Thank you forehead

**Comment by SCENEE** [comment]
Could you try to move a panel to .half soon after adding it?

**Comment by SCENEE** [comment]
I would like to close this issue. Please feel free to reopen this if you will reproduce it on v1.4.0 or later.
