### ISSUE TITLE
An issue while setting hidesBottomBarWhenPushed = true on iOS 10

### ISSUE THREAD

**Issue by tungdx** [SCENEE/FloatingPanel#69]
Hello, first of all, thank you so much for sharing this library. It's very awesome.

However, I found that there is an issue (please check my screenshot and video)
<img width="1133" alt="screen shot 2018-11-26 at 18 00 40" src="https://user-images.githubusercontent.com/1876051/49010306-60290900-f1a5-11e8-854a-bd5c0a9a284d.png">

I set hidesBottomBarWhenPushed = true on TestVC. When running on iOS 10, there is a white bar in bottom, but it did not happen on iOS 11.

Here is the video when running the demo on simulator:
https://youtu.be/WIwcAvNYEIs

I attached the demo as well in "Samples" target

[FloatingPanel-master 2.zip](https://github.com/SCENEE/FloatingPanel/files/2615197/FloatingPanel-master.2.zip)

Hope you could help. Thank you!

**Comment by SCENEE** [comment]
Thanks for your report, @tungdx. I can't see the video, but I confirmed this issue you described as above. I will investigate the cause and try to fix it.

**Comment by tungdx** [comment]
I set the video as private, just set it as public. Anyway, thank you @SCENEE Hope you find a way to fix it.

**Comment by SCENEE** [comment]
@tungdx, actually this is not the library's issue.
Please comment out here
```diff
- openedVC.edgesForExtendedLayout = []
+ // openedVC.edgesForExtendedLayout = []
```

**Comment by tungdx** [comment]
Your're right, that's my bad. Thank you so much for your quick supporting!
