### ISSUE TITLE
How to open Panel custom height

### ISSUE THREAD

**Issue by kemalserkan** [SCENEE/FloatingPanel#7]
Hi 

How to open the panel with the custom height value?

**Comment by kemalserkan** [comment]
Thank you so much @SCENEE 

I saw the your mention after wrote here.

**Comment by akashnimare** [comment]
@SCENEE loving this project. Thanks for putting so much efforts into this :)

Had a small doubt related to this - I was wondering if we can customize the height based on the height of the device. Something like - 

```swift
 func insetFor(position: FloatingPanelPosition) -> CGFloat? {
        switch position {
        case .full: return UIScreen.main.height
        case .half: return UIScreen.main.height * 0.6
        }
    }
```

**Comment by SCENEE** [comment]
Hi, @akashnimare. 
`FloatingPanelFullScreenLayout` helps you to customize the height in the above :)
