### ISSUE TITLE
Is it possible to add FloatingPanel above some view?

### ISSUE THREAD

**Issue by kaungsoe** [SCENEE/FloatingPanel#73]
I have a use case where I need to show FloatingPanel above some view. 

I have a container viewcontroller which contains view controller with FloatingPanel and when FloatingPanel is scroll up, I want it to be above the container viewcontroller's navigation bar. Is this possible.

**Comment by SCENEE** [comment]
You can manage a floating panel root view in your view hierarchy on v1.3.0.  Please see the release note. https://github.com/SCENEE/FloatingPanel/releases/tag/v1.3.0

Thanks,
