### ISSUE TITLE
Horizontal scroll view inside content view

### ISSUE THREAD

**Issue by Thavasidurai** [SCENEE/FloatingPanel#76]
Hi,

First of all thank you so much for the beautiful library.

I am facing an issue when I have a horizontal collection/scroll view inside the content view controller. It handled well for vertical scroll but not for horizontal I suspect surface view's pan gesture recognizer collide with the scroll. It would be really appreciable if you help me to fix this.

Thanks in advance
Thavasi

**Comment by Thavasidurai** [comment]
Just went through closed issues it seems you have fixed it already but I am wondering why it is not working for me I am not sure what I am missing here :-(

**Comment by SCENEE** [comment]
Do you use the latest version? 
If you use the latest, can you send me a video capture of your app?

**Comment by Elshad** [comment]
@SCENEE if there is `view` with horizontal `scrollView` then up-down pan gesture does not work for `view`, works only left-right pan gesture for `scrollView`

**Comment by SCENEE** [comment]
@Elshad, Thanks for your good example! I will investigate and try to fix it.

**Comment by SCENEE** [comment]
@Thavasidurai and @Elshad,

I'm working on `fix-failure-requirements` branch.  I added 2 commits to fix the above problem.
I recognize this issue can't be fixed only on this library side, so I'm going to add a new delegate method. 

I created PR #89 to fix the change. Could you please take a look at my PR?

Thanks,
