### ISSUE TITLE
Integrate FloatingPanel into Objective C project 

### ISSUE THREAD

**Issue by quannextfunc** [SCENEE/FloatingPanel#78]
Hi @SCENEE ,
I would like to use this library inside a objective C project. Is there any efficient way to integrate ?

Thank you

**Comment by SCENEE** [comment]
Hi @quannextfunc ,

I recommend to use this library in Objective-C project as the following steps

1. Set up “Build Settings”  in your project
	* Set “Always Embedded Swift Standard Library” to “YES”
2. Add FlaotingPanelAdapter.swift
	* You must also add a “Objective-C Bridging Header”(even if it's empty).
4. Implement `FloatingPanelAdapter` with FloatingPanel in Swift

Here is an example project.

[SamplesObjCArchive.zip](https://github.com/SCENEE/FloatingPanel/files/2670310/SamplesObjCArchive.zip)

```
$ unzip SamplesObjCArchive.zip
$ cd SamplesObjC/
$ pod install
$open SamplesObjC.xcworkspace/
```

Finally, it's not possible to use FloatingPanel library directly in Objective-C. I tried to change it for ObjC,   but the change will break APIs for Swift so I'm not planning to change it for ObjC.

**Comment by pichirichi** [comment]
I managed to change it to support in ObjC, I had to pull put the Position enum out into ObjC.
FloatingPanelPosition.h
```
typedef NSString * FloatingPanelPosition NS_STRING_ENUM NS_SWIFT_NAME(FloatingPanelPosition);
FOUNDATION_EXPORT FloatingPanelPosition FloatingPanelPositionFull;
FOUNDATION_EXPORT FloatingPanelPosition FloatingPanelPositionHalf;
FOUNDATION_EXPORT FloatingPanelPosition FloatingPanelPositionTip;
FOUNDATION_EXPORT FloatingPanelPosition FloatingPanelPositionHidden;

NS_ASSUME_NONNULL_END
```
FloatingPanelPosition.m
```
FloatingPanelPosition FloatingPanelPositionFull    = @"Full";
FloatingPanelPosition FloatingPanelPositionHalf    = @"Half";
FloatingPanelPosition FloatingPanelPositionTip     = @"Tip";
FloatingPanelPosition FloatingPanelPositionHidden  = @"Hidden";
```

add the h to the bridging header and add @objc to functions/properties you want to expose to ObjC.

**Comment by newmanw** [comment]
@pichirichi you say 

> I managed to change it to support in ObjC

Assume this means within your own project.  Any way you can contribute those changes back via a PR so others that want to use this library in obj-c can?

**Comment by pichirichi** [comment]
> @pichirichi you say
> 
> > I managed to change it to support in ObjC
> 
> Assume this means within your own project. Any way you can contribute those changes back via a PR so others that want to use this library in obj-c can?

Unfortunately it is too baked into our code since we also did some iOS 9 workarounds.
for Objc it is mainly the enum and @objc where it is required.|
We are not using all the functionality the pod provides so I'm not sure we covered all aspects.

**Comment by pichirichi** [comment]
The wrapper approach might be a more elegant one, exposing the functions you need.

**Comment by SCENEE** [comment]
I created `FloatingPanelObjC.framework` in `support-objc` branch. You can try it using both of CocoaPods and Carthage.

**Carthage**

```
github "scenee/FloatingPanel" "support-objc"
```

**CocoaPods**

```
pod 'FloatingPanelObjC', git: 'https://github.com/SCENEE/FloatingPanel.git', branch: "support-objc"
```

Could you please give me your feedback?
I don't test it well, but I confirmed it worked with SamplesObjC app in this repo.

**Comment by aaronbrethorst** [comment]
I'm seeing a build error with Carthage when I try using the specified branch:

```
/Users/aaron/repos/OBANext/Carthage/Checkouts/FloatingPanel/Framework/Sources/FloatingPanelController.swift:102:18: error: method cannot be marked @objc because the type of the parameter cannot be represented in Objective-C
    @objc public init(delegate: FloatingPanelControllerDelegate? = nil) {
                 ^

CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target: FloatingPanel)
    cd /Users/aaron/repos/OBANext/Carthage/Checkouts/FloatingPanel/Framework
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
```

I can confirm this error also happens when I open `FloatingPanel.xcworkspace` and build within Xcode.

**Comment by SCENEE** [comment]
@aaronbrethorst, Thanks! I forgot to push a commit to fix the build error. Please try `b14be9f` commit.

**Comment by PasqualePuzio** [comment]
Hi all,

my 2 cents on this: we have taken the "adapter" approach recommended by @SCENEE 
I must say it proved to be a very elegant and clean solution, allowing us to preserve FloatingPanel without making any changes and integrate it into our objective c project.

Even though it may look complex at a first look, I believe in the long run it's a much better approach in terms of simplicity. With an adapter we don't need to develop and maintain an objective c porting if FloatingPanel.

**Comment by SCENEE** [comment]
Thanks for your feedback, @PasqualePuzio! I agree with you.  I actually regret that this library loses objc API full compatibility because it has CocoaTouch-like API. But now I think the adapter approach is better for the reasons as you mention above.

**Comment by royherma** [comment]
Hey @SCENEE, the lib works (thanks!), however there are a good amount of properties that I can not access, such as:

```
public var isRemovalInteractionEnabled: Bool {
     set { floatingPanel.isRemovalInteractionEnabled = newValue }
        get { return floatingPanel.isRemovalInteractionEnabled }
}
```

because they are missing their @objc accesor, any way to add these please??

**Comment by SCENEE** [comment]
Hi there, since v2.0 the lib supports the full ObjC interoperability. Stay tuned.

**Comment by SCENEE** [comment]
v2 has already supported full ObjC interoperability. Thank you for all 👍
