### ISSUE TITLE
How to pass the tab bar drag event to underneath view 

### ISSUE THREAD

**Issue by Thavasidurai** [SCENEE/FloatingPanel#83]
I have UI similar to your tab bar with floating panel example just 10px will be shown initially. Here I would like to drag the view even if I drag the tab bar. In other words, I have to detect the tab bar drag event and pass it to the underneath view.

I tried passing all the tab bar touch event to underneath view by overriding pointInside
withEvent method but tab bar actual behavior (tap detection) stopped working. 

Is there any way to differentiate the touch and drag event based on that can we pass it to the required view? if not, can you please guide me how to solve this?

**Comment by Thavasidurai** [comment]
Thanks for the quick response!
Here is the use case
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3082181/49860461-d70a0700-fe1f-11e8-8f8c-bdd94899f8ac.gif)

**Comment by SCENEE** [comment]
Thanks, @Thavasidurai. What's a problem in FloatngPanel library?

**Comment by Thavasidurai** [comment]
I am getting expected output following an ugly way!

I just added a pan gesture to the tab bar and passed it to the floating panel's handle pan gesture method it's working perfectly but I need to modify the library code to change the access control to public from private. I know this is not the right approach, Is there any other way to handle it nicely or Is it possible to provide any other provision in the library to handle it without touching library code?

**Comment by SCENEE** [comment]
How about adding a target to `FloatingPanleController.panGestureRecognizer`?

```swift
        fpc.panGestureRecognizer.addTarget(self, action: #selector(handleFloatingPanel(panGesture:)))
        ...
    }
    @objc func handleFloatingPanel(panGesture: UIPanGestureRecognizer) {
        // Do something
    }
```

**Comment by daskaliuk** [comment]
Value of type 'FloatingPanelController?' has no member 'panGestureRecognizer'

**Comment by SCENEE** [comment]
I added `panGestureRecognizer` property  in `FloatingPanelController` in [v1.1.0](https://github.com/SCENEE/FloatingPanel/releases/tag/v1.1.0) 🙂 
https://github.com/SCENEE/FloatingPanel/blob/master/Framework/Sources/FloatingPanelController.swift#L86
