### ISSUE TITLE
Full Screen Support

### ISSUE THREAD

**Issue by mergesort** [SCENEE/FloatingPanel#91]
Hi @SCENEE, I wanted to request an enhancement to FloatingPanel, and to say thank you for the work you've put into it.

I've modified the Stocks example to reflect the changes I'd like to see ideally.

![current full screen](https://user-images.githubusercontent.com/716513/50487408-4e1ccf00-09cc-11e9-93b1-3db43e889790.png)

Currently on an iPhone X/XS up to the red bar is the highest that a floating panel can go up to when setting `insetFor(position: FloatingPanelPosition) -> CGFloat?`.

The user experience I'm trying to recreate allows the view controller to go full screen, more akin to what you see in the Uber and Lyft apps. Below is what it would look like in the ideal circumstance, if I was able to set to a ViewController's `topAnchor` rather than it's safeArea's `topAnchor`.

![ideal full screen](https://user-images.githubusercontent.com/716513/50488357-0f891380-09d0-11e9-954f-9e2cba8fcbc0.png)

I messed around with the stocks example for a bit but ran into edge cases, and was wondering if you would consider implementing functionality that would allow this to be a part of the library itself.

Please let me know if I can be more clear, provide more information, or be helpful another way. Thank you so much!

**Comment by SCENEE** [comment]
Thanks, @mergesort!  I will try to implement `FloatingPanelFullScreenLayout` protocol(adopting `FloatingPanelLayout`) for the use case.

**Comment by SCENEE** [comment]
I added `FloatingPanelFullScreenLayout` protocol in `support-full-screen` branch(PR #97). `ThreeTabBarPanelLayout` in Samples app is a sample of the usage.

**Comment by mergesort** [comment]
I just got a chance to play around with this and it looks perfect to me. I really appreciate you implementing this @SCENEE!

Thanks a bunch!
