### ISSUE TITLE
How to add folatpanel to tabbar controller

### ISSUE THREAD

**Issue by sahabe1** [SCENEE/FloatingPanel#94]
When adding float panel to tabbar controller based application its showing empty panel

![simulator screen shot - iphone xr - 2018-12-31 at 18 22 34](https://user-images.githubusercontent.com/1065015/50560682-36757b80-0d29-11e9-8aca-cba6c4b9d8ab.png)

**Comment by SCENEE** [comment]
Did you use v1.3.1?
